// frontend/src/features/note-game/components/KeyboardBindingsEditor.tsx
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/shared/components/ui/button";
import { Card } from "@/shared/components/ui/card";
import { cn } from "@/lib/utils";
import { DEFAULT_NOTE_TO_KEY_MAP } from "../hooks/useKeyboardInput";

const SHARP_NOTES = ["C#", "D#", "E#", "F#", "G#", "A#", "B#"] as const;
const NATURAL_NOTES = ["C", "D", "E", "F", "G", "A", "B"] as const;
const FLAT_NOTES = ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb"] as const;

export interface KeyboardBindingsEditorProps {
	bindings: Record<string, string>;
	onChange: (bindings: Record<string, string>) => void;
	onListeningChange?: (note: string | null) => void;
}

interface NoteKeyButtonProps {
	note: string;
	assignedKey: string | undefined;
	isListening: boolean;
	onClick: () => void;
}

function NoteKeyButton({
	note,
	assignedKey,
	isListening,
	onClick,
}: NoteKeyButtonProps) {
	return (
		<Button
			variant="outline"
			onClick={onClick}
			className={cn(
				"h-16 flex-col gap-0.5 px-1",
				isListening &&
					"border-primary/40 bg-primary/5 shadow-[0_0_6px_0] shadow-primary/20",
			)}
		>
			<span className="text-sm font-bold">{note}</span>
			{isListening ? (
				<span className="text-xs text-primary/60">...</span>
			) : (
				<span className="text-xs text-muted-foreground">
					{assignedKey ?? "---"}
				</span>
			)}
		</Button>
	);
}

export function KeyboardBindingsEditor({
	bindings,
	onChange,
	onListeningChange,
}: KeyboardBindingsEditorProps) {
	const [listeningNote, setListeningNote] = useState<string | null>(null);

	const setListening = useCallback(
		(note: string | null) => {
			setListeningNote(note);
			onListeningChange?.(note);
		},
		[onListeningChange],
	);

	useEffect(() => {
		if (listeningNote === null) return;

		function handleKeyDown(e: KeyboardEvent) {
			e.preventDefault();

			if (e.key === "Escape") {
				e.stopPropagation();
				setListening(null);
				return;
			}

			const pressedKey = e.key;
			const oldKey = bindings[listeningNote!];
			const conflictingNote = Object.entries(bindings).find(
				([note, key]) => key === pressedKey && note !== listeningNote,
			);

			const updated = { ...bindings };
			updated[listeningNote!] = pressedKey;

			if (conflictingNote && oldKey) {
				updated[conflictingNote[0]] = oldKey;
			}

			onChange(updated);
			setListening(null);
		}

		document.addEventListener("keydown", handleKeyDown, { capture: true });
		return () =>
			document.removeEventListener("keydown", handleKeyDown, { capture: true });
	}, [listeningNote, bindings, onChange, setListening]);

	function renderRow(label: string, notes: readonly string[]) {
		return (
			<div className="space-y-1">
				<span className="text-xs font-medium text-muted-foreground">
					{label}
				</span>
				<div className="grid grid-cols-7 gap-2">
					{notes.map((note) => (
						<NoteKeyButton
							key={note}
							note={note}
							assignedKey={bindings[note]}
							isListening={listeningNote === note}
							onClick={() => setListening(note)}
						/>
					))}
				</div>
			</div>
		);
	}

	return (
		<Card className="space-y-4 p-4">
			{renderRow("Sharps", SHARP_NOTES)}
			{renderRow("Naturals", NATURAL_NOTES)}
			{renderRow("Flats", FLAT_NOTES)}
			<div className="flex justify-end pt-2">
				<Button
					variant="ghost"
					size="sm"
					onClick={() => onChange(DEFAULT_NOTE_TO_KEY_MAP)}
				>
					Reset to Defaults
				</Button>
			</div>
		</Card>
	);
}

// frontend/src/app/features/note-game/components/keyboard-bindings-editor/keyboard-bindings-editor.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	model,
	output,
	signal,
} from "@angular/core";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { filter, fromEvent } from "rxjs";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CardDirective } from "../../../../shared/components/ui/card.directive";
import { cn } from "../../../../shared/utils/cn";
import { DEFAULT_NOTE_TO_KEY_MAP } from "../../models/keymap";

/**
 * Rebinds the 21 note keys. Port of
 * frontend-react/src/features/note-game/components/KeyboardBindingsEditor.tsx.
 *
 * Click a note, press a key, done. If that key already belonged to another
 * note the two swap, so the map never has a hole in it -- React's behaviour,
 * and the reason the editor holds a draft rather than saving per keystroke.
 *
 * **The listener runs in the capture phase, and that is load-bearing.** React
 * used `{ capture: true }` so Escape could cancel "listening" without also
 * reaching the dialog's own Escape handler and closing the dialog. A capture
 * listener on `document` runs before anything else sees the event, so
 * `stopPropagation()` there really does stop it -- an Angular
 * `(document:keydown)` host binding is bubble-phase and would fire *after*
 * `<app-dialog>`'s, which is why this one is a stream instead.
 *
 * (The game's own keydown stream is a separate matter: it is switched off
 * through `NoteGameService.inputDisabled` while the dialog is open, so
 * rebinding "C" cannot also answer "C".)
 *
 * The three row labels are the *editor's* own, not the shared
 * `NATURAL_NOTES`: they are 21 accidental-bearing names, and React declared
 * them here for the same reason.
 */

const SHARP_NOTES = ["C#", "D#", "E#", "F#", "G#", "A#", "B#"] as const;
const NATURAL_NOTES = ["C", "D", "E", "F", "G", "A", "B"] as const;
const FLAT_NOTES = ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb"] as const;

@Component({
	selector: "app-keyboard-bindings-editor",
	imports: [ButtonComponent, CardDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	template: `
		<div appCard className="space-y-4 p-4">
			@for (row of rows; track row.label) {
				<div class="space-y-1">
					<span class="text-xs font-medium text-muted-foreground">{{
						row.label
					}}</span>
					<div class="grid grid-cols-7 gap-2">
						@for (note of row.notes; track note) {
							<app-button
								variant="outline"
								[className]="buttonClasses(note)"
								(click)="arm(note)"
							>
								<span class="text-sm font-bold">{{ note }}</span>
								@if (listening() === note) {
									<span class="text-xs text-primary/60">...</span>
								} @else {
									<span class="text-xs text-muted-foreground">{{
										bindings()[note] ?? "---"
									}}</span>
								}
							</app-button>
						}
					</div>
				</div>
			}
			<div class="flex justify-end pt-2">
				<app-button variant="ghost" size="sm" (click)="resetToDefaults()">
					Reset to Defaults
				</app-button>
			</div>
		</div>
	`,
})
export class KeyboardBindingsEditorComponent {
	readonly bindings = model.required<Record<string, string>>();

	/** The note awaiting a key, or null. The dialog title reads it. */
	readonly listeningChange = output<string | null>();

	protected readonly listening = signal<string | null>(null);

	protected readonly rows = [
		{ label: "Sharps", notes: SHARP_NOTES },
		{ label: "Naturals", notes: NATURAL_NOTES },
		{ label: "Flats", notes: FLAT_NOTES },
	] as const;

	constructor() {
		fromEvent<KeyboardEvent>(document, "keydown", { capture: true })
			.pipe(
				filter(() => this.listening() !== null),
				takeUntilDestroyed(),
			)
			.subscribe((event) => this.capture(event));
	}

	protected buttonClasses(note: string): string {
		return cn(
			"h-16 flex-col gap-0.5 px-1",
			this.listening() === note &&
				"border-primary/40 bg-primary/5 shadow-[0_0_6px_0] shadow-primary/20",
		);
	}

	protected arm(note: string): void {
		this.setListening(note);
	}

	protected resetToDefaults(): void {
		this.bindings.set({ ...DEFAULT_NOTE_TO_KEY_MAP });
	}

	private capture(event: KeyboardEvent): void {
		const note = this.listening();
		if (note === null) return;

		event.preventDefault();
		// Nothing else may act on the key that is being bound -- least of all
		// the dialog's Escape-to-close.
		event.stopPropagation();

		if (event.key === "Escape") {
			this.setListening(null);
			return;
		}

		const current = this.bindings();
		const previousKey = current[note];
		const conflicting = Object.entries(current).find(
			([other, key]) => key === event.key && other !== note,
		);

		const updated = { ...current, [note]: event.key };
		// The displaced note inherits the key this one was using, so a swap
		// never leaves a note unbound.
		if (conflicting && previousKey) updated[conflicting[0]] = previousKey;

		this.bindings.set(updated);
		this.setListening(null);
	}

	private setListening(note: string | null): void {
		this.listening.set(note);
		this.listeningChange.emit(note);
	}
}
