// frontend/src/app/core/components/navigation/navigation.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	signal,
} from "@angular/core";
import { toSignal } from "@angular/core/rxjs-interop";
import { NavigationEnd, Router, RouterLink } from "@angular/router";
import { NgIcon } from "@ng-icons/core";
import { filter, map } from "rxjs";

import { AuthService } from "../../../auth/services/auth.service";
import { AuthStore } from "../../../auth/services/auth.store";
import { FriendsUiStore } from "../../../features/friends/services/friends.store";
import { ButtonComponent } from "../../../shared/components/ui/button.component";
import { cn } from "../../../shared/utils/cn";
import { ThemeStore } from "../../services/theme.store";

interface NavLink {
	to: string;
	label: string;
}

interface GameLink extends NavLink {
	description: string;
}

/**
 * Port of frontend-react/src/shared/components/layout/Navigation.tsx.
 *
 * The chrome that wraps every route: brand, primary links, the Games
 * dropdown, role-dependent links, the theme toggle, the friends toggle and
 * the account menu.
 *
 * Two things here are acceptance criteria rather than styling:
 *
 * - **The accessible names.** `Switch to light theme` / `Switch to dark
 *   theme`, `Open friends` / `Close friends`, `Open menu` / `Close menu`,
 *   `Account menu`. Phase 0 added them to the React app precisely so the
 *   parity suite could reach these controls, and the toggle's name is how
 *   a spec reads the current theme.
 * - **Menus are `@if`-ed, never CSS-hidden.** A spec asserts a signed-in
 *   user's name is *visible* after login; if the closed account dropdown
 *   still rendered that name into the DOM, `getByText(...).first()` would
 *   pick the hidden copy. React mounted these conditionally and so do we.
 *
 * DESIGN.md rule 3: the selected state is an ink fill, never brass, and
 * `hover:bg-accent` is the quiet wash.
 */
@Component({
	selector: "app-navigation",
	imports: [ButtonComponent, NgIcon, RouterLink],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./navigation.component.html",
	host: { "(document:keydown)": "onDocumentKeydown($event)" },
})
export class NavigationComponent {
	private readonly router = inject(Router);
	private readonly auth = inject(AuthService);

	protected readonly store = inject(AuthStore);
	protected readonly theme = inject(ThemeStore);
	protected readonly friends = inject(FriendsUiStore);

	protected readonly mobileMenuOpen = signal(false);
	protected readonly userMenuOpen = signal(false);
	protected readonly gamesMenuOpen = signal(false);

	protected readonly primaryLinks: NavLink[] = [
		{ to: "/home", label: "Tremolo" },
		{ to: "/sheet-music", label: "Practice" },
	];

	protected readonly gameLinks: GameLink[] = [
		{
			to: "/note-game",
			label: "Note Game",
			description: "Name notes on the staff",
		},
		{
			to: "/key-signature-game",
			label: "Key Signatures",
			description: "Name the key from its signature",
		},
		{
			to: "/interval-game",
			label: "Intervals",
			description: "Name the distance between two notes",
		},
		{
			to: "/scale-game",
			label: "Scales",
			description: "Name the scale type you see",
		},
		{
			to: "/chord-game",
			label: "Chords",
			description: "Name the chord quality you see",
		},
	];

	protected readonly secondaryLinks: NavLink[] = [
		{ to: "/about", label: "About" },
		{ to: "/convert", label: "Convert" },
	];

	/**
	 * The current path, as a signal. React read `useLocation().pathname`;
	 * `toSignal` over the router's `NavigationEnd` stream is the same read,
	 * and it owns its own subscription (PLAN.md 5.6 -- nobody unsubscribes
	 * by hand).
	 */
	private readonly path = toSignal(
		this.router.events.pipe(
			filter((event) => event instanceof NavigationEnd),
			map(() => stripQuery(this.router.url)),
		),
		{ initialValue: stripQuery(this.router.url) },
	);

	protected readonly roleLinks = computed<NavLink[]>(() => {
		if (!this.store.isAuthenticated()) return [];
		const role = this.store.role();
		if (role === "TEACHER") return [{ to: "/classes", label: "Classes" }];
		if (role === "STUDENT")
			return [{ to: "/assignments", label: "Assignments" }];
		return [];
	});

	protected readonly isGameActive = computed(() =>
		this.gameLinks.some((link) => link.to === this.path()),
	);

	protected readonly initials = computed(() => {
		const user = this.store.user();
		if (!user) return "";
		return `${user.firstName[0] ?? ""}${user.lastName[0] ?? ""}`;
	});

	protected readonly themeLabel = computed(() =>
		this.theme.theme() === "dark"
			? "Switch to light theme"
			: "Switch to dark theme",
	);

	protected isActive(path: string): boolean {
		return this.path() === path;
	}

	/** DESIGN.md rule 3: selected = ink fill, otherwise a quiet hover wash. */
	protected navLinkClass(active: boolean, extra = ""): string {
		return cn(
			"px-4 py-2 rounded-md text-sm font-medium transition-all",
			active
				? "bg-primary text-primary-foreground"
				: "text-foreground hover:bg-accent hover:text-accent-foreground",
			extra,
		);
	}

	protected toggleGamesMenu(): void {
		this.gamesMenuOpen.update((open) => !open);
	}

	protected toggleUserMenu(): void {
		this.userMenuOpen.update((open) => !open);
	}

	protected toggleMobileMenu(): void {
		this.mobileMenuOpen.update((open) => !open);
	}

	protected closeMenus(): void {
		this.gamesMenuOpen.set(false);
		this.userMenuOpen.set(false);
	}

	protected toggleFriends(): void {
		this.friends.togglePanel();
	}

	/**
	 * React's `useLogout` cleared the session and let `ProtectedRoute`
	 * re-render, which bounced a signed-in-only page to /login while
	 * leaving a public one alone. Angular guards do not re-run on their
	 * own, so the session is cleared and the current URL is re-navigated:
	 * `onSameUrlNavigation: "reload"` (app.config.ts) makes the guards run
	 * again and reproduces both halves of that behaviour.
	 */
	protected logout(): void {
		this.auth.logout();
		this.userMenuOpen.set(false);
		this.mobileMenuOpen.set(false);
		void this.router.navigateByUrl(this.router.url);
	}

	protected onDocumentKeydown(event: KeyboardEvent): void {
		if (event.key !== "Escape") return;
		if (!this.gamesMenuOpen() && !this.userMenuOpen()) return;
		this.closeMenus();
	}
}

function stripQuery(url: string): string {
	return url.split(/[?#]/)[0] ?? url;
}

<nav
	class="sticky top-0 z-50 w-full border-b-2 border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60"
>
	<div class="container mx-auto px-4">
		<div class="flex h-16 items-center justify-between">
			<!-- Logo -->
			<a routerLink="/home" class="flex items-center space-x-2 group">
				<div
					class="rounded-lg bg-primary p-2 group-hover:scale-110 transition-transform"
				>
					<ng-icon
						name="lucideMusic"
						aria-hidden="true"
						class="h-6 w-6 text-primary-foreground"
					/>
				</div>
				<span class="font-display text-xl font-bold hidden sm:inline-block">
					Tremolo
				</span>
			</a>

			<!-- Desktop navigation -->
			<div class="hidden md:flex items-center space-x-1">
				@for (link of primaryLinks; track link.to) {
					<a [routerLink]="link.to" [class]="navLinkClass(isActive(link.to))">{{
						link.label
					}}</a>
				}

				<!-- Games menu -->
				<div class="relative">
					<button
						type="button"
						aria-haspopup="menu"
						[attr.aria-expanded]="gamesMenuOpen()"
						[class]="navLinkClass(isGameActive(), 'flex items-center gap-1')"
						(click)="toggleGamesMenu()"
					>
						Games
						<ng-icon
							name="lucideChevronDown"
							aria-hidden="true"
							class="h-4 w-4 transition-transform"
							[class.rotate-180]="gamesMenuOpen()"
						/>
					</button>

					@if (gamesMenuOpen()) {
						<div
							class="fixed inset-0 z-40"
							role="button"
							tabindex="0"
							aria-label="Close games menu"
							(click)="gamesMenuOpen.set(false)"
							(keydown.enter)="gamesMenuOpen.set(false)"
							(keydown.space)="gamesMenuOpen.set(false)"
						></div>
						<div
							class="absolute left-0 mt-2 w-72 z-50 rounded-lg border-2 border-border bg-popover p-2 shadow-lg animate-fade-in"
						>
							@for (link of gameLinks; track link.to) {
								<a
									[routerLink]="link.to"
									[class]="
										isActive(link.to)
											? 'block px-3 py-2 rounded-md transition-colors bg-primary text-primary-foreground'
											: 'block px-3 py-2 rounded-md transition-colors hover:bg-accent'
									"
									(click)="gamesMenuOpen.set(false)"
								>
									<span class="block text-sm font-medium">{{
										link.label
									}}</span>
									<span
										[class]="
											isActive(link.to)
												? 'block text-xs text-primary-foreground/80'
												: 'block text-xs text-muted-foreground'
										"
										>{{ link.description }}</span
									>
								</a>
							}
						</div>
					}
				</div>

				@for (link of roleLinks(); track link.to) {
					<a [routerLink]="link.to" [class]="navLinkClass(isActive(link.to))">{{
						link.label
					}}</a>
				}

				@for (link of secondaryLinks; track link.to) {
					<a [routerLink]="link.to" [class]="navLinkClass(isActive(link.to))">{{
						link.label
					}}</a>
				}
			</div>

			<!-- Right section: theme toggle, friends, account -->
			<div class="flex items-center space-x-2">
				<app-button
					variant="ghost"
					size="icon"
					className="rounded-full"
					[ariaLabel]="themeLabel()"
					(click)="theme.toggleTheme()"
				>
					<ng-icon
						[name]="theme.theme() === 'dark' ? 'lucideSun' : 'lucideMoon'"
						aria-hidden="true"
						class="h-5 w-5"
					/>
				</app-button>

				@if (store.isAuthenticated()) {
					<app-button
						variant="ghost"
						size="icon"
						[className]="
							friends.isPanelOpen()
								? 'rounded-full bg-accent text-accent-foreground'
								: 'rounded-full'
						"
						[ariaLabel]="
							friends.isPanelOpen() ? 'Close friends' : 'Open friends'
						"
						[ariaExpanded]="friends.isPanelOpen()"
						(click)="toggleFriends()"
					>
						<ng-icon name="lucideUsers" aria-hidden="true" class="h-5 w-5" />
					</app-button>
				}

				@if (store.isAuthenticated()) {
					<div class="relative hidden md:block">
						<button
							type="button"
							class="flex items-center justify-center h-10 w-10 rounded-full bg-primary text-primary-foreground font-bold hover:scale-110 transition-transform"
							aria-label="Account menu"
							aria-haspopup="menu"
							[attr.aria-expanded]="userMenuOpen()"
							(click)="toggleUserMenu()"
						>
							{{ initials() }}
						</button>

						@if (userMenuOpen()) {
							<div
								class="fixed inset-0 z-40"
								role="button"
								tabindex="0"
								aria-label="Close user menu"
								(click)="userMenuOpen.set(false)"
								(keydown.enter)="userMenuOpen.set(false)"
								(keydown.space)="userMenuOpen.set(false)"
							></div>
							<div
								class="absolute right-0 mt-2 w-56 z-50 rounded-lg border-2 border-border bg-popover p-2 shadow-lg animate-fade-in"
							>
								<div class="px-3 py-2 border-b-2 border-border mb-2">
									<p class="text-sm font-bold">
										{{ store.user()?.firstName }} {{ store.user()?.lastName }}
									</p>
									<p class="text-xs text-muted-foreground">
										{{ store.user()?.email }}
									</p>
								</div>
								<a
									routerLink="/dashboard"
									class="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
									(click)="userMenuOpen.set(false)"
								>
									<ng-icon
										name="lucideLayoutDashboard"
										aria-hidden="true"
										class="h-4 w-4"
									/>
									<span>Dashboard</span>
								</a>
								<a
									routerLink="/profile"
									class="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
									(click)="userMenuOpen.set(false)"
								>
									<ng-icon
										name="lucideUserCircle"
										aria-hidden="true"
										class="h-4 w-4"
									/>
									<span>Profile</span>
								</a>
								<a
									routerLink="/account"
									class="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
									(click)="userMenuOpen.set(false)"
								>
									<ng-icon
										name="lucideSettings"
										aria-hidden="true"
										class="h-4 w-4"
									/>
									<span>Account</span>
								</a>
								<div class="border-t-2 border-border my-2"></div>
								<button
									type="button"
									class="w-full flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-destructive hover:text-destructive-foreground text-sm transition-colors"
									(click)="logout()"
								>
									<ng-icon
										name="lucideLogOut"
										aria-hidden="true"
										class="h-4 w-4"
									/>
									<span>Log Out</span>
								</button>
							</div>
						}
					</div>
				} @else {
					<a routerLink="/login" class="hidden md:block">
						<app-button variant="default" size="sm">
							<ng-icon
								name="lucideUser"
								aria-hidden="true"
								class="mr-2 h-4 w-4"
							/>
							Login
						</app-button>
					</a>
				}

				<!-- Mobile menu button -->
				<app-button
					variant="ghost"
					size="icon"
					className="md:hidden"
					[ariaLabel]="mobileMenuOpen() ? 'Close menu' : 'Open menu'"
					[ariaExpanded]="mobileMenuOpen()"
					(click)="toggleMobileMenu()"
				>
					<ng-icon
						[name]="mobileMenuOpen() ? 'lucideX' : 'lucideMenu'"
						aria-hidden="true"
						class="h-6 w-6"
					/>
				</app-button>
			</div>
		</div>

		<!-- Mobile menu -->
		@if (mobileMenuOpen()) {
			<div
				class="md:hidden py-4 space-y-2 border-t-2 border-border animate-slide-in"
			>
				@for (link of primaryLinks; track link.to) {
					<a
						[routerLink]="link.to"
						[class]="navLinkClass(isActive(link.to), 'block')"
						(click)="mobileMenuOpen.set(false)"
						>{{ link.label }}</a
					>
				}

				<p
					class="px-4 pt-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground"
				>
					Games
				</p>
				@for (link of gameLinks; track link.to) {
					<a
						[routerLink]="link.to"
						[class]="navLinkClass(isActive(link.to), 'block')"
						(click)="mobileMenuOpen.set(false)"
						>{{ link.label }}</a
					>
				}

				<div class="border-t-2 border-border my-2"></div>
				@for (link of secondaryLinks; track link.to) {
					<a
						[routerLink]="link.to"
						[class]="navLinkClass(isActive(link.to), 'block')"
						(click)="mobileMenuOpen.set(false)"
						>{{ link.label }}</a
					>
				}

				@for (link of roleLinks(); track link.to) {
					<a
						[routerLink]="link.to"
						[class]="navLinkClass(isActive(link.to), 'block')"
						(click)="mobileMenuOpen.set(false)"
						>{{ link.label }}</a
					>
				}

				@if (store.isAuthenticated()) {
					<div class="border-t-2 border-border my-2"></div>
					<button
						type="button"
						class="w-full text-left px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
						(click)="toggleFriends(); mobileMenuOpen.set(false)"
					>
						Friends
					</button>
					<a
						routerLink="/dashboard"
						class="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
						(click)="mobileMenuOpen.set(false)"
						>Dashboard</a
					>
					<a
						routerLink="/profile"
						class="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
						(click)="mobileMenuOpen.set(false)"
						>Profile</a
					>
					<a
						routerLink="/account"
						class="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
						(click)="mobileMenuOpen.set(false)"
						>Account</a
					>
					<button
						type="button"
						class="w-full text-left px-4 py-2 rounded-md text-sm font-medium hover:bg-destructive hover:text-destructive-foreground"
						(click)="logout()"
					>
						Log Out
					</button>
				} @else {
					<a
						routerLink="/login"
						class="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
						(click)="mobileMenuOpen.set(false)"
						>Login</a
					>
				}
			</div>
		}
	</div>
</nav>

// new-frontend/src/components/Navigation.tsx
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Music, Menu, X, Sun, Moon, User, LogOut, LayoutDashboard, UserCircle, Settings } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export function Navigation() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const { user, logout, isAuthenticated } = useAuth();
  const { theme, toggleTheme } = useTheme();
  const location = useLocation();

  const navLinks = [
    { to: '/', label: 'Tremolo' },
    { to: '/sheet-music', label: 'Practice' },
    { to: '/note-game', label: 'Note Game' },
    { to: '/about', label: 'About' },
    { to: '/convert', label: 'Convert' },
  ];

  const isActive = (path: string) => location.pathname === path;

  const handleLogout = () => {
    logout();
    setUserMenuOpen(false);
    setMobileMenuOpen(false);
  };

  return (
    <nav className="sticky top-0 z-50 w-full border-b-2 border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <Link to="/" className="flex items-center space-x-2 group">
            <div className="rounded-lg bg-primary p-2 group-hover:scale-110 transition-transform">
              <Music className="h-6 w-6 text-primary-foreground" />
            </div>
            <span className="text-xl font-bold hidden sm:inline-block">
              Tremolo
            </span>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-1">
            {navLinks.map((link) => (
              <Link
                key={link.to}
                to={link.to}
                className={cn(
                  "px-4 py-2 rounded-md text-sm font-medium transition-all",
                  isActive(link.to)
                    ? "bg-primary text-primary-foreground"
                    : "text-foreground hover:bg-accent hover:text-accent-foreground"
                )}
              >
                {link.label}
              </Link>
            ))}
          </div>

          {/* Right Section: Theme Toggle + User Menu */}
          <div className="flex items-center space-x-2">
            {/* Theme Toggle */}
            <Button
              variant="ghost"
              size="icon"
              onClick={toggleTheme}
              className="rounded-full"
            >
              {theme === 'dark' ? (
                <Sun className="h-5 w-5" />
              ) : (
                <Moon className="h-5 w-5" />
              )}
            </Button>

            {/* Desktop User Menu */}
            {isAuthenticated ? (
              <div className="relative hidden md:block">
                <button
                  onClick={() => setUserMenuOpen(!userMenuOpen)}
                  className="flex items-center justify-center h-10 w-10 rounded-full bg-primary text-primary-foreground font-bold hover:scale-110 transition-transform"
                >
                  {user?.firstName[0]}{user?.lastName[0]}
                </button>

                {userMenuOpen && (
                  <>
                    <div
                      className="fixed inset-0 z-40"
                      onClick={() => setUserMenuOpen(false)}
                      onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && setUserMenuOpen(false)}
                      role="button"
                      tabIndex={0}
                      aria-label="Close user menu"
                    />
                    <div className="absolute right-0 mt-2 w-56 z-50 rounded-lg border-2 border-border bg-popover p-2 shadow-lg animate-fade-in">
                      <div className="px-3 py-2 border-b-2 border-border mb-2">
                        <p className="text-sm font-bold">
                          {user?.firstName} {user?.lastName}
                        </p>
                        <p className="text-xs text-muted-foreground">{user?.email}</p>
                      </div>
                      <Link
                        to="/dashboard"
                        onClick={() => setUserMenuOpen(false)}
                        className="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
                      >
                        <LayoutDashboard className="h-4 w-4" />
                        <span>Dashboard</span>
                      </Link>
                      <Link
                        to="/profile"
                        onClick={() => setUserMenuOpen(false)}
                        className="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
                      >
                        <UserCircle className="h-4 w-4" />
                        <span>Profile</span>
                      </Link>
                      <Link
                        to="/account"
                        onClick={() => setUserMenuOpen(false)}
                        className="flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-accent text-sm transition-colors"
                      >
                        <Settings className="h-4 w-4" />
                        <span>Account</span>
                      </Link>
                      <div className="border-t-2 border-border my-2" />
                      <button
                        onClick={handleLogout}
                        className="w-full flex items-center space-x-2 px-3 py-2 rounded-md hover:bg-destructive hover:text-destructive-foreground text-sm transition-colors"
                      >
                        <LogOut className="h-4 w-4" />
                        <span>Log Out</span>
                      </button>
                    </div>
                  </>
                )}
              </div>
            ) : (
              <Link to="/login" className="hidden md:block">
                <Button variant="default" size="sm">
                  <User className="mr-2 h-4 w-4" />
                  Login
                </Button>
              </Link>
            )}

            {/* Mobile Menu Button */}
            <Button
              variant="ghost"
              size="icon"
              className="md:hidden"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? (
                <X className="h-6 w-6" />
              ) : (
                <Menu className="h-6 w-6" />
              )}
            </Button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden py-4 space-y-2 border-t-2 border-border animate-slide-in">
            {navLinks.map((link) => (
              <Link
                key={link.to}
                to={link.to}
                onClick={() => setMobileMenuOpen(false)}
                className={cn(
                  "block px-4 py-2 rounded-md text-sm font-medium transition-all",
                  isActive(link.to)
                    ? "bg-primary text-primary-foreground"
                    : "text-foreground hover:bg-accent"
                )}
              >
                {link.label}
              </Link>
            ))}

            {isAuthenticated ? (
              <>
                <div className="border-t-2 border-border my-2" />
                <Link
                  to="/dashboard"
                  onClick={() => setMobileMenuOpen(false)}
                  className="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
                >
                  Dashboard
                </Link>
                <Link
                  to="/profile"
                  onClick={() => setMobileMenuOpen(false)}
                  className="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
                >
                  Profile
                </Link>
                <Link
                  to="/account"
                  onClick={() => setMobileMenuOpen(false)}
                  className="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
                >
                  Account
                </Link>
                <button
                  onClick={handleLogout}
                  className="w-full text-left px-4 py-2 rounded-md text-sm font-medium hover:bg-destructive hover:text-destructive-foreground"
                >
                  Log Out
                </button>
              </>
            ) : (
              <Link
                to="/login"
                onClick={() => setMobileMenuOpen(false)}
                className="block px-4 py-2 rounded-md text-sm font-medium hover:bg-accent"
              >
                Login
              </Link>
            )}
          </div>
        )}
      </div>
    </nav>
  );
}
