// frontend/src/app/features/dashboard/components/performance-chart/performance-chart.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
	output,
} from "@angular/core";

import {
	TremoloLineChartComponent,
	type TremoloReferenceLine,
	type TremoloSeries,
} from "../../../../shared/components/charts/tremolo-line-chart.component";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { SelectComponent } from "../../../../shared/components/ui/select.component";
import type {
	ChartInterval,
	MultiMetricChartData,
} from "../../../../shared/models/chart.models";

/**
 * Port of frontend-react/src/features/dashboard/components/PerformanceChart.tsx.
 *
 * NPM, accuracy and total questions over time. NPM shows by default; the
 * other two start hidden and the legend turns them on. Carries the interval
 * selector and, for a teacher, the my-data / class-data toggle.
 */

/**
 * One row of the chart.
 *
 * The index signature is not decoration: `TremoloChartPoint` is
 * `Record<string, string | number>`, and an interface without one is not
 * assignable to it (TypeScript gives type *aliases* an implicit index
 * signature and interfaces none). Declaring it explicitly keeps the named
 * fields typed and makes the row usable as chart data without a cast.
 */
interface PerformancePoint {
	[key: string]: string | number;
	time: string;
	npm: number;
	accuracy: number;
	sessions: number;
	questions: number;
}

const ALL_SERIES: readonly TremoloSeries[] = [
	{
		key: "npm",
		name: "Notes Per Minute",
		color: "hsl(var(--primary))",
		format: (v) => v.toFixed(1),
	},
	{
		key: "accuracy",
		name: "Accuracy",
		color: "hsl(var(--brass))",
		format: (v) => `${v.toFixed(1)}%`,
	},
	{
		key: "questions",
		name: "Total Questions",
		color: "hsl(var(--destructive))",
		format: (v) => String(Math.round(v)),
	},
];

/** Hidden until the user clicks them in the legend. */
const INITIALLY_HIDDEN: readonly string[] = ["accuracy", "questions"];

/**
 * Zips the four independent series by index.
 *
 * They are not guaranteed to be the same length, so the longest wins and a
 * missing value reads as 0 -- carried over from React, where the same
 * `?? 0` kept a short accuracy series from truncating the NPM line.
 */
function transformChartData(data: MultiMetricChartData): PerformancePoint[] {
	const maxLength = Math.max(
		data.npm.length,
		data.accuracy.length,
		data.sessionCount.length,
		data.totalQuestions.length,
	);

	const combined: PerformancePoint[] = [];
	for (let i = 0; i < maxLength; i++) {
		combined.push({
			time:
				data.npm[i]?.x ||
				data.accuracy[i]?.x ||
				data.sessionCount[i]?.x ||
				data.totalQuestions[i]?.x ||
				"",
			npm: data.npm[i]?.y ?? 0,
			accuracy: data.accuracy[i]?.y ?? 0,
			sessions: data.sessionCount[i]?.y ?? 0,
			questions: data.totalQuestions[i]?.y ?? 0,
		});
	}
	return combined;
}

function formatXAxisLabel(timestamp: unknown, interval: ChartInterval): string {
	if (typeof timestamp !== "string" || !timestamp) return "";
	const date = new Date(timestamp);
	switch (interval) {
		case "month":
			return date.toLocaleDateString("en-US", {
				month: "short",
				year: "2-digit",
			});
		case "year":
			return date.toLocaleDateString("en-US", { year: "numeric" });
		default:
			return date.toLocaleDateString("en-US", {
				month: "short",
				day: "numeric",
			});
	}
}

function formatTooltipHeader(
	timestamp: unknown,
	interval: ChartInterval,
): string {
	if (typeof timestamp !== "string" || !timestamp) return "";
	const date = new Date(timestamp);
	if (interval === "year") {
		return date.toLocaleDateString("en-US", { year: "numeric" });
	}
	if (interval === "month") {
		return date.toLocaleDateString("en-US", {
			month: "long",
			year: "numeric",
		});
	}
	return date.toLocaleDateString("en-US", {
		month: "short",
		day: "numeric",
		year: "numeric",
	});
}

@Component({
	selector: "app-performance-chart",
	imports: [
		ButtonComponent,
		SelectComponent,
		TremoloLineChartComponent,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: "block" },
	templateUrl: "./performance-chart.component.html",
})
export class PerformanceChartComponent {
	readonly chartData = input.required<MultiMetricChartData>();
	readonly interval = input.required<ChartInterval>();
	readonly isTeacher = input(false);
	readonly viewMode = input<"my" | "class">("my");

	readonly intervalChange = output<ChartInterval>();
	readonly viewModeChange = output<"my" | "class">();

	protected readonly series = ALL_SERIES;
	protected readonly initiallyHidden = INITIALLY_HIDDEN;

	protected readonly points = computed(() =>
		transformChartData(this.chartData()),
	);

	/** Under two points there is no trend to draw; React showed a note. */
	protected readonly hasTrend = computed(() => this.points().length >= 2);

	protected readonly referenceLines = computed<TremoloReferenceLine[]>(() => {
		const points = this.points();
		if (points.length < 2) return [];
		const avg = points.reduce((sum, p) => sum + p.npm, 0) / points.length;
		return [{ value: avg, label: `avg ${avg.toFixed(1)}` }];
	});

	protected readonly xTickFormatter = computed(
		() => (value: unknown) => formatXAxisLabel(value, this.interval()),
	);

	protected readonly tooltipLabelFormatter = computed(
		() => (value: unknown) => formatTooltipHeader(value, this.interval()),
	);

	protected onIntervalChange(value: string): void {
		this.intervalChange.emit(value as ChartInterval);
	}
}

<div appCard className="shadow-lg">
	<div appCardHeader>
		<div
			class="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center"
		>
			<h3 appCardTitle className="text-2xl">Performance</h3>
			<div class="flex w-full flex-col gap-2 sm:flex-row md:w-auto">
				@if (isTeacher()) {
					<div class="flex gap-2">
						<app-button
							size="sm"
							[variant]="viewMode() === 'my' ? 'default' : 'outline'"
							(click)="viewModeChange.emit('my')"
						>
							My Data
						</app-button>
						<app-button
							size="sm"
							[variant]="viewMode() === 'class' ? 'default' : 'outline'"
							(click)="viewModeChange.emit('class')"
						>
							Class Data
						</app-button>
					</div>
				}

				<app-select
					ariaLabel="Chart interval"
					[value]="interval()"
					(valueChange)="onIntervalChange($event)"
				>
					<option value="day">Daily</option>
					<option value="week">Weekly</option>
					<option value="month">Monthly</option>
					<option value="year">Yearly</option>
				</app-select>
			</div>
		</div>
	</div>
	<div appCardContent>
		@if (hasTrend()) {
			<app-tremolo-line-chart
				ariaLabel="Performance over time"
				xKey="time"
				[data]="points()"
				[series]="series"
				[height]="360"
				[xTickFormatter]="xTickFormatter()"
				[tooltipLabelFormatter]="tooltipLabelFormatter()"
				[referenceLines]="referenceLines()"
				[initialHiddenSeries]="initiallyHidden"
			/>
		} @else {
			<div
				class="flex h-[320px] items-center justify-center text-sm text-muted-foreground"
			>
				Not enough data yet — play a few games to see your trend.
			</div>
		}
	</div>
</div>

// new-frontend/src/features/dashboard/components/PerformanceChart.tsx
/**
 * Performance Chart Component
 *
 * Displays a line chart showing multiple performance metrics over time:
 * - Notes Per Minute (NPM)
 * - Accuracy percentage
 * - Session count
 * - Total questions
 *
 * Includes an interval selector for different time ranges.
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import type { MultiMetricChartData, ChartInterval } from '@/services/api/types';

interface PerformanceChartProps {
  chartData: MultiMetricChartData;
  interval: ChartInterval;
  onIntervalChange: (interval: ChartInterval) => void;
  isTeacher?: boolean;
  viewMode?: 'my' | 'class';
  onViewModeChange?: (mode: 'my' | 'class') => void;
}

/**
 * Transform API chart data to format expected by Recharts
 */
function transformChartData(data: MultiMetricChartData) {
  // Find the longest array to determine data point count
  const maxLength = Math.max(
    data.npm.length,
    data.accuracy.length,
    data.sessionCount.length,
    data.totalQuestions.length
  );

  // Create combined data points
  const combined = [];
  for (let i = 0; i < maxLength; i++) {
    combined.push({
      time:
        data.npm[i]?.x ||
        data.accuracy[i]?.x ||
        data.sessionCount[i]?.x ||
        data.totalQuestions[i]?.x ||
        '',
      npm: data.npm[i]?.y || 0,
      accuracy: data.accuracy[i]?.y || 0,
      sessions: data.sessionCount[i]?.y || 0,
      questions: data.totalQuestions[i]?.y || 0,
    });
  }

  return combined;
}

/**
 * Format x-axis labels based on interval
 */
function formatXAxisLabel(timestamp: string, interval: ChartInterval): string {
  const date = new Date(timestamp);

  switch (interval) {
    case 'day':
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    case 'week':
      return `Week ${Math.ceil(date.getDate() / 7)}`;
    case 'month':
      return date.toLocaleDateString('en-US', { month: 'short' });
    case 'year':
      return date.toLocaleDateString('en-US', { year: 'numeric' });
    default:
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  }
}

export function PerformanceChart({
  chartData,
  interval,
  onIntervalChange,
  isTeacher = false,
  viewMode = 'my',
  onViewModeChange,
}: PerformanceChartProps) {
  const transformedData = transformChartData(chartData);
  const intervalLabel = interval.charAt(0).toUpperCase() + interval.slice(1);

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <CardTitle className="text-2xl">Performance Metrics</CardTitle>
          <div className="flex flex-col sm:flex-row gap-2 w-full md:w-auto">
            {/* Teacher view mode toggle */}
            {isTeacher && onViewModeChange && (
              <div className="flex gap-2">
                <Button
                  variant={viewMode === 'my' ? 'default' : 'outline'}
                  onClick={() => onViewModeChange('my')}
                  size="sm"
                >
                  My Data
                </Button>
                <Button
                  variant={viewMode === 'class' ? 'default' : 'outline'}
                  onClick={() => onViewModeChange('class')}
                  size="sm"
                >
                  Class Data
                </Button>
              </div>
            )}

            {/* Interval selector */}
            <Select
              value={interval}
              onChange={(e) => onIntervalChange(e.target.value as ChartInterval)}
            >
              <option value="day">Daily</option>
              <option value="week">Weekly</option>
              <option value="month">Monthly</option>
              <option value="year">Yearly</option>
            </Select>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={400}>
          <LineChart data={transformedData}>
            <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
            <XAxis
              dataKey="time"
              label={{
                value: intervalLabel,
                position: 'insideBottom',
                offset: -5,
              }}
              tickFormatter={(value) => formatXAxisLabel(value, interval)}
            />
            <YAxis />
            <Tooltip
              contentStyle={{
                backgroundColor: 'hsl(var(--card))',
                border: '2px solid hsl(var(--border))',
                borderRadius: '8px',
              }}
              labelFormatter={(value) => formatXAxisLabel(value, interval)}
            />
            <Legend />
            <Line
              type="monotone"
              dataKey="npm"
              stroke="hsl(var(--primary))"
              strokeWidth={3}
              name="Notes Per Minute"
            />
            <Line
              type="monotone"
              dataKey="accuracy"
              stroke="hsl(var(--accent))"
              strokeWidth={3}
              name="Accuracy %"
            />
            <Line
              type="monotone"
              dataKey="sessions"
              stroke="hsl(var(--muted-foreground))"
              strokeWidth={2}
              name="Sessions"
            />
            <Line
              type="monotone"
              dataKey="questions"
              stroke="hsl(var(--destructive))"
              strokeWidth={2}
              name="Total Questions"
            />
          </LineChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}
