// frontend/src/app/features/dashboard/components/user-profile-card/user-profile-card.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	input,
} from "@angular/core";

import { LoggerService } from "../../../../core/services/logger.service";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import type { UserProfile } from "../../../../shared/models/user.models";

/**
 * Port of frontend-react/src/features/dashboard/components/UserProfileCard.tsx.
 *
 * Initials avatar, name, role chip, join month, and the two quick stats.
 *
 * **The name heading is an acceptance criterion.** `e2e/specs/auth.spec.ts`'s
 * "signs in and lands on the dashboard" asserts that the signed-in user's
 * "First Last" is visible after login, and this `<h1>` is the only place the
 * dashboard renders it. It was the parity suite's one known failure through
 * Phase 3.1.
 */
@Component({
	selector: "app-user-profile-card",
	imports: [...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: "block" },
	templateUrl: "./user-profile-card.component.html",
})
export class UserProfileCardComponent {
	private readonly logger = inject(LoggerService);

	readonly user = input.required<UserProfile>();
	readonly totalSessions = input.required<number>();
	readonly timeReading = input.required<string>();

	protected readonly fullName = computed(
		() => `${this.user().firstName} ${this.user().lastName}`,
	);

	protected readonly initials = computed(() => {
		const user = this.user();
		return `${user.firstName.charAt(0)}${user.lastName.charAt(0)}`;
	});

	protected readonly joinDate = computed(() =>
		new Date(this.user().createdAt).toLocaleDateString("en-US", {
			month: "long",
			year: "numeric",
		}),
	);

	/** "STUDENT" -> "Student". */
	protected readonly roleDisplay = computed(() => {
		const role = this.user().role;
		return role ? role.charAt(0) + role.slice(1).toLowerCase() : "User";
	});

	constructor() {
		// React warned from inside the render function. Here the warning lives
		// in an effect rather than in `roleDisplay`, so the computed stays pure
		// -- a computed that logs fires again on every dependency change and
		// never on a cache hit, which makes the log say nothing reliable.
		effect(() => {
			const user = this.user();
			if (!user.role) {
				this.logger.warn("Missing user.role for user", { userId: user.id });
			}
		});
	}
}

<div appCard className="shadow-lg">
	<div appCardContent className="p-6">
		<div class="flex flex-col items-center gap-6 md:flex-row md:items-start">
			<!-- Avatar -->
			<div class="flex-shrink-0">
				<div
					class="flex h-24 w-24 items-center justify-center rounded-full bg-primary text-3xl font-bold text-primary-foreground"
				>
					{{ initials() }}
				</div>
			</div>

			<!-- User info -->
			<div class="flex-1 space-y-2 text-center md:text-left">
				<h1 class="text-3xl font-bold">{{ fullName() }}</h1>
				<div
					class="flex flex-wrap items-center justify-center gap-2 md:justify-start"
				>
					<span
						class="rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary"
						>{{ roleDisplay() }}</span
					>
					<span class="text-sm text-muted-foreground"
						>Joined {{ joinDate() }}</span
					>
				</div>
			</div>

			<!-- Quick stats -->
			<div class="grid grid-cols-2 gap-4">
				<div class="text-center">
					<div class="text-3xl font-bold text-primary">
						{{ totalSessions() }}
					</div>
					<div class="text-xs text-muted-foreground">total sessions</div>
				</div>
				<div class="text-center">
					<div class="text-3xl font-bold text-brass">{{ timeReading() }}</div>
					<div class="text-xs text-muted-foreground">time reading</div>
				</div>
			</div>
		</div>
	</div>
</div>

// new-frontend/src/features/dashboard/components/UserProfileCard.tsx
/**
 * User Profile Card Component
 * 
 * Displays user information including avatar, name, role, join date,
 * and quick statistics (total sessions and time reading).
 */

import { Card, CardContent } from '@/components/ui/card';
import type { GeneralUserInfo } from '@/services/api/types';

interface QuickStats {
  totalSessions: number;
  timeReading: string;
}

interface UserProfileCardProps {
  user: GeneralUserInfo;
  quickStats: QuickStats;
}

export function UserProfileCard({ user, quickStats }: UserProfileCardProps) {
  const joinDate = new Date(user.created_at).toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
  });

  const roleDisplay = user.role.charAt(0).toUpperCase() + user.role.slice(1);

  return (
    <Card className="shadow-lg">
      <CardContent className="p-6">
        <div className="flex flex-col md:flex-row gap-6 items-center md:items-start">
          {/* Avatar */}
          <div className="flex-shrink-0">
            <div className="w-24 h-24 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-3xl font-bold">
              {user.first_name[0]}{user.last_name[0]}
            </div>
          </div>

          {/* User Info */}
          <div className="flex-1 text-center md:text-left space-y-2">
            <h1 className="text-3xl font-bold">
              {user.first_name} {user.last_name}
            </h1>
            <div className="flex flex-wrap gap-2 justify-center md:justify-start items-center">
              <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium">
                {roleDisplay}
              </span>
              <span className="text-muted-foreground text-sm">
                Joined {joinDate}
              </span>
            </div>
          </div>

          {/* Quick Stats */}
          <div className="grid grid-cols-2 gap-4">
            <div className="text-center">
              <div className="text-3xl font-bold text-primary">{quickStats.totalSessions}</div>
              <div className="text-xs text-muted-foreground">total sessions</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-accent">{quickStats.timeReading}</div>
              <div className="text-xs text-muted-foreground">time reading</div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
