// frontend-react/src/features/friends/components/AddFriendView.tsx
import { useState, useEffect, useRef } from "react";
import { ArrowLeft, Search, UserPlus, Loader2, Check } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { useSearchUsers, useAddFriend } from "@/shared/hooks/queries";
import { useDebounce } from "@/shared/hooks/useDebounce";
import { FriendCard } from "./FriendCard";

const DEBOUNCE_MS = 120;

interface AddFriendViewProps {
	onBack: () => void;
}

export function AddFriendView({ onBack }: AddFriendViewProps) {
	const [query, setQuery] = useState("");
	const debouncedQuery = useDebounce(query, DEBOUNCE_MS);
	const [addedIds, setAddedIds] = useState<Set<number>>(new Set());
	const inputRef = useRef<HTMLInputElement>(null);

	const {
		data: results = [],
		isLoading: isSearching,
		isError: searchFailed,
	} = useSearchUsers(debouncedQuery);

	const addFriend = useAddFriend();

	useEffect(() => {
		inputRef.current?.focus();
	}, []);

	const handleAdd = (friendId: number) => {
		addFriend.mutate(friendId, {
			onSuccess: () => {
				setAddedIds((prev) => new Set(prev).add(friendId));
			},
		});
	};

	return (
		<div className="flex flex-col h-full">
			<div className="p-4 border-b-2 border-border flex items-center gap-2">
				<Button
					variant="ghost"
					size="icon"
					onClick={onBack}
					className="rounded-full h-8 w-8"
					aria-label="Back to friends"
				>
					<ArrowLeft className="h-4 w-4" />
				</Button>
				<h2 className="text-lg font-bold">Add Friend</h2>
			</div>

			<div className="p-4 border-b-2 border-border">
				<div className="relative">
					<Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
					<Input
						ref={inputRef}
						placeholder="Search by name..."
						value={query}
						onChange={(e) => setQuery(e.target.value)}
						className="pl-9 pr-9"
					/>
				</div>
			</div>

			<div className="flex-1 overflow-y-auto p-2">
				{searchFailed ? (
					<div className="flex flex-col items-center justify-center h-32 gap-1">
						<p className="text-sm text-destructive text-center py-4">
							Search failed. Check your connection and try again.
						</p>
					</div>
				) : isSearching ? (
					<div className="flex items-center justify-center h-32">
						<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
					</div>
				) : results.length === 0 && debouncedQuery ? (
					<div className="flex flex-col items-center justify-center h-32 gap-1">
						<p className="text-sm font-medium text-muted-foreground">
							No users found
						</p>
					</div>
				) : results.length > 0 ? (
					results.map((user) => (
						<FriendCard
							key={user.id}
							user={user}
							action={
								<AddFriendButton
									name={`${user.firstName} ${user.lastName}`}
									isAdded={addedIds.has(user.id)}
									isAdding={
										addFriend.isPending && addFriend.variables === user.id
									}
									onAdd={() => handleAdd(user.id)}
								/>
							}
						/>
					))
				) : (
					<div className="flex flex-col items-center justify-center h-32 gap-1">
						<p className="text-sm font-medium text-muted-foreground">
							Search for someone by name
						</p>
					</div>
				)}
			</div>
		</div>
	);
}

interface AddFriendButtonProps {
	name: string;
	isAdded: boolean;
	isAdding: boolean;
	onAdd: () => void;
}

function AddFriendButton({
	name,
	isAdded,
	isAdding,
	onAdd,
}: AddFriendButtonProps) {
	return (
		<Button
			variant={isAdded ? "ghost" : "outline"}
			size="icon"
			className="rounded-full h-8 w-8 shrink-0"
			onClick={onAdd}
			disabled={isAdded || isAdding}
			aria-label={isAdded ? `${name} added` : `Add ${name}`}
		>
			{isAdding ? (
				<Loader2 className="h-4 w-4 animate-spin" />
			) : isAdded ? (
				<Check className="h-4 w-4 text-primary" />
			) : (
				<UserPlus className="h-4 w-4" />
			)}
		</Button>
	);
}

// frontend/src/app/features/friends/components/add-friend-view/add-friend-view.component.ts
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	type ElementRef,
	inject,
	output,
	signal,
	viewChild,
} from "@angular/core";
import { rxResource, toObservable, toSignal } from "@angular/core/rxjs-interop";
import { NgIcon } from "@ng-icons/core";
import { debounceTime } from "rxjs";

import { SpinnerComponent } from "../../../../core/components/spinner/spinner.component";
import { NotificationService } from "../../../../core/services/notification.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { InputDirective } from "../../../../shared/components/ui/input.directive";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type { Friend } from "../../models/friends.models";
import { FriendsService } from "../../services/friends.service";
import { FriendCardComponent } from "../friend-card/friend-card.component";

/** Unchanged from React's `AddFriendView`. */
const DEBOUNCE_MS = 120;

/**
 * The friends panel's add view. Port of
 * frontend-react/src/features/friends/components/AddFriendView.tsx.
 *
 * Two React mechanisms become one operator and one resource:
 *
 * - `useDebounce(query, 120)` is `debounceTime(120)` on the query signal's
 *   observable. The hook's `clearTimeout` cleanup is what `debounceTime`
 *   does by definition, and `toSignal` owns the subscription (PLAN.md 5.6),
 *   so there is nothing to tear down by hand.
 * - `useSearchUsers(debouncedQuery)`'s `enabled: trimmed.length > 0` is the
 *   resource's `params` returning `undefined`: a resource with undefined
 *   params stays `idle` and never calls its stream. That is also why the
 *   "Search for someone by name" prompt is the initial state -- `value()`
 *   is the default `[]` and nothing has been requested.
 *
 * Search errors are shown inline and **not** toasted, matching
 * `useSearchUsers`'s `meta.suppressErrorToast`: it fires on every keystroke
 * and a transient failure is not worth a toast. Adding a friend does toast,
 * matching `useAddFriend`'s `errorTitle`.
 *
 * Accessible names `e2e/specs/friends-and-theme.spec.ts` selects on: the
 * "Add Friend" heading, "Back to friends", the "Search by name..."
 * placeholder, and `Add <full name>` flipping to `<full name> added`.
 */
@Component({
	selector: "app-add-friend-view",
	imports: [
		ButtonComponent,
		FriendCardComponent,
		InputDirective,
		NgIcon,
		SpinnerComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: contents;
		}
	`,
	templateUrl: "./add-friend-view.component.html",
})
export class AddFriendViewComponent {
	private readonly service = inject(FriendsService);
	private readonly notifications = inject(NotificationService);

	readonly back = output<void>();

	private readonly searchInput =
		viewChild.required<ElementRef<HTMLInputElement>>("searchInput");

	protected readonly query = signal("");

	private readonly debouncedQuery = toSignal(
		toObservable(this.query).pipe(debounceTime(DEBOUNCE_MS)),
		{ initialValue: "" },
	);

	protected readonly results = rxResource({
		params: () => this.debouncedQuery().trim() || undefined,
		stream: ({ params }) => this.service.searchUsers(params),
		defaultValue: [] as Friend[],
	});

	/** Ids added during this visit -- the button flips in place, as in React. */
	protected readonly addedIds = signal<ReadonlySet<number>>(new Set<number>());
	protected readonly addingId = signal<number | null>(null);

	constructor() {
		// React focused the box in a mount effect; this is the same moment,
		// after the view exists.
		afterNextRender(() => this.searchInput().nativeElement.focus());
	}

	/** True once the debounce has settled on a non-empty query. */
	protected hasQuery(): boolean {
		return this.debouncedQuery().trim().length > 0;
	}

	protected fullName(user: Friend): string {
		return `${user.firstName} ${user.lastName}`;
	}

	protected onSearch(event: Event): void {
		this.query.set((event.target as HTMLInputElement).value);
	}

	protected add(user: Friend): void {
		if (this.addedIds().has(user.id) || this.addingId() === user.id) return;

		this.addingId.set(user.id);

		// A one-shot POST: a plain subscribe in the handler is the shape
		// PLAN.md 5.6 prescribes -- it completes after one emission.
		this.service.addFriend(user.id).subscribe({
			next: () => {
				this.addingId.set(null);
				this.addedIds.update((ids) => new Set(ids).add(user.id));
			},
			error: (error: unknown) => {
				this.addingId.set(null);
				this.notifications.showError(
					getErrorMessage(error),
					"Failed to add friend",
				);
			},
		});
	}
}

<div class="flex flex-col h-full">
	<div class="p-4 border-b-2 border-border flex items-center gap-2">
		<app-button
			variant="ghost"
			size="icon"
			className="rounded-full h-8 w-8"
			ariaLabel="Back to friends"
			(click)="back.emit()"
		>
			<ng-icon size="1rem" name="lucideArrowLeft" aria-hidden="true" />
		</app-button>
		<h2 class="text-lg font-bold">Add Friend</h2>
	</div>

	<div class="p-4 border-b-2 border-border">
		<div class="relative">
			<ng-icon
				size="1rem"
				name="lucideSearch"
				aria-hidden="true"
				class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
			/>
			<input
				#searchInput
				appInput
				type="text"
				placeholder="Search by name..."
				class="pl-9 pr-9"
				[value]="query()"
				(input)="onSearch($event)"
			/>
		</div>
	</div>

	<div class="flex-1 overflow-y-auto p-2">
		@if (results.error()) {
			<div class="flex flex-col items-center justify-center h-32 gap-1">
				<p class="text-sm text-destructive text-center py-4">
					Search failed. Check your connection and try again.
				</p>
			</div>
		} @else if (results.isLoading()) {
			<app-spinner label="Searching" />
		} @else if (results.value().length > 0) {
			@for (user of results.value(); track user.id) {
				<app-friend-card [user]="user">
					<app-button
						[variant]="addedIds().has(user.id) ? 'ghost' : 'outline'"
						size="icon"
						className="rounded-full h-8 w-8 shrink-0"
						[disabled]="addedIds().has(user.id) || addingId() === user.id"
						[ariaLabel]="
							addedIds().has(user.id)
								? fullName(user) + ' added'
								: 'Add ' + fullName(user)
						"
						(click)="add(user)"
					>
						@if (addingId() === user.id) {
							<ng-icon
								size="1rem"
								name="lucideLoader2"
								aria-hidden="true"
								class="animate-spin"
							/>
						} @else if (addedIds().has(user.id)) {
							<ng-icon
								size="1rem"
								name="lucideCheck"
								aria-hidden="true"
								class="text-primary"
							/>
						} @else {
							<ng-icon size="1rem" name="lucideUserPlus" aria-hidden="true" />
						}
					</app-button>
				</app-friend-card>
			}
		} @else {
			<div class="flex flex-col items-center justify-center h-32 gap-1">
				<p class="text-sm font-medium text-muted-foreground">
					{{ hasQuery() ? "No users found" : "Search for someone by name" }}
				</p>
			</div>
		}
	</div>
</div>
