// frontend/src/features/classes/components/ClassHeader.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Copy, Check, Users } from "lucide-react";
import { Card, CardContent } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogFooter,
} from "@/shared/components/ui/dialog";
import { useArchiveClass } from "@/shared/hooks/queries";
import type { Class } from "@/features/classes/types";

interface ClassHeaderProps {
	classItem: Class;
}

export function ClassHeader({ classItem }: ClassHeaderProps) {
	const navigate = useNavigate();
	const [copied, setCopied] = useState(false);
	const [confirmOpen, setConfirmOpen] = useState(false);
	const archiveClass = useArchiveClass();

	async function handleCopy() {
		try {
			await navigator.clipboard.writeText(classItem.joinCode);
			setCopied(true);
			setTimeout(() => setCopied(false), 1500);
		} catch {
			// Clipboard access can fail (permissions, insecure context); silently
			// no-op — the code is still visible for the teacher to read aloud.
		}
	}

	function handleArchive() {
		archiveClass.mutate(classItem.id, {
			onSuccess: () => {
				setConfirmOpen(false);
				navigate("/classes");
			},
		});
	}

	return (
		<Card>
			<CardContent className="p-6 space-y-4">
				<div className="flex flex-wrap items-start justify-between gap-4">
					<div className="min-w-0">
						<h1 className="font-display text-3xl font-bold truncate">
							{classItem.name}
						</h1>
						<span className="mt-1 flex items-center gap-1 text-sm text-muted-foreground">
							<Users className="h-4 w-4" />
							<span className="tabular-nums">{classItem.studentCount}</span>
							{classItem.studentCount === 1 ? "student" : "students"}
						</span>
					</div>
					<Button
						variant="outline"
						className="text-destructive hover:bg-destructive/10"
						onClick={() => setConfirmOpen(true)}
					>
						Archive class
					</Button>
				</div>

				<div className="flex items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary px-4 py-3 sm:max-w-xs">
					<div>
						<p className="text-[10px] uppercase tracking-wide text-muted-foreground">
							Join code
						</p>
						<p className="font-display text-2xl font-semibold tracking-widest">
							{classItem.joinCode}
						</p>
					</div>
					<Button
						type="button"
						variant="ghost"
						size="icon"
						onClick={handleCopy}
						aria-label="Copy join code"
					>
						{copied ? (
							<Check className="h-4 w-4 text-correct" />
						) : (
							<Copy className="h-4 w-4" />
						)}
					</Button>
				</div>
			</CardContent>

			<Dialog open={confirmOpen} onOpenChange={setConfirmOpen}>
				<DialogContent onOpenChange={setConfirmOpen} className="max-w-md">
					<DialogHeader>
						<DialogTitle className="font-display">Archive class?</DialogTitle>
					</DialogHeader>
					<div className="p-6">
						<p className="text-sm text-muted-foreground">
							This hides{" "}
							<span className="font-medium text-foreground">
								{classItem.name}
							</span>{" "}
							from everyone — students lose access and it can&rsquo;t be undone
							from here. Existing data is kept.
						</p>
					</div>
					<DialogFooter>
						<Button
							type="button"
							variant="outline"
							onClick={() => setConfirmOpen(false)}
							disabled={archiveClass.isPending}
						>
							Cancel
						</Button>
						<Button
							type="button"
							variant="destructive"
							loading={archiveClass.isPending}
							onClick={handleArchive}
						>
							Archive class
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</Card>
	);
}

// frontend/src/app/features/classes/components/class-header/class-header.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	signal,
} from "@angular/core";
import { Router } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { ConfirmDialogComponent } from "../../../../core/components/confirm-dialog/confirm-dialog.component";
import { NotificationService } from "../../../../core/services/notification.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { ClipboardService } from "../../../../shared/services/clipboard.service";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type { Class } from "../../models/classes.models";
import { ClassesService } from "../../services/classes.service";

/**
 * Port of frontend-react/src/features/classes/components/ClassHeader.tsx:
 * the class name, its roll count, the join code with a copy button, and the
 * archive action behind a confirm dialog.
 *
 * React's `ConfirmDialog` took a `ReactNode` description so it could bold
 * the class name inside the sentence. Phase 2's port takes a string (its
 * header records why), so the name is interpolated into the sentence
 * instead of being marked up -- the words are identical.
 */
@Component({
	selector: "app-class-header",
	imports: [
		ButtonComponent,
		ConfirmDialogComponent,
		NgIcon,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [ClipboardService],
	templateUrl: "./class-header.component.html",
})
export class ClassHeaderComponent {
	readonly classItem = input.required<Class>();

	private readonly classesService = inject(ClassesService);
	private readonly notifications = inject(NotificationService);
	private readonly router = inject(Router);
	private readonly clipboard = inject(ClipboardService);

	readonly copied = this.clipboard.copied;
	readonly confirmOpen = signal(false);
	readonly pending = signal(false);

	readonly studentLabel = computed(() =>
		this.classItem().studentCount === 1 ? "student" : "students",
	);

	readonly archiveDescription = computed(
		() =>
			`This hides ${this.classItem().name} from everyone — students lose access and it can’t be undone from here. Existing data is kept.`,
	);

	copy(): void {
		this.clipboard.copy(this.classItem().joinCode);
	}

	archive(): void {
		if (this.pending()) return;
		this.pending.set(true);

		this.classesService.archiveClass(this.classItem().id).subscribe({
			next: () => {
				this.pending.set(false);
				this.confirmOpen.set(false);
				void this.router.navigateByUrl("/classes");
			},
			error: (err: unknown) => {
				this.pending.set(false);
				this.notifications.showError(
					getErrorMessage(err),
					"Failed to archive class",
				);
			},
		});
	}
}

<div appCard>
	<div appCardContent className="p-6 space-y-4">
		<div class="flex flex-wrap items-start justify-between gap-4">
			<div class="min-w-0">
				<h1 class="font-display text-3xl font-bold truncate">
					{{ classItem().name }}
				</h1>
				<span
					class="mt-1 flex items-center gap-1 text-sm text-muted-foreground"
				>
					<ng-icon name="lucideUsers" size="1rem" aria-hidden="true" />
					<span class="tabular-nums">{{ classItem().studentCount }}</span>
					{{ studentLabel() }}
				</span>
			</div>
			<app-button
				variant="outline"
				className="text-destructive hover:bg-destructive/10"
				(click)="confirmOpen.set(true)"
			>
				Archive class
			</app-button>
		</div>

		<div
			class="flex items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary px-4 py-3 sm:max-w-xs"
		>
			<div>
				<p class="text-[10px] uppercase tracking-wide text-muted-foreground">
					Join code
				</p>
				<p class="font-display text-2xl font-semibold tracking-widest">
					{{ classItem().joinCode }}
				</p>
			</div>
			<app-button
				variant="ghost"
				size="icon"
				ariaLabel="Copy join code"
				appTooltip="Copy join code"
				(click)="copy()"
			>
				@if (copied()) {
					<ng-icon
						name="lucideCheck"
						size="1rem"
						aria-hidden="true"
						class="text-correct"
					/>
				} @else {
					<ng-icon name="lucideCopy" size="1rem" aria-hidden="true" />
				}
			</app-button>
		</div>
	</div>

	<app-confirm-dialog
		[(open)]="confirmOpen"
		title="Archive class?"
		[description]="archiveDescription()"
		confirmLabel="Archive class"
		[pending]="pending()"
		(confirm)="archive()"
	/>
</div>
