// frontend/src/features/classes/components/ClassCard.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { Copy, Check, Users } from "lucide-react";
import { Card, CardContent } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import type { Class } from "@/features/classes/types";

interface ClassCardProps {
	classItem: Class;
}

export function ClassCard({ classItem }: ClassCardProps) {
	const [copied, setCopied] = useState(false);

	async function handleCopy(e: React.MouseEvent) {
		e.preventDefault();
		e.stopPropagation();
		try {
			await navigator.clipboard.writeText(classItem.joinCode);
			setCopied(true);
			setTimeout(() => setCopied(false), 1500);
		} catch {
			// Clipboard access can fail (permissions, insecure context); silently
			// no-op — the code is still visible for the teacher to read aloud.
		}
	}

	return (
		<Link to={`/classes/${classItem.id}`} className="block">
			<Card className="h-full transition-colors hover:bg-accent/50">
				<CardContent className="p-4 space-y-4">
					<div className="flex items-start justify-between gap-2">
						<h3 className="font-display text-lg font-semibold truncate">
							{classItem.name}
						</h3>
						<span className="flex items-center gap-1 text-xs text-muted-foreground shrink-0">
							<Users className="h-3.5 w-3.5" />
							<span className="tabular-nums">{classItem.studentCount}</span>
						</span>
					</div>

					<div className="flex items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary px-3 py-2">
						<div>
							<p className="text-[10px] uppercase tracking-wide text-muted-foreground">
								Join code
							</p>
							<p className="font-display text-xl font-semibold tracking-widest">
								{classItem.joinCode}
							</p>
						</div>
						<Button
							type="button"
							variant="ghost"
							size="icon"
							onClick={handleCopy}
							aria-label="Copy join code"
						>
							{copied ? (
								<Check className="h-4 w-4 text-correct" />
							) : (
								<Copy className="h-4 w-4" />
							)}
						</Button>
					</div>
				</CardContent>
			</Card>
		</Link>
	);
}

// frontend/src/app/features/classes/components/class-card/class-card.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	inject,
	input,
} from "@angular/core";
import { RouterLink } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { ClipboardService } from "../../../../shared/services/clipboard.service";
import type { Class } from "../../models/classes.models";

/**
 * Port of frontend-react/src/features/classes/components/ClassCard.tsx: one
 * class in the teacher's grid, showing the join code the teacher actually
 * hands to students.
 *
 * `ClipboardService` is provided **here**, not at the root: `copied` is
 * per-card state, and a shared instance would light up every card's tick at
 * once (the service's own header says so).
 *
 * The copy button sits inside the card's link, so its click has to stop
 * both the default navigation and the bubble -- the same two lines React's
 * `handleCopy` ran.
 */
@Component({
	selector: "app-class-card",
	imports: [ButtonComponent, NgIcon, RouterLink, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [ClipboardService],
	templateUrl: "./class-card.component.html",
})
export class ClassCardComponent {
	readonly classItem = input.required<Class>();

	private readonly clipboard = inject(ClipboardService);
	readonly copied = this.clipboard.copied;

	copy(event: Event): void {
		event.preventDefault();
		event.stopPropagation();
		this.clipboard.copy(this.classItem().joinCode);
	}
}

<a [routerLink]="['/classes', classItem().id]" class="block">
	<div appCard className="h-full transition-colors hover:bg-accent/50">
		<div appCardContent className="p-4 space-y-4">
			<div class="flex items-start justify-between gap-2">
				<h3
					appCardTitle
					className="font-display text-lg font-semibold truncate"
				>
					{{ classItem().name }}
				</h3>
				<span
					class="flex items-center gap-1 text-xs text-muted-foreground shrink-0"
				>
					<ng-icon name="lucideUsers" size="0.875rem" aria-hidden="true" />
					<span class="tabular-nums">{{ classItem().studentCount }}</span>
				</span>
			</div>

			<div
				class="flex items-center justify-between gap-2 rounded-md border-2 border-border bg-secondary px-3 py-2"
			>
				<div>
					<p class="text-[10px] uppercase tracking-wide text-muted-foreground">
						Join code
					</p>
					<p class="font-display text-xl font-semibold tracking-widest">
						{{ classItem().joinCode }}
					</p>
				</div>
				<app-button
					variant="ghost"
					size="icon"
					ariaLabel="Copy join code"
					appTooltip="Copy join code"
					(click)="copy($event)"
				>
					@if (copied()) {
						<ng-icon
							name="lucideCheck"
							size="1rem"
							aria-hidden="true"
							class="text-correct"
						/>
					} @else {
						<ng-icon name="lucideCopy" size="1rem" aria-hidden="true" />
					}
				</app-button>
			</div>
		</div>
	</div>
</a>
