// frontend/src/app/features/note-game/components/settings-bar/settings-bar.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { AuthStore } from "../../../../auth/services/auth.store";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { DIALOG_DIRECTIVES } from "../../../../shared/components/ui/dialog.component";
import { SelectComponent } from "../../../../shared/components/ui/select.component";
import { BreakpointService } from "../../../../shared/services/breakpoint.service";
import {
	GameMode,
	NOTE_LIMITS,
	TIME_LIMITS,
} from "@features/identification-game/data";
import { type GameSettings, SCALES } from "../../models/note-game.models";
import { KeyboardBindingsDialogComponent } from "../keyboard-bindings-dialog/keyboard-bindings-dialog.component";
import { MobileSettingsDrawerComponent } from "../mobile-settings-drawer/mobile-settings-drawer.component";
import { NoteRangeSettingComponent } from "../note-range-setting/note-range-setting.component";

/**
 * The pre-game settings bar. Port of
 * frontend-react/src/features/note-game/components/SettingsBar.tsx.
 *
 * Three layouts, one mounted at a time: the full desktop bar, a one-line
 * summary that opens the drawer on phones, and a stacked summary for phone
 * landscape. React chose between three components; the flags on
 * `BreakpointService` are mutually exclusive, so three template branches are
 * the same thing.
 *
 * **The desktop bar's controls are acceptance criteria.** `useQuestionMode`
 * in `e2e/support/app.ts` drives the note game by clicking the button named
 * exactly `notes` and then the one named exactly `10`, and
 * `settings.spec.ts` reads the scale picker by its accessible name `Scale`.
 * The identification games keep the same controls behind a Settings dialog;
 * the note game keeps them inline, and that difference is what the helper
 * branches on.
 */
@Component({
	selector: "app-settings-bar",
	imports: [
		ButtonComponent,
		KeyboardBindingsDialogComponent,
		MobileSettingsDrawerComponent,
		NgIcon,
		NoteRangeSettingComponent,
		SelectComponent,
		...DIALOG_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	template: `
		@if (breakpoints.isPhoneLandscape()) {
			<button
				type="button"
				class="flex flex-col items-center justify-center gap-1 bg-card border-2 border-border rounded-lg px-2 py-2 cursor-pointer w-full h-full"
				(click)="drawerOpen.set(true)"
			>
				@for (part of summaryParts(); track part) {
					<span class="text-xs text-muted-foreground text-center">{{
						part
					}}</span>
				}
				<ng-icon
					name="lucideSettings"
					size="0.875rem"
					class="h-3.5 w-3.5 text-muted-foreground mt-1"
					aria-hidden="true"
				/>
			</button>
			<app-mobile-settings-drawer
				[settings]="settings()"
				[(open)]="drawerOpen"
				(settingsChange)="settingsChange.emit($event)"
			/>
		} @else if (breakpoints.isMobile()) {
			<button
				type="button"
				class="flex items-center justify-between bg-card border-2 border-border rounded-lg px-3 py-1.5 cursor-pointer w-full text-left"
				(click)="drawerOpen.set(true)"
			>
				<span class="text-sm text-muted-foreground truncate">{{
					summaryText()
				}}</span>
				<span class="flex-shrink-0 ml-2 p-1">
					<ng-icon
						name="lucideSettings"
						size="1rem"
						class="h-4 w-4 text-muted-foreground"
						aria-hidden="true"
					/>
				</span>
			</button>
			<app-mobile-settings-drawer
				[settings]="settings()"
				[(open)]="drawerOpen"
				(settingsChange)="settingsChange.emit($event)"
			/>
		} @else {
			<div
				class="flex flex-wrap items-center gap-2 md:gap-3 bg-card border-2 border-border rounded-lg px-3 md:px-4 py-2"
			>
				<div class="flex items-center gap-1">
					<app-button
						size="sm"
						[variant]="isTimeMode() ? 'default' : 'ghost'"
						(click)="settingsChange.emit({ gameMode: modes.Time })"
					>
						time
					</app-button>
					<app-button
						size="sm"
						[variant]="!isTimeMode() ? 'default' : 'ghost'"
						(click)="settingsChange.emit({ gameMode: modes.Notes })"
					>
						notes
					</app-button>
				</div>

				<div class="w-px bg-border self-stretch"></div>

				<div class="flex items-center gap-1">
					@for (limit of limits(); track limit) {
						<app-button
							size="sm"
							[variant]="activeLimit() === limit ? 'default' : 'ghost'"
							(click)="selectLimit(limit)"
						>
							{{ limit }}
						</app-button>
					}
				</div>

				<div class="w-px bg-border self-stretch"></div>

				<div class="flex items-center gap-2 [&>app-select]:w-auto">
					<app-select
						ariaLabel="Scale"
						className="w-28 h-9"
						[value]="settings().scale"
						(valueChange)="settingsChange.emit({ scale: $event })"
					>
						@for (scale of scales; track scale) {
							<option [value]="scale">{{ scale }}</option>
						}
					</app-select>

					<app-button
						size="sm"
						variant="outline"
						className="h-9"
						(click)="rangeDialogOpen.set(true)"
					>
						{{ settings().lowNote }}–{{ settings().highNote }}
					</app-button>

					<app-dialog [(open)]="rangeDialogOpen">
						<div appDialogContent>
							<div appDialogHeader><h2 appDialogTitle>Note Range</h2></div>
							<div class="px-6 py-4">
								<app-note-range-setting
									[clef]="settings().clef"
									[lowNote]="settings().lowNote"
									[highNote]="settings().highNote"
									(settingsChange)="settingsChange.emit($event)"
								/>
							</div>
							<div appDialogFooter>
								<app-button
									variant="default"
									(click)="rangeDialogOpen.set(false)"
								>
									Done
								</app-button>
							</div>
						</div>
					</app-dialog>
				</div>
			</div>
		}

		<button
			type="button"
			class="fixed bottom-4 right-4 z-40 p-3 rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 transition-colors"
			aria-label="Configure keyboard bindings"
			(click)="bindingsOpen.set(true)"
		>
			<ng-icon
				name="lucideKeyboard"
				size="1.25rem"
				class="h-5 w-5"
				aria-hidden="true"
			/>
		</button>

		<app-keyboard-bindings-dialog
			[(open)]="bindingsOpen"
			[canEdit]="isAuthenticated()"
			[bindings]="bindings()"
			(saveBindings)="saveBindings.emit($event)"
		/>
	`,
})
export class SettingsBarComponent {
	protected readonly breakpoints = inject(BreakpointService);
	private readonly auth = inject(AuthStore);

	readonly settings = input.required<GameSettings>();
	/** The player's current note-to-key map, for the bindings dialog. */
	readonly bindings = input.required<Record<string, string>>();

	readonly settingsChange = output<Partial<GameSettings>>();
	readonly saveBindings = output<Record<string, string>>();
	/**
	 * True while the bindings dialog is open. The page uses it to mute the
	 * game's keyboard stream so rebinding a key does not also answer with it.
	 */
	readonly bindingsOpenChange = output<boolean>();

	protected readonly modes = GameMode;
	protected readonly scales = SCALES;
	protected readonly isAuthenticated = this.auth.isAuthenticated;

	protected readonly drawerOpen = signal(false);
	protected readonly rangeDialogOpen = signal(false);
	protected readonly bindingsOpen = signal(false);

	protected readonly isTimeMode = computed(
		() => this.settings().gameMode === GameMode.Time,
	);
	protected readonly limits = computed<readonly number[]>(() =>
		this.isTimeMode() ? TIME_LIMITS : NOTE_LIMITS,
	);
	protected readonly activeLimit = computed(() =>
		this.isTimeMode() ? this.settings().timeLimit : this.settings().noteLimit,
	);

	/** The compact summary the phone layouts show instead of the controls. */
	protected readonly summaryParts = computed(() => {
		const settings = this.settings();
		const timed = this.isTimeMode();
		const limit = timed ? settings.timeLimit : settings.noteLimit;
		return [
			timed ? "time" : "notes",
			timed ? `${limit}s` : `${limit}`,
			settings.scale,
			`${settings.lowNote}–${settings.highNote}`,
		];
	});

	protected readonly summaryText = computed(() =>
		this.summaryParts().join("  /  "),
	);

	protected selectLimit(limit: number): void {
		this.settingsChange.emit(
			this.isTimeMode() ? { timeLimit: limit } : { noteLimit: limit },
		);
	}

	constructor() {
		// React relayed every open/close through one `handleDialogOpenChange`,
		// including the dialog closing itself on Escape or a backdrop click.
		// Reading the signal covers all of those in one place.
		effect(() => this.bindingsOpenChange.emit(this.bindingsOpen()));
	}
}

// frontend/src/features/note-game/components/SettingsBar.tsx
import { useState } from "react";
import { Keyboard, Settings } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Select } from "@/shared/components/ui/select";
import { useBreakpoint } from "@/shared/hooks";
import { useAuthStore } from "@/stores/auth.store";
import {
	useKeyboardBindings,
	useSaveKeyboardBindings,
} from "@/shared/hooks/queries";
import type { GameSettings as GameSettingsType } from "../types";
import { GameMode, SCALES } from "../types";
import { MobileSettingsDrawer } from "./MobileSettingsDrawer";
import { KeyboardBindingsDialog } from "./KeyboardBindingsDialog";
import { DEFAULT_NOTE_TO_KEY_MAP } from "../hooks/useKeyboardInput";
import type { KeyboardBindingsRequest } from "@/services/api/types";

export interface SettingsBarProps {
	settings: GameSettingsType;
	onSettingsChange: (settings: Partial<GameSettingsType>) => void;
	onDialogOpenChange?: (open: boolean) => void;
}

const TIME_LIMITS = [15, 30, 60, 120] as const;
const NOTE_LIMITS = [10, 25, 50, 100] as const;
const OCTAVES = [1, 2, 3, 4, 5, 6, 7, 8, 9] as const;

function Divider() {
	return <div className="w-px bg-border self-stretch" />;
}

function buildSummaryParts(settings: GameSettingsType): string[] {
	const isTimeMode = settings.gameMode === GameMode.Time;
	const activeLimit = isTimeMode ? settings.timeLimit : settings.noteLimit;
	return [
		isTimeMode ? "time" : "notes",
		isTimeMode ? `${activeLimit}s` : `${activeLimit}`,
		settings.scale,
		`Oct ${settings.octave}`,
	];
}

function SettingsBarMobile({ settings, onSettingsChange }: SettingsBarProps) {
	const [drawerOpen, setDrawerOpen] = useState(false);
	const summaryText = buildSummaryParts(settings).join("  /  ");

	return (
		<>
			<button
				type="button"
				className="flex items-center justify-between bg-card border-2 border-border rounded-lg px-3 py-1.5 cursor-pointer w-full text-left"
				onClick={() => setDrawerOpen(true)}
			>
				<span className="text-sm text-muted-foreground truncate">
					{summaryText}
				</span>
				<span className="flex-shrink-0 ml-2 p-1">
					<Settings className="h-4 w-4 text-muted-foreground" />
				</span>
			</button>
			<MobileSettingsDrawer
				settings={settings}
				onSettingsChange={onSettingsChange}
				open={drawerOpen}
				onOpenChange={setDrawerOpen}
			/>
		</>
	);
}

function SettingsBarLandscape({
	settings,
	onSettingsChange,
}: SettingsBarProps) {
	const [drawerOpen, setDrawerOpen] = useState(false);
	const summaryParts = buildSummaryParts(settings);

	return (
		<>
			<button
				type="button"
				className="flex flex-col items-center justify-center gap-1 bg-card border-2 border-border rounded-lg px-2 py-2 cursor-pointer w-full h-full"
				onClick={() => setDrawerOpen(true)}
			>
				{summaryParts.map((part) => (
					<span
						key={part}
						className="text-xs text-muted-foreground text-center"
					>
						{part}
					</span>
				))}
				<Settings className="h-3.5 w-3.5 text-muted-foreground mt-1" />
			</button>
			<MobileSettingsDrawer
				settings={settings}
				onSettingsChange={onSettingsChange}
				open={drawerOpen}
				onOpenChange={setDrawerOpen}
			/>
		</>
	);
}

function SettingsBarDesktop({ settings, onSettingsChange }: SettingsBarProps) {
	const isTimeMode = settings.gameMode === GameMode.Time;
	const limits = isTimeMode ? TIME_LIMITS : NOTE_LIMITS;
	const activeLimit = isTimeMode ? settings.timeLimit : settings.noteLimit;

	return (
		<div className="flex flex-wrap items-center gap-2 md:gap-3 bg-card border-2 border-border rounded-lg px-3 md:px-4 py-2">
			<div className="flex items-center gap-1">
				<Button
					size="sm"
					variant={isTimeMode ? "default" : "ghost"}
					onClick={() => onSettingsChange({ gameMode: GameMode.Time })}
				>
					time
				</Button>
				<Button
					size="sm"
					variant={!isTimeMode ? "default" : "ghost"}
					onClick={() => onSettingsChange({ gameMode: GameMode.Notes })}
				>
					notes
				</Button>
			</div>

			<Divider />

			<div className="flex items-center gap-1">
				{limits.map((limit) => (
					<Button
						key={limit}
						size="sm"
						variant={activeLimit === limit ? "default" : "ghost"}
						onClick={() =>
							onSettingsChange(
								isTimeMode ? { timeLimit: limit } : { noteLimit: limit },
							)
						}
					>
						{limit}
					</Button>
				))}
			</div>

			<Divider />

			<div className="flex items-center gap-2 [&>div]:w-auto">
				<Select
					className="w-28 h-9"
					value={settings.scale}
					onChange={(e) => onSettingsChange({ scale: e.target.value })}
				>
					{SCALES.map((scale) => (
						<option key={scale} value={scale}>
							{scale}
						</option>
					))}
				</Select>

				<Select
					className="w-28 h-9"
					value={settings.octave.toString()}
					onChange={(e) => onSettingsChange({ octave: Number(e.target.value) })}
				>
					{OCTAVES.map((octave) => (
						<option key={octave} value={octave}>
							Octave {octave}
						</option>
					))}
				</Select>
			</div>
		</div>
	);
}

/**
 * Responsive settings bar.
 * Conditionally renders the appropriate layout variant based on viewport,
 * so only one is ever mounted at a time.
 */
export function SettingsBar({
	settings,
	onSettingsChange,
	onDialogOpenChange,
}: SettingsBarProps) {
	const { isMobile, isPhoneLandscape } = useBreakpoint();
	const { isAuthenticated } = useAuthStore();
	const { data: savedBindings } = useKeyboardBindings();
	const saveBindings = useSaveKeyboardBindings();
	const [dialogOpen, setDialogOpen] = useState(false);

	function handleDialogOpenChange(open: boolean) {
		setDialogOpen(open);
		onDialogOpenChange?.(open);
	}

	function handleSaveBindings(noteToKey: Record<string, string>) {
		const request: KeyboardBindingsRequest = {
			key_c: noteToKey["C"] ?? "",
			key_c_sharp: noteToKey["C#"] ?? "",
			key_c_flat: noteToKey["Cb"] ?? "",
			key_d: noteToKey["D"] ?? "",
			key_d_sharp: noteToKey["D#"] ?? "",
			key_d_flat: noteToKey["Db"] ?? "",
			key_e: noteToKey["E"] ?? "",
			key_e_sharp: noteToKey["E#"] ?? "",
			key_e_flat: noteToKey["Eb"] ?? "",
			key_f: noteToKey["F"] ?? "",
			key_f_sharp: noteToKey["F#"] ?? "",
			key_f_flat: noteToKey["Fb"] ?? "",
			key_g: noteToKey["G"] ?? "",
			key_g_sharp: noteToKey["G#"] ?? "",
			key_g_flat: noteToKey["Gb"] ?? "",
			key_a: noteToKey["A"] ?? "",
			key_a_sharp: noteToKey["A#"] ?? "",
			key_a_flat: noteToKey["Ab"] ?? "",
			key_b: noteToKey["B"] ?? "",
			key_b_sharp: noteToKey["B#"] ?? "",
			key_b_flat: noteToKey["Bb"] ?? "",
		};
		saveBindings.mutate(request);
	}

	function apiResponseToNoteMap(): Record<string, string> {
		if (!savedBindings) return DEFAULT_NOTE_TO_KEY_MAP;
		return {
			C: savedBindings.key_c,
			"C#": savedBindings.key_c_sharp,
			Cb: savedBindings.key_c_flat,
			D: savedBindings.key_d,
			"D#": savedBindings.key_d_sharp,
			Db: savedBindings.key_d_flat,
			E: savedBindings.key_e,
			"E#": savedBindings.key_e_sharp,
			Eb: savedBindings.key_e_flat,
			F: savedBindings.key_f,
			"F#": savedBindings.key_f_sharp,
			Fb: savedBindings.key_f_flat,
			G: savedBindings.key_g,
			"G#": savedBindings.key_g_sharp,
			Gb: savedBindings.key_g_flat,
			A: savedBindings.key_a,
			"A#": savedBindings.key_a_sharp,
			Ab: savedBindings.key_a_flat,
			B: savedBindings.key_b,
			"B#": savedBindings.key_b_sharp,
			Bb: savedBindings.key_b_flat,
		};
	}

	let variant: React.ReactNode;

	if (isPhoneLandscape) {
		variant = (
			<SettingsBarLandscape
				settings={settings}
				onSettingsChange={onSettingsChange}
			/>
		);
	} else if (isMobile) {
		variant = (
			<SettingsBarMobile
				settings={settings}
				onSettingsChange={onSettingsChange}
			/>
		);
	} else {
		variant = (
			<SettingsBarDesktop
				settings={settings}
				onSettingsChange={onSettingsChange}
			/>
		);
	}

	return (
		<>
			{variant}
			{isAuthenticated && (
				<>
					<button
						type="button"
						onClick={() => handleDialogOpenChange(true)}
						className="fixed bottom-4 right-4 z-40 p-3 rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 transition-colors"
						aria-label="Configure keyboard bindings"
					>
						<Keyboard className="h-5 w-5" />
					</button>
					<KeyboardBindingsDialog
						open={dialogOpen}
						onOpenChange={handleDialogOpenChange}
						bindings={apiResponseToNoteMap()}
						onSave={handleSaveBindings}
					/>
				</>
			)}
		</>
	);
}
