// frontend/src/pages/SheetMusicPage.tsx
import { useState } from "react";
import { Music2 } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Select } from "@/shared/components/ui/select";
import { Card } from "@/shared/components/ui/card";
import { useGenerateMary, useGenerateRandom } from "@/shared/hooks/queries";
import { getErrorMessage } from "@/shared/utils/error.utils";
import { SheetMusicDisplay } from "@/features/sheet-music/components/SheetMusicDisplay";
import { logger } from "@/lib/logger";

const scales = [
	{ label: "C Major", tonic: "C" },
	{ label: "F Major", tonic: "F" },
	{ label: "Bb Major", tonic: "B-" },
	{ label: "Eb Major", tonic: "E-" },
	{ label: "Ab Major", tonic: "A-" },
	{ label: "Db Major", tonic: "D-" },
	{ label: "Gb Major", tonic: "G-" },
	{ label: "G Major", tonic: "G" },
	{ label: "D Major", tonic: "D" },
	{ label: "A Major", tonic: "A" },
	{ label: "E Major", tonic: "E" },
	{ label: "B Major", tonic: "B" },
];

const octaves = [3, 4, 5];

const sixteenthRhythms = [
	{ label: "1111", value: "1111" },
	{ label: "112", value: "112" },
	{ label: "121", value: "121" },
	{ label: "211", value: "211" },
	{ label: "0111", value: "0111" },
];

const eighthRhythms = [
	{ label: "11", value: "11" },
	{ label: "01", value: "01" },
	{ label: "10", value: "10" },
];

export function SheetMusicPage() {
	const [scaleIndex, setScaleIndex] = useState(0);
	const [octave, setOctave] = useState(4);
	const [selectedRhythm, setSelectedRhythm] = useState<string | null>(null);
	const [rhythmType, setRhythmType] = useState<8 | 16 | null>(null);
	const [musicXml, setMusicXml] = useState<string>("");

	const generateMary = useGenerateMary();
	const generateRandom = useGenerateRandom();

	const isGenerating = generateMary.isPending || generateRandom.isPending;
	const error = generateMary.error || generateRandom.error;

	const currentScale = scales[scaleIndex];

	const handleGenerateMary = () => {
		if (!currentScale) return;
		generateMary.mutate(
			{ tonic: currentScale.tonic, octave },
			{
				onSuccess: (xml) => {
					setMusicXml(xml);
					setSelectedRhythm(null);
					setRhythmType(null);
				},
			},
		);
	};

	const handleGenerateRhythm = (rhythm: string, type: 8 | 16) => {
		if (!currentScale) return;
		setSelectedRhythm(rhythm);
		setRhythmType(type);
		generateRandom.mutate(
			{ rhythm, rhythmType: type, tonic: currentScale.tonic },
			{
				onSuccess: (xml) => {
					setMusicXml(xml);
				},
			},
		);
	};

	return (
		<div className="min-h-screen py-8 px-4">
			<div className="container mx-auto max-w-5xl space-y-6">
				<div className="text-center space-y-2">
					<h1 className="text-4xl font-bold">Sheet Music Practice</h1>
					<p className="text-muted-foreground text-lg">
						Generate custom exercises with specific rhythms and scales
					</p>
				</div>

				{/* Sheet Music Display */}
				{musicXml ? (
					<SheetMusicDisplay
						musicXml={musicXml}
						onError={(err) => logger.error(err.message)}
					/>
				) : (
					<Card className="p-12 min-h-[400px] flex items-center justify-center bg-gradient-to-br from-background to-muted/30">
						<div className="text-center space-y-6">
							{error ? (
								<div className="space-y-4">
									<div className="text-destructive font-semibold">
										Error: {getErrorMessage(error)}
									</div>
									<p className="text-sm text-muted-foreground">
										Please try again with different options
									</p>
								</div>
							) : isGenerating ? (
								<div className="space-y-4">
									<div className="animate-spin mx-auto">
										<Music2 className="h-16 w-16 text-primary" />
									</div>
									<p className="text-lg text-muted-foreground">
										Generating music...
									</p>
								</div>
							) : (
								<>
									<Music2 className="h-24 w-24 text-muted-foreground mx-auto" />
									<p className="text-lg text-muted-foreground">
										Select options below and click a button to generate sheet
										music
									</p>
								</>
							)}
						</div>
					</Card>
				)}

				{/* Controls */}
				<div className="space-y-4">
					<Card className="p-6">
						<div className="grid grid-cols-1 md:grid-cols-3 gap-4">
							{/* Scale Selector */}
							<div className="space-y-2">
								<label htmlFor="scale-select" className="text-sm font-medium">
									Choose Scale
								</label>
								<Select
									id="scale-select"
									value={scaleIndex.toString()}
									onChange={(e) => setScaleIndex(Number(e.target.value))}
								>
									{scales.map((s, index) => (
										<option key={index} value={index}>
											{s.label}
										</option>
									))}
								</Select>
							</div>

							{/* Octave Selector */}
							<div className="space-y-2">
								<label htmlFor="octave-select" className="text-sm font-medium">
									Choose Octave
								</label>
								<Select
									id="octave-select"
									value={octave.toString()}
									onChange={(e) => setOctave(Number(e.target.value))}
								>
									{octaves.map((o) => (
										<option key={o} value={o}>
											Octave {o}
										</option>
									))}
								</Select>
							</div>

							{/* Generate Mary Button */}
							<div className="space-y-2">
								<span className="text-sm font-medium block">
									Generate Exercise
								</span>
								<Button
									onClick={handleGenerateMary}
									disabled={isGenerating}
									className="w-full"
								>
									Generate Mary
								</Button>
							</div>
						</div>
					</Card>

					{/* Rhythm Selectors */}
					<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
						{/* 16th Note Rhythms */}
						<Card className="p-6">
							<h3 className="text-lg font-bold mb-4">16th Note Rhythms</h3>
							<div className="space-y-2">
								{sixteenthRhythms.map((rhythm) => (
									<Button
										key={rhythm.value}
										variant={
											selectedRhythm === rhythm.value && rhythmType === 16
												? "default"
												: "outline"
										}
										onClick={() => handleGenerateRhythm(rhythm.value, 16)}
										disabled={isGenerating}
										className="w-full justify-start font-mono"
									>
										{rhythm.label}
									</Button>
								))}
							</div>
						</Card>

						{/* 8th Note Rhythms */}
						<Card className="p-6">
							<h3 className="text-lg font-bold mb-4">8th Note Rhythms</h3>
							<div className="space-y-2">
								{eighthRhythms.map((rhythm) => (
									<Button
										key={rhythm.value}
										variant={
											selectedRhythm === rhythm.value && rhythmType === 8
												? "default"
												: "outline"
										}
										onClick={() => handleGenerateRhythm(rhythm.value, 8)}
										disabled={isGenerating}
										className="w-full justify-start font-mono"
									>
										{rhythm.label}
									</Button>
								))}
							</div>
						</Card>
					</div>
				</div>

				{/* Info Card */}
				<Card className="p-6 bg-primary/5 border-primary/20">
					<div className="space-y-2">
						<h3 className="font-bold text-lg">How It Works</h3>
						<ul className="space-y-1 text-sm text-muted-foreground">
							<li>
								• Select a scale and octave to determine which notes will be
								used
							</li>
							<li>• Choose a rhythm pattern (16th or 8th note combinations)</li>
							<li>
								• The system generates random notes from your selected scale
								arranged in the chosen rhythm
							</li>
							<li>
								• Each generation creates a unique exercise - no memorization
								possible!
							</li>
							<li>• Perfect for sight-reading practice and UIL preparation</li>
						</ul>
					</div>
				</Card>
			</div>
		</div>
	);
}

// frontend/src/app/features/sheet-music/components/sheet-music-page/sheet-music-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	signal,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { LoggerService } from "../../../../core/services/logger.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CardDirective } from "../../../../shared/components/ui/card.directive";
import { SelectComponent } from "../../../../shared/components/ui/select.component";
import {
	describeRhythm,
	RhythmGlyphComponent,
	type RhythmType,
} from "../../../../shared/components/music/rhythm-glyph.component";
import { MusicService } from "../../../../shared/services/music.service";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import { SheetMusicDisplayComponent } from "../sheet-music-display/sheet-music-display.component";

/**
 * The twelve major keys the generator offers.
 *
 * React held music21 spellings here (`tonic: "B-"`) and posted them
 * straight through, which quietly put wire notation in page code. These are
 * UI spellings; `MusicService` converts them at the boundary, so the request
 * body is byte-identical and `frontend/CLAUDE.md`'s "feature code never sees
 * music21 `-` flats" holds literally.
 */
const SCALES = [
	{ label: "C Major", tonic: "C" },
	{ label: "F Major", tonic: "F" },
	{ label: "Bb Major", tonic: "Bb" },
	{ label: "Eb Major", tonic: "Eb" },
	{ label: "Ab Major", tonic: "Ab" },
	{ label: "Db Major", tonic: "Db" },
	{ label: "Gb Major", tonic: "Gb" },
	{ label: "G Major", tonic: "G" },
	{ label: "D Major", tonic: "D" },
	{ label: "A Major", tonic: "A" },
	{ label: "E Major", tonic: "E" },
	{ label: "B Major", tonic: "B" },
];

const OCTAVES = [3, 4, 5];
const SIXTEENTH_RHYTHMS = ["1111", "112", "121", "211", "0111"];
const EIGHTH_RHYTHMS = ["11", "01", "10"];

/**
 * Port of frontend-react/src/pages/SheetMusicPage.tsx.
 *
 * Generation is a user action, not a page load, so there is no
 * `rxResource` here (PLAN.md 5.2 covers fetch-on-load; this is React's
 * `useMutation`). A button press subscribes once, and `HttpClient`
 * completes after one emission -- the one-shot case PLAN.md 5.6 allows a
 * plain `.subscribe()` for.
 */
@Component({
	selector: "app-sheet-music-page",
	imports: [
		ButtonComponent,
		CardDirective,
		NgIcon,
		RhythmGlyphComponent,
		SelectComponent,
		SheetMusicDisplayComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./sheet-music-page.component.html",
})
export class SheetMusicPageComponent {
	private readonly music = inject(MusicService);
	private readonly logger = inject(LoggerService);

	protected readonly scales = SCALES;
	protected readonly octaves = OCTAVES;
	protected readonly sixteenthRhythms = SIXTEENTH_RHYTHMS;
	protected readonly eighthRhythms = EIGHTH_RHYTHMS;

	protected readonly scaleIndex = signal("0");
	protected readonly octave = signal("4");
	protected readonly selectedRhythm = signal<string | null>(null);
	protected readonly rhythmType = signal<RhythmType | null>(null);
	protected readonly musicXml = signal("");
	protected readonly isGenerating = signal(false);
	protected readonly error = signal<unknown>(null);

	protected readonly errorMessage = computed(() => {
		const error = this.error();
		return error === null ? "" : getErrorMessage(error);
	});

	private get currentScale() {
		return this.scales[Number(this.scaleIndex())];
	}

	protected describe(rhythm: string, rhythmType: RhythmType): string {
		return describeRhythm(rhythm, rhythmType);
	}

	protected isSelected(rhythm: string, rhythmType: RhythmType): boolean {
		return this.selectedRhythm() === rhythm && this.rhythmType() === rhythmType;
	}

	protected generateMary(): void {
		const scale = this.currentScale;
		if (!scale) return;

		this.start();
		this.music
			.generateMary({ tonic: scale.tonic, octave: Number(this.octave()) })
			.subscribe({
				next: (xml) => {
					this.musicXml.set(xml);
					this.selectedRhythm.set(null);
					this.rhythmType.set(null);
					this.isGenerating.set(false);
				},
				error: (err: unknown) => this.finishWithError(err),
			});
	}

	protected generateRhythm(rhythm: string, rhythmType: RhythmType): void {
		const scale = this.currentScale;
		if (!scale) return;

		this.selectedRhythm.set(rhythm);
		this.rhythmType.set(rhythmType);

		this.start();
		this.music
			.generateRandom({ rhythm, rhythmType, tonic: scale.tonic })
			.subscribe({
				next: (xml) => {
					this.musicXml.set(xml);
					this.isGenerating.set(false);
				},
				error: (err: unknown) => this.finishWithError(err),
			});
	}

	protected onRenderError(error: Error): void {
		this.logger.error(error.message);
	}

	private start(): void {
		this.isGenerating.set(true);
		this.error.set(null);
	}

	private finishWithError(err: unknown): void {
		this.logger.error("Failed to generate sheet music", err);
		this.error.set(err);
		this.isGenerating.set(false);
	}
}

<div class="min-h-screen py-8 px-4">
	<div class="container mx-auto max-w-5xl space-y-6">
		<div class="text-center space-y-2">
			<h1 class="text-4xl font-bold">Sheet Music Practice</h1>
			<p class="text-muted-foreground text-lg">
				Generate custom exercises with specific rhythms and scales
			</p>
		</div>

		<!-- Sheet Music Display -->
		@if (musicXml()) {
			<app-sheet-music-display
				[musicXml]="musicXml()"
				(renderError)="onRenderError($event)"
			/>
		} @else {
			<div
				appCard
				class="p-12 min-h-[400px] flex items-center justify-center bg-gradient-to-br from-background to-muted/30"
			>
				<div class="text-center space-y-6">
					@if (error()) {
						<div class="space-y-4">
							<div class="text-destructive font-semibold">
								Error: {{ errorMessage() }}
							</div>
							<p class="text-sm text-muted-foreground">
								Please try again with different options
							</p>
						</div>
					} @else if (isGenerating()) {
						<div class="space-y-4">
							<div class="animate-spin mx-auto">
								<ng-icon
									name="lucideMusic2"
									aria-hidden="true"
									class="h-16 w-16 text-primary"
								/>
							</div>
							<p class="text-lg text-muted-foreground">Generating music...</p>
						</div>
					} @else {
						<ng-icon
							name="lucideMusic2"
							aria-hidden="true"
							class="h-24 w-24 text-muted-foreground mx-auto"
						/>
						<p class="text-lg text-muted-foreground">
							Select options below and click a button to generate sheet music
						</p>
					}
				</div>
			</div>
		}

		<!-- Controls -->
		<div class="space-y-4">
			<div appCard class="p-6">
				<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
					<!-- Scale Selector -->
					<div class="space-y-2">
						<label for="scale-select" class="text-sm font-medium">
							Choose Scale
						</label>
						<app-select selectId="scale-select" [(value)]="scaleIndex">
							@for (scale of scales; track scale.label; let i = $index) {
								<option [value]="i">{{ scale.label }}</option>
							}
						</app-select>
					</div>

					<!-- Octave Selector -->
					<div class="space-y-2">
						<label for="octave-select" class="text-sm font-medium">
							Choose Octave
						</label>
						<app-select selectId="octave-select" [(value)]="octave">
							@for (o of octaves; track o) {
								<option [value]="o">Octave {{ o }}</option>
							}
						</app-select>
					</div>

					<!-- Generate Mary Button.
					     `flex flex-col gap-2` rather than React's `space-y-2`:
					     `space-y-*` sets a margin on each child, and
					     `<app-button>` is a `display: contents` host, which has
					     no box to take one. Flex gap lands on the real
					     <button> instead, at the same 8px. -->
					<div class="flex flex-col gap-2">
						<span class="text-sm font-medium block">Generate Exercise</span>
						<app-button
							className="w-full"
							[disabled]="isGenerating()"
							(click)="generateMary()"
						>
							Generate Mary
						</app-button>
					</div>
				</div>
			</div>

			<!-- Rhythm Selectors -->
			<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
				<!-- 16th Note Rhythms -->
				<div appCard class="p-6">
					<h3 class="text-lg font-bold mb-4">16th Note Rhythms</h3>
					<!-- flex gap, not space-y: see the Generate Mary column. -->
					<div class="flex flex-col gap-2">
						@for (rhythm of sixteenthRhythms; track rhythm) {
							<app-button
								[variant]="isSelected(rhythm, 16) ? 'default' : 'outline'"
								[disabled]="isGenerating()"
								[ariaLabel]="describe(rhythm, 16)"
								className="w-full justify-start h-12"
								(click)="generateRhythm(rhythm, 16)"
							>
								<app-rhythm-glyph [rhythm]="rhythm" [rhythmType]="16" />
							</app-button>
						}
					</div>
				</div>

				<!-- 8th Note Rhythms -->
				<div appCard class="p-6">
					<h3 class="text-lg font-bold mb-4">8th Note Rhythms</h3>
					<!-- flex gap, not space-y: see the Generate Mary column. -->
					<div class="flex flex-col gap-2">
						@for (rhythm of eighthRhythms; track rhythm) {
							<app-button
								[variant]="isSelected(rhythm, 8) ? 'default' : 'outline'"
								[disabled]="isGenerating()"
								[ariaLabel]="describe(rhythm, 8)"
								className="w-full justify-start h-12"
								(click)="generateRhythm(rhythm, 8)"
							>
								<app-rhythm-glyph [rhythm]="rhythm" [rhythmType]="8" />
							</app-button>
						}
					</div>
				</div>
			</div>
		</div>

		<!-- Info Card -->
		<div appCard class="p-6 bg-primary/5 border-primary/20">
			<div class="space-y-2">
				<h3 class="font-bold text-lg">How It Works</h3>
				<ul class="space-y-1 text-sm text-muted-foreground">
					<li>
						• Select a scale and octave to determine which notes will be used
					</li>
					<li>• Choose a rhythm pattern (16th or 8th note combinations)</li>
					<li>
						• The system generates random notes from your selected scale
						arranged in the chosen rhythm
					</li>
					<li>
						• Each generation creates a unique exercise - no memorization
						possible!
					</li>
					<li>• Perfect for sight-reading practice and UIL preparation</li>
				</ul>
			</div>
		</div>
	</div>
</div>
