// frontend/src/features/note-game/components/MobileSettingsDrawer.tsx
import { useEffect } from "react";
import { Settings } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Select } from "@/shared/components/ui/select";
import type { GameSettings as GameSettingsType } from "../types";
import { GameMode, SCALES } from "../types";

export interface MobileSettingsDrawerProps {
	settings: GameSettingsType;
	onSettingsChange: (settings: Partial<GameSettingsType>) => void;
	open: boolean;
	onOpenChange: (open: boolean) => void;
}

const TIME_LIMITS = [15, 30, 60, 120] as const;
const NOTE_LIMITS = [10, 25, 50, 100] as const;
const OCTAVES = [1, 2, 3, 4, 5, 6, 7, 8, 9] as const;

/**
 * Full-screen bottom drawer for mobile game settings.
 * Slides up from the bottom with a backdrop overlay.
 * Inspired by Monkeytype's vertical settings panel.
 */
export function MobileSettingsDrawer({
	settings,
	onSettingsChange,
	open,
	onOpenChange,
}: MobileSettingsDrawerProps) {
	const isTimeMode = settings.gameMode === GameMode.Time;
	const limits = isTimeMode ? TIME_LIMITS : NOTE_LIMITS;
	const activeLimit = isTimeMode ? settings.timeLimit : settings.noteLimit;

	useEffect(() => {
		if (open) {
			document.body.style.overflow = "hidden";
		} else {
			document.body.style.overflow = "";
		}
		return () => {
			document.body.style.overflow = "";
		};
	}, [open]);

	return (
		<>
			{/* Backdrop */}
			<button
				type="button"
				aria-label="Close settings"
				className={`fixed inset-0 z-40 bg-black/60 transition-opacity duration-300 ${
					open ? "opacity-100" : "opacity-0 pointer-events-none"
				}`}
				onClick={() => onOpenChange(false)}
			/>

			{/* Drawer */}
			<div
				className={`fixed inset-x-0 bottom-0 z-50 bg-card border-t-2 border-border rounded-t-2xl transition-transform duration-300 ease-out ${
					open ? "translate-y-0" : "translate-y-full"
				}`}
			>
				{/* Drag handle */}
				<div className="flex justify-center pt-3 pb-2">
					<div className="w-10 h-1 rounded-full bg-muted-foreground/30" />
				</div>

				<div className="px-5 pb-6 space-y-5 max-h-[80vh] overflow-y-auto">
					{/* Header */}
					<div className="flex items-center justify-between">
						<div className="flex items-center gap-2 text-lg font-semibold">
							<Settings className="h-5 w-5 text-muted-foreground" />
							Game Settings
						</div>
						<Button
							size="sm"
							variant="ghost"
							onClick={() => onOpenChange(false)}
						>
							Done
						</Button>
					</div>

					{/* Game Mode */}
					<div className="space-y-2">
						<span className="text-sm font-medium text-muted-foreground">
							Mode
						</span>
						<div className="grid grid-cols-2 gap-2">
							<Button
								variant={isTimeMode ? "default" : "outline"}
								className="h-11"
								onClick={() => onSettingsChange({ gameMode: GameMode.Time })}
							>
								time
							</Button>
							<Button
								variant={!isTimeMode ? "default" : "outline"}
								className="h-11"
								onClick={() => onSettingsChange({ gameMode: GameMode.Notes })}
							>
								notes
							</Button>
						</div>
					</div>

					{/* Limit */}
					<div className="space-y-2">
						<span className="text-sm font-medium text-muted-foreground">
							{isTimeMode ? "Time Limit" : "Note Limit"}
						</span>
						<div className="grid grid-cols-4 gap-2">
							{limits.map((limit) => (
								<Button
									key={limit}
									variant={activeLimit === limit ? "default" : "outline"}
									className="h-11"
									onClick={() =>
										onSettingsChange(
											isTimeMode ? { timeLimit: limit } : { noteLimit: limit },
										)
									}
								>
									{limit}
								</Button>
							))}
						</div>
					</div>

					{/* Scale */}
					<div className="space-y-2">
						<label
							htmlFor="mobile-scale-select"
							className="text-sm font-medium text-muted-foreground"
						>
							Scale
						</label>
						<Select
							id="mobile-scale-select"
							className="h-11"
							value={settings.scale}
							onChange={(e) => onSettingsChange({ scale: e.target.value })}
						>
							{SCALES.map((scale) => (
								<option key={scale} value={scale}>
									{scale}
								</option>
							))}
						</Select>
					</div>

					{/* Octave */}
					<div className="space-y-2">
						<label
							htmlFor="mobile-octave-select"
							className="text-sm font-medium text-muted-foreground"
						>
							Octave
						</label>
						<Select
							id="mobile-octave-select"
							className="h-11"
							value={settings.octave.toString()}
							onChange={(e) =>
								onSettingsChange({ octave: Number(e.target.value) })
							}
						>
							{OCTAVES.map((octave) => (
								<option key={octave} value={octave}>
									Octave {octave}
								</option>
							))}
						</Select>
					</div>
				</div>
			</div>
		</>
	);
}

// frontend/src/app/features/note-game/components/mobile-settings-drawer/mobile-settings-drawer.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	input,
	model,
	output,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { SelectComponent } from "../../../../shared/components/ui/select.component";
import {
	GameMode,
	NOTE_LIMITS,
	TIME_LIMITS,
} from "@features/identification-game";
import { type GameSettings, SCALES } from "../../models/note-game.models";
import { NoteRangeSettingComponent } from "../note-range-setting/note-range-setting.component";

/**
 * Full-screen bottom drawer for mobile game settings. Port of
 * frontend-react/src/features/note-game/components/MobileSettingsDrawer.tsx.
 *
 * Always in the DOM and slid off-screen when closed, exactly as React had it
 * -- that is what makes the transition animate, and it is also why
 * `e2e/support/app.ts` filters its scale picker on visibility rather than
 * assuming only one exists.
 */
@Component({
	selector: "app-mobile-settings-drawer",
	imports: [
		ButtonComponent,
		NgIcon,
		NoteRangeSettingComponent,
		SelectComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: contents;
		}
	`,
	template: `
		<!-- Backdrop -->
		<button
			type="button"
			aria-label="Close settings"
			[class]="backdropClasses()"
			(click)="open.set(false)"
		></button>

		<!-- Drawer -->
		<div [class]="drawerClasses()">
			<!-- Drag handle -->
			<div class="flex justify-center pt-3 pb-2">
				<div class="w-10 h-1 rounded-full bg-muted-foreground/30"></div>
			</div>

			<div class="px-5 pb-6 space-y-5 max-h-[80vh] overflow-y-auto">
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-2 text-lg font-semibold">
						<ng-icon
							name="lucideSettings"
							size="1.25rem"
							class="h-5 w-5 text-muted-foreground"
							aria-hidden="true"
						/>
						Game Settings
					</div>
					<app-button size="sm" variant="ghost" (click)="open.set(false)">
						Done
					</app-button>
				</div>

				<div class="space-y-2">
					<span class="text-sm font-medium text-muted-foreground">Mode</span>
					<div class="grid grid-cols-2 gap-2">
						<app-button
							[variant]="isTimeMode() ? 'default' : 'outline'"
							className="h-11"
							(click)="settingsChange.emit({ gameMode: modes.Time })"
						>
							time
						</app-button>
						<app-button
							[variant]="!isTimeMode() ? 'default' : 'outline'"
							className="h-11"
							(click)="settingsChange.emit({ gameMode: modes.Notes })"
						>
							notes
						</app-button>
					</div>
				</div>

				<div class="space-y-2">
					<span class="text-sm font-medium text-muted-foreground">
						{{ isTimeMode() ? "Time Limit" : "Note Limit" }}
					</span>
					<div class="grid grid-cols-4 gap-2">
						@for (limit of limits(); track limit) {
							<app-button
								[variant]="activeLimit() === limit ? 'default' : 'outline'"
								className="h-11"
								(click)="selectLimit(limit)"
							>
								{{ limit }}
							</app-button>
						}
					</div>
				</div>

				<div class="space-y-2">
					<label
						for="mobile-scale-select"
						class="text-sm font-medium text-muted-foreground"
					>
						Scale
					</label>
					<app-select
						selectId="mobile-scale-select"
						className="h-11"
						[value]="settings().scale"
						(valueChange)="settingsChange.emit({ scale: $event })"
					>
						@for (scale of scales; track scale) {
							<option [value]="scale">{{ scale }}</option>
						}
					</app-select>
				</div>

				<div class="space-y-2">
					<span class="text-sm font-medium text-muted-foreground">
						Note Range
					</span>
					<app-note-range-setting
						[clef]="settings().clef"
						[lowNote]="settings().lowNote"
						[highNote]="settings().highNote"
						(settingsChange)="settingsChange.emit($event)"
					/>
				</div>
			</div>
		</div>
	`,
})
export class MobileSettingsDrawerComponent {
	readonly settings = input.required<GameSettings>();
	readonly open = model(false);

	readonly settingsChange = output<Partial<GameSettings>>();

	protected readonly modes = GameMode;
	protected readonly scales = SCALES;

	protected readonly isTimeMode = computed(
		() => this.settings().gameMode === GameMode.Time,
	);
	protected readonly limits = computed<readonly number[]>(() =>
		this.isTimeMode() ? TIME_LIMITS : NOTE_LIMITS,
	);
	protected readonly activeLimit = computed(() =>
		this.isTimeMode() ? this.settings().timeLimit : this.settings().noteLimit,
	);

	protected readonly backdropClasses = computed(
		() =>
			`fixed inset-0 z-40 bg-black/60 transition-opacity duration-300 ${
				this.open() ? "opacity-100" : "opacity-0 pointer-events-none"
			}`,
	);

	protected readonly drawerClasses = computed(
		() =>
			`fixed inset-x-0 bottom-0 z-50 bg-card border-t-2 border-border rounded-t-2xl transition-transform duration-300 ease-out ${
				this.open() ? "translate-y-0" : "translate-y-full"
			}`,
	);

	constructor() {
		// React locked body scroll in a useEffect with an unconditional
		// cleanup; the effect's onCleanup is the same contract, and it also
		// covers the drawer being destroyed while open.
		effect((onCleanup) => {
			const open = this.open();
			document.body.style.overflow = open ? "hidden" : "";
			onCleanup(() => {
				document.body.style.overflow = "";
			});
		});
	}

	protected selectLimit(limit: number): void {
		this.settingsChange.emit(
			this.isTimeMode() ? { timeLimit: limit } : { noteLimit: limit },
		);
	}
}
