// new-frontend/src/features/dashboard/components/DashboardSkeleton.tsx
/**
 * Dashboard Skeleton Loader
 *
 * Displays skeleton loaders that match the actual dashboard layout
 * while data is being fetched from the API.
 */

import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';

export function DashboardSkeleton() {
  return (
    <div className="min-h-screen py-8 px-4">
      <div className="container mx-auto max-w-6xl space-y-6">
        {/* User Profile Card Skeleton */}
        <Card className="shadow-lg">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-6 items-center md:items-start">
              {/* Avatar Skeleton */}
              <Skeleton className="w-24 h-24 rounded-full flex-shrink-0" />

              {/* User Info Skeleton */}
              <div className="flex-1 text-center md:text-left space-y-2">
                <Skeleton className="h-9 w-48 mx-auto md:mx-0" />
                <div className="flex flex-wrap gap-2 justify-center md:justify-start items-center">
                  <Skeleton className="h-6 w-20" />
                  <Skeleton className="h-6 w-32" />
                </div>
              </div>

              {/* Quick Stats Skeleton */}
              <div className="grid grid-cols-2 gap-4">
                <div className="text-center">
                  <Skeleton className="h-9 w-16 mx-auto mb-1" />
                  <Skeleton className="h-4 w-24" />
                </div>
                <div className="text-center">
                  <Skeleton className="h-9 w-16 mx-auto mb-1" />
                  <Skeleton className="h-4 w-24" />
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Performance Chart Skeleton */}
        <Card className="shadow-lg">
          <CardHeader>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
              <Skeleton className="h-8 w-48" />
              <Skeleton className="h-10 w-32" />
            </div>
          </CardHeader>
          <CardContent>
            <Skeleton className="w-full h-[400px]" />
          </CardContent>
        </Card>

        {/* Stats Grid Skeleton */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((i) => (
            <Card key={i} className="hover:shadow-lg transition-shadow">
              <CardContent className="p-6">
                <div className="flex items-start justify-between">
                  <div className="space-y-2">
                    <Skeleton className="h-4 w-24" />
                    <Skeleton className="h-9 w-16" />
                  </div>
                  <Skeleton className="h-10 w-10 rounded-lg" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/features/dashboard/components/dashboard-skeleton/dashboard-skeleton.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";

import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { SkeletonDirective } from "../../../../shared/components/ui/skeleton.directive";

/**
 * Port of
 * frontend-react/src/features/dashboard/components/DashboardSkeleton.tsx --
 * placeholder blocks laid out like the real dashboard so the page does not
 * jump when the data lands.
 *
 * It covers the profile card, the chart card and the four stat cards, and
 * deliberately not the activity card: the heatmap has its own inline
 * loading state because it is fetched separately (see the dashboard page).
 */
@Component({
	selector: "app-dashboard-skeleton",
	imports: [SkeletonDirective, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: "block" },
	templateUrl: "./dashboard-skeleton.component.html",
})
export class DashboardSkeletonComponent {
	protected readonly statCards = [1, 2, 3, 4];
}

<div class="min-h-screen px-4 py-8">
	<div class="container mx-auto max-w-6xl space-y-6">
		<!-- Profile card -->
		<div appCard className="shadow-lg">
			<div appCardContent className="p-6">
				<div
					class="flex flex-col items-center gap-6 md:flex-row md:items-start"
				>
					<div appSkeleton class="h-24 w-24 flex-shrink-0 rounded-full"></div>

					<div class="flex-1 space-y-2 text-center md:text-left">
						<div appSkeleton class="mx-auto h-9 w-48 md:mx-0"></div>
						<div
							class="flex flex-wrap items-center justify-center gap-2 md:justify-start"
						>
							<div appSkeleton class="h-6 w-20"></div>
							<div appSkeleton class="h-6 w-32"></div>
						</div>
					</div>

					<div class="grid grid-cols-2 gap-4">
						<div class="text-center">
							<div appSkeleton class="mx-auto mb-1 h-9 w-16"></div>
							<div appSkeleton class="h-4 w-24"></div>
						</div>
						<div class="text-center">
							<div appSkeleton class="mx-auto mb-1 h-9 w-16"></div>
							<div appSkeleton class="h-4 w-24"></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Performance chart -->
		<div appCard className="shadow-lg">
			<div appCardHeader>
				<div
					class="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center"
				>
					<div appSkeleton class="h-8 w-48"></div>
					<div appSkeleton class="h-10 w-32"></div>
				</div>
			</div>
			<div appCardContent>
				<div appSkeleton class="h-[400px] w-full"></div>
			</div>
		</div>

		<!-- Stats grid -->
		<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
			@for (card of statCards; track card) {
				<div appCard className="hover:shadow-lg transition-shadow">
					<div appCardContent className="p-6">
						<div class="flex items-start justify-between">
							<div class="space-y-2">
								<div appSkeleton class="h-4 w-24"></div>
								<div appSkeleton class="h-9 w-16"></div>
							</div>
							<div appSkeleton class="h-10 w-10 rounded-lg"></div>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</div>
