// frontend/src/features/classes/components/JoinClassCard.tsx
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Check } from "lucide-react";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import { Skeleton } from "@/shared/components/ui/skeleton";
import { Button } from "@/shared/components/ui/button";
import { FormField } from "@/shared/components/forms/FormField";
import { FormInput } from "@/shared/components/forms/FormInput";
import { useJoinClass, useStudentClasses } from "@/shared/hooks/queries";
import { getErrorMessage } from "@/shared/utils/error.utils";
import type { StudentClass } from "@/features/classes/types";

interface JoinClassFormData {
	joinCode: string;
}

export function JoinClassCard() {
	const {
		register,
		handleSubmit,
		reset,
		formState: { errors },
	} = useForm<JoinClassFormData>({ defaultValues: { joinCode: "" } });
	const joinClass = useJoinClass();
	const {
		data: classes = [],
		isLoading: isClassesLoading,
		isError: isClassesError,
	} = useStudentClasses();
	const [joined, setJoined] = useState<StudentClass | null>(null);

	function onSubmit(data: JoinClassFormData) {
		setJoined(null);
		joinClass.mutate(data.joinCode.trim(), {
			onSuccess: (studentClass) => {
				setJoined(studentClass);
				reset();
			},
		});
	}

	const joinError = errors.joinCode?.message
		? errors.joinCode.message
		: joinClass.isError
			? getErrorMessage(joinClass.error)
			: undefined;

	return (
		<Card>
			<CardHeader>
				<CardTitle className="font-display text-2xl">Join a class</CardTitle>
			</CardHeader>
			<CardContent className="space-y-4">
				<form
					onSubmit={handleSubmit(onSubmit)}
					className="flex items-start gap-2"
					noValidate
				>
					<FormField
						label="Class code"
						htmlFor="join-code"
						error={joinError}
						className="flex-1"
					>
						<FormInput
							id="join-code"
							placeholder="7NZJN3"
							maxLength={6}
							autoComplete="off"
							registration={register("joinCode", {
								required: "Enter a class code",
							})}
							error={joinError}
						/>
					</FormField>
					<Button
						type="submit"
						variant="brass"
						loading={joinClass.isPending}
						className="mt-6"
					>
						Join
					</Button>
				</form>

				{joined && (
					<div className="flex items-center gap-2 rounded-md border-2 border-correct/40 bg-correct/10 p-3 text-sm">
						<Check className="h-4 w-4 shrink-0 text-correct" />
						<span>
							Joined <span className="font-medium">{joined.name}</span> —{" "}
							{joined.teacherName}
						</span>
					</div>
				)}

				<div>
					<h3 className="mb-2 text-sm font-medium text-muted-foreground">
						Your classes
					</h3>
					{isClassesLoading ? (
						<div className="space-y-2">
							<Skeleton className="h-9 w-full" />
							<Skeleton className="h-9 w-full" />
						</div>
					) : isClassesError ? (
						<p className="text-sm text-destructive">
							Failed to load your classes.
						</p>
					) : classes.length > 0 ? (
						<ul className="space-y-1">
							{classes.map((studentClass) => (
								<li
									key={studentClass.id}
									className="flex items-center justify-between rounded-lg p-2 transition-colors hover:bg-accent/50"
								>
									<span className="truncate text-sm font-medium">
										{studentClass.name}
									</span>
									<span className="shrink-0 text-xs text-muted-foreground">
										{studentClass.teacherName}
									</span>
								</li>
							))}
						</ul>
					) : (
						<p className="text-sm text-muted-foreground">
							You haven&apos;t joined any classes yet.
						</p>
					)}
				</div>
			</CardContent>
		</Card>
	);
}

// frontend/src/app/features/classes/components/join-class-card/join-class-card.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	inject,
	output,
	signal,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import {
	form,
	FormField,
	maxLength,
	validateStandardSchema,
} from "@angular/forms/signals";
import { NgIcon } from "@ng-icons/core";
import { z } from "zod";

import { FormFieldComponent } from "../../../../shared/components/forms/form-field.component";
import { FormInputDirective } from "../../../../shared/components/forms/form-input.directive";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { SkeletonDirective } from "../../../../shared/components/ui/skeleton.directive";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type { StudentClass } from "../../models/classes.models";
import { ClassesService } from "../../services/classes.service";

export const joinClassSchema = z.object({
	joinCode: z.string().min(1, "Enter a class code"),
});

export type JoinClassFormData = z.infer<typeof joinClassSchema>;

/**
 * Port of frontend-react/src/features/classes/components/JoinClassCard.tsx:
 * the student's join-by-code form, plus the list of classes they are in.
 *
 * **The join error is shown inline, never as a toast.** React said so with
 * `meta: { suppressErrorToast: true }` on the mutation, and a React test
 * pins it: a wrong code is a 404 whose body the student needs to read next
 * to the field they just typed in, not a corner notification. The Angular
 * shape is the same one every other mutation here uses -- the error arm --
 * it just writes into a signal instead of calling `showError`.
 *
 * Contracts the parity suite selects on: the label "Class code" and the
 * button "Join" (`exact: true`, which is why the card's title is "Join a
 * class" and the button is the bare word).
 */
@Component({
	selector: "app-join-class-card",
	imports: [
		ButtonComponent,
		FormField,
		FormFieldComponent,
		FormInputDirective,
		NgIcon,
		SkeletonDirective,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./join-class-card.component.html",
})
export class JoinClassCardComponent {
	/** Raised after a successful join, for anything else on the page. */
	readonly joined = output<StudentClass>();

	private readonly classesService = inject(ClassesService);

	private readonly formModel = signal<JoinClassFormData>({ joinCode: "" });

	readonly joinForm = form(this.formModel, (path) => {
		validateStandardSchema(path, joinClassSchema);
		// React wrote `maxLength={6}` on the input. Signal Forms owns the
		// validation attributes on a `[formField]` element (NG8022 refuses a
		// hand-written one), so the cap is declared here and the directive
		// renders the attribute.
		maxLength(path.joinCode, 6);
	});

	readonly classes = rxResource({
		stream: () => this.classesService.getStudentClasses(),
		defaultValue: [] as StudentClass[],
	});

	readonly pending = signal(false);
	readonly serverError = signal<string | null>(null);
	readonly justJoined = signal<StudentClass | null>(null);

	// The template binds both `[error]="serverError()"` and
	// `[field]="joinForm.joinCode"` on the field. `app-form-field` gives
	// `error` precedence and falls through to the field's own message when it
	// is null, which is React's
	// `errors.joinCode?.message ?? getErrorMessage(join.error)` ladder.

	submit(event: Event): void {
		event.preventDefault();
		if (this.pending()) return;

		this.joinForm().markAsTouched();
		if (this.joinForm().invalid()) return;

		this.justJoined.set(null);
		this.serverError.set(null);
		this.pending.set(true);

		this.classesService.joinClass(this.formModel().joinCode.trim()).subscribe({
			next: (studentClass) => {
				this.pending.set(false);
				this.justJoined.set(studentClass);
				this.joinForm().reset({ joinCode: "" });
				// React invalidated the student class list here; a resource
				// refetches instead (D6).
				this.classes.reload();
				this.joined.emit(studentClass);
			},
			error: (err: unknown) => {
				this.pending.set(false);
				this.serverError.set(getErrorMessage(err));
			},
		});
	}
}

<div appCard>
	<div appCardHeader>
		<h3 appCardTitle className="font-display text-2xl">Join a class</h3>
	</div>
	<div appCardContent className="space-y-4">
		<form (submit)="submit($event)" class="flex items-start gap-2">
			<app-form-field
				label="Class code"
				htmlFor="join-code"
				className="flex-1 space-y-1.5"
				[error]="serverError()"
				[field]="joinForm.joinCode"
			>
				<input
					appFormInput
					id="join-code"
					autocomplete="off"
					placeholder="7NZJN3"
					[formField]="joinForm.joinCode"
				/>
			</app-form-field>
			<app-button
				type="submit"
				variant="brass"
				className="mt-6"
				[loading]="pending()"
			>
				Join
			</app-button>
		</form>

		@if (justJoined(); as studentClass) {
			<div
				class="flex items-center gap-2 rounded-md border-2 border-correct/40 bg-correct/10 p-3 text-sm"
			>
				<ng-icon
					name="lucideCheck"
					size="1rem"
					aria-hidden="true"
					class="shrink-0 text-correct"
				/>
				<span>
					Joined <span class="font-medium">{{ studentClass.name }}</span> —
					{{ studentClass.teacherName }}
				</span>
			</div>
		}

		<div>
			<h3 class="mb-2 text-sm font-medium text-muted-foreground">
				Your classes
			</h3>
			@if (classes.status() === "loading") {
				<div class="space-y-2">
					<div appSkeleton class="h-9 w-full"></div>
					<div appSkeleton class="h-9 w-full"></div>
				</div>
			} @else if (classes.error()) {
				<p class="text-sm text-destructive">Failed to load your classes.</p>
			} @else if (classes.value().length > 0) {
				<ul class="space-y-1">
					@for (studentClass of classes.value(); track studentClass.id) {
						<li
							class="flex items-center justify-between rounded-lg p-2 transition-colors hover:bg-accent/50"
						>
							<span class="truncate text-sm font-medium">{{
								studentClass.name
							}}</span>
							<span class="shrink-0 text-xs text-muted-foreground">{{
								studentClass.teacherName
							}}</span>
						</li>
					}
				</ul>
			} @else {
				<p class="text-sm text-muted-foreground">
					You haven't joined any classes yet.
				</p>
			}
		</div>
	</div>
</div>
