// frontend/src/features/classes/components/RosterList.tsx
import { useState } from "react";
import { Loader2, UserMinus } from "lucide-react";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { ConfirmDialog } from "@/shared/components/ui/confirm-dialog";
import { QueryState } from "@/shared/components/QueryState";
import { useClassRoster, useRemoveStudent } from "@/shared/hooks/queries";
import { formatDate } from "@/shared/utils/date.utils";
import type { RosterEntry } from "@/features/classes/types";

interface RosterListProps {
	classId: number;
}

function RosterRow({
	entry,
	classId,
}: {
	entry: RosterEntry;
	classId: number;
}) {
	const [confirmOpen, setConfirmOpen] = useState(false);
	const removeStudent = useRemoveStudent();

	function handleRemove() {
		removeStudent.mutate(
			{ classId, studentId: entry.studentId },
			{ onSuccess: () => setConfirmOpen(false) },
		);
	}

	return (
		<div className="flex items-center gap-3 p-3 rounded-lg transition-colors hover:bg-accent/50">
			<div className="flex-1 min-w-0">
				<span className="text-sm font-medium truncate block">
					{entry.firstName} {entry.lastName}
				</span>
				<p className="text-xs text-muted-foreground truncate">
					Joined {formatDate(entry.joinedAt)}
				</p>
			</div>
			<Button
				variant="ghost"
				size="icon"
				aria-label={`Remove ${entry.firstName} ${entry.lastName}`}
				className="text-muted-foreground hover:text-destructive"
				onClick={() => setConfirmOpen(true)}
			>
				<UserMinus className="h-4 w-4" />
			</Button>

			<ConfirmDialog
				open={confirmOpen}
				onOpenChange={setConfirmOpen}
				title="Remove student?"
				description={
					<>
						Remove{" "}
						<span className="font-medium text-foreground">
							{entry.firstName} {entry.lastName}
						</span>{" "}
						from this class? They can rejoin later with the class code.
					</>
				}
				confirmLabel="Remove"
				pending={removeStudent.isPending}
				onConfirm={handleRemove}
			/>
		</div>
	);
}

export function RosterList({ classId }: RosterListProps) {
	const {
		data: roster = [],
		isLoading,
		isError,
		error,
	} = useClassRoster(classId);

	return (
		<Card>
			<CardHeader className="flex-row items-center justify-between space-y-0">
				<CardTitle className="font-display text-xl">Roster</CardTitle>
				<span className="tabular-nums text-sm text-muted-foreground">
					{roster.length}
				</span>
			</CardHeader>
			<CardContent className="p-2">
				<QueryState
					isLoading={isLoading}
					isError={isError}
					error={error}
					loading={
						<div className="flex items-center justify-center h-24">
							<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
						</div>
					}
					isEmpty={roster.length === 0}
					empty={
						<div className="flex flex-col items-center justify-center h-24 gap-1 text-center">
							<p className="text-sm font-medium text-muted-foreground">
								No students yet — share the join code to get started.
							</p>
						</div>
					}
				>
					{roster.map((entry) => (
						<RosterRow key={entry.studentId} entry={entry} classId={classId} />
					))}
				</QueryState>
			</CardContent>
		</Card>
	);
}

// frontend/src/app/features/classes/components/roster-list/roster-list.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	signal,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import { NgIcon } from "@ng-icons/core";

import { AppErrorComponent } from "../../../../core/components/app-error/app-error.component";
import { ConfirmDialogComponent } from "../../../../core/components/confirm-dialog/confirm-dialog.component";
import { NotificationService } from "../../../../core/services/notification.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { formatDate } from "../../../../shared/utils/date.utils";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type { RosterEntry } from "../../models/classes.models";
import { ClassesService } from "../../services/classes.service";

/**
 * Port of frontend-react/src/features/classes/components/RosterList.tsx --
 * who is enrolled, and the remove-student action.
 *
 * React gave each row its own `RosterRow` component purely so the row could
 * own a `useState` for its confirm dialog. Signals do not need a component
 * to hold state, so the list keeps one `confirming` signal naming the row
 * being confirmed and renders **one** dialog. Same behaviour, one component
 * instead of two, and only one dialog in the DOM.
 *
 * Removing a student refetches the roster and tells the parent, because the
 * class's `student_count` on the header changed too -- the two
 * `invalidateQueries` calls React's `useRemoveStudent` made.
 */
@Component({
	selector: "app-roster-list",
	imports: [
		AppErrorComponent,
		ButtonComponent,
		ConfirmDialogComponent,
		NgIcon,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	templateUrl: "./roster-list.component.html",
})
export class RosterListComponent {
	readonly classId = input.required<number>();

	/** Raised when the roll changed, so the class header can refetch. */
	readonly rosterChanged = output<void>();

	private readonly classesService = inject(ClassesService);
	private readonly notifications = inject(NotificationService);

	readonly roster = rxResource({
		params: () => this.classId(),
		stream: ({ params }) => this.classesService.getClassRoster(params),
		defaultValue: [] as RosterEntry[],
	});

	readonly confirming = signal<RosterEntry | null>(null);
	readonly pending = signal(false);

	readonly confirmDescription = computed(() => {
		const entry = this.confirming();
		if (!entry) return "";
		return `Remove ${entry.firstName} ${entry.lastName} from this class? They can rejoin later with the class code.`;
	});

	joinedLabel(entry: RosterEntry): string {
		return `Joined ${formatDate(entry.joinedAt)}`;
	}

	fullName(entry: RosterEntry): string {
		return `${entry.firstName} ${entry.lastName}`;
	}

	confirmOpenChange(open: boolean): void {
		if (!open) this.confirming.set(null);
	}

	remove(): void {
		const entry = this.confirming();
		if (!entry || this.pending()) return;
		this.pending.set(true);

		this.classesService
			.removeStudent(this.classId(), entry.studentId)
			.subscribe({
				next: () => {
					this.pending.set(false);
					this.confirming.set(null);
					this.roster.reload();
					this.rosterChanged.emit();
				},
				error: (err: unknown) => {
					this.pending.set(false);
					this.notifications.showError(
						getErrorMessage(err),
						"Failed to remove student",
					);
				},
			});
	}
}

<div appCard>
	<div
		appCardHeader
		className="flex-row items-center justify-between space-y-0"
	>
		<h3 appCardTitle className="font-display text-xl">Roster</h3>
		<span class="tabular-nums text-sm text-muted-foreground">{{
			roster.value().length
		}}</span>
	</div>
	<div appCardContent className="p-2">
		@if (roster.status() === "loading") {
			<div class="flex items-center justify-center h-24">
				<ng-icon
					name="lucideLoader2"
					size="1.5rem"
					aria-hidden="true"
					class="animate-spin text-muted-foreground"
				/>
			</div>
		} @else if (roster.error()) {
			<app-error [error]="roster.error()" />
		} @else if (roster.value().length === 0) {
			<div
				class="flex flex-col items-center justify-center h-24 gap-1 text-center"
			>
				<p class="text-sm font-medium text-muted-foreground">
					No students yet — share the join code to get started.
				</p>
			</div>
		} @else {
			@for (entry of roster.value(); track entry.studentId) {
				<div
					class="flex items-center gap-3 p-3 rounded-lg transition-colors hover:bg-accent/50"
				>
					<div class="flex-1 min-w-0">
						<span class="text-sm font-medium truncate block">{{
							fullName(entry)
						}}</span>
						<p class="text-xs text-muted-foreground truncate">
							{{ joinedLabel(entry) }}
						</p>
					</div>
					<app-button
						variant="ghost"
						size="icon"
						[ariaLabel]="'Remove ' + fullName(entry)"
						className="text-muted-foreground hover:text-destructive"
						(click)="confirming.set(entry)"
					>
						<ng-icon name="lucideUserMinus" size="1rem" aria-hidden="true" />
					</app-button>
				</div>
			}
		}
	</div>

	<!--
		One dialog for the whole list, named by `confirming()`. React needed a
		dialog per row only because each row's `useState` lived in its own
		component.
	-->
	<app-confirm-dialog
		[open]="confirming() !== null"
		(openChange)="confirmOpenChange($event)"
		title="Remove student?"
		[description]="confirmDescription()"
		confirmLabel="Remove"
		[pending]="pending()"
		(confirm)="remove()"
	/>
</div>
