// frontend/src/features/identification-game/components/ScoreBar.tsx
import { useBreakpoint } from "@/shared/hooks";
import type { NoteAnswer } from "../types";
import { GameMode } from "../types";

export interface ScoreBarProps {
	answers: NoteAnswer[];
	timeRemaining?: number;
	noteLimit?: number;
	gameMode: GameMode;
	formatTime?: (seconds: number) => string;
}

interface ScoreData {
	correctAnswers: number;
	totalAnswers: number;
	accuracy: number;
	timerDisplay: string;
}

function useScoreData({
	answers,
	timeRemaining,
	noteLimit,
	gameMode,
	formatTime,
}: ScoreBarProps): ScoreData {
	const correctAnswers = answers.filter((a) => a.correct).length;
	const accuracy =
		answers.length > 0
			? Math.round((correctAnswers / answers.length) * 100)
			: 0;

	let timerDisplay = "";
	if (gameMode === GameMode.Time && timeRemaining !== undefined) {
		timerDisplay = formatTime ? formatTime(timeRemaining) : `${timeRemaining}s`;
	} else if (gameMode === GameMode.Notes && noteLimit !== undefined) {
		timerDisplay = `${answers.length}/${noteLimit}`;
	}

	return {
		correctAnswers,
		totalAnswers: answers.length,
		accuracy,
		timerDisplay,
	};
}

function ScoreBarHorizontal(props: ScoreBarProps) {
	const { correctAnswers, totalAnswers, accuracy, timerDisplay } =
		useScoreData(props);

	return (
		<div className="flex justify-between items-center bg-card border-2 border-border rounded-lg px-2 sm:px-4 py-1.5 sm:py-2 min-h-[2.5rem] sm:min-h-[3rem]">
			<div className="text-sm sm:text-lg font-medium">
				Score: {correctAnswers}/{totalAnswers}
			</div>
			<div className="text-sm sm:text-lg font-bold tabular-nums">
				{timerDisplay}
			</div>
			<div className="text-sm sm:text-lg font-medium">
				Accuracy: {accuracy}%
			</div>
		</div>
	);
}

function ScoreBarSidebar(props: ScoreBarProps) {
	const { correctAnswers, totalAnswers, accuracy, timerDisplay } =
		useScoreData(props);

	return (
		<div className="flex flex-col items-center justify-center gap-1.5 bg-card border-2 border-border rounded-lg px-2 py-2 w-full h-full">
			<div className="text-xs font-medium text-center">
				{correctAnswers}/{totalAnswers}
			</div>
			<div className="text-sm font-bold text-center text-primary tabular-nums">
				{timerDisplay}
			</div>
			<div className="text-xs font-medium text-center">{accuracy}%</div>
		</div>
	);
}

/**
 * Compact score bar that replaces SettingsBar during active gameplay.
 * Conditionally renders the appropriate layout variant based on viewport.
 */
export function ScoreBar(props: ScoreBarProps) {
	const { isPhoneLandscape } = useBreakpoint();

	if (isPhoneLandscape) {
		return <ScoreBarSidebar {...props} />;
	}

	return <ScoreBarHorizontal {...props} />;
}

// frontend/src/app/features/identification-game/components/score-bar/score-bar.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
} from "@angular/core";

import { BreakpointService } from "@shared/services/breakpoint.service";

import { GameMode, type NoteAnswer } from "../../models/game-state.models";

/**
 * The compact live score, which replaces the title row during play.
 *
 * Port of
 * frontend-react/src/features/identification-game/components/ScoreBar.tsx.
 * The two layouts are React's: a phone held sideways gets a narrow sidebar
 * so the staff keeps the width, everything else gets the horizontal bar.
 * React rendered one or the other from `useBreakpoint`; this reads the same
 * three media queries through `BreakpointService`.
 */
@Component({
	selector: "app-score-bar",
	imports: [],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	template: `
		@if (breakpoints.isPhoneLandscape()) {
			<div
				class="flex h-full w-full flex-col items-center justify-center gap-1.5 rounded-lg border-2 border-border bg-card px-2 py-2"
			>
				<div class="text-center text-xs font-medium">
					{{ correct() }}/{{ total() }}
				</div>
				<div class="text-center text-sm font-bold tabular-nums text-primary">
					{{ timerDisplay() }}
				</div>
				<div class="text-center text-xs font-medium">{{ accuracy() }}%</div>
			</div>
		} @else {
			<div
				class="flex min-h-[2.5rem] items-center justify-between rounded-lg border-2 border-border bg-card px-2 py-1.5 sm:min-h-[3rem] sm:px-4 sm:py-2"
			>
				<div class="text-sm font-medium sm:text-lg">
					Score: {{ correct() }}/{{ total() }}
				</div>
				<div class="text-sm font-bold tabular-nums sm:text-lg">
					{{ timerDisplay() }}
				</div>
				<div class="text-sm font-medium sm:text-lg">
					Accuracy: {{ accuracy() }}%
				</div>
			</div>
		}
	`,
})
export class ScoreBarComponent {
	protected readonly breakpoints = inject(BreakpointService);

	readonly answers = input.required<NoteAnswer[]>();
	readonly gameMode = input.required<GameMode>();
	readonly timeRemaining = input<number | undefined>(undefined);
	readonly noteLimit = input<number | undefined>(undefined);
	/** Seconds to "M:SS". Supplied by the page's timer. */
	readonly formatTime = input<((seconds: number) => string) | undefined>(
		undefined,
	);

	protected readonly correct = computed(
		() => this.answers().filter((a) => a.correct).length,
	);
	protected readonly total = computed(() => this.answers().length);
	protected readonly accuracy = computed(() =>
		this.total() > 0 ? Math.round((this.correct() / this.total()) * 100) : 0,
	);

	protected readonly timerDisplay = computed(() => {
		const remaining = this.timeRemaining();
		const limit = this.noteLimit();

		if (this.gameMode() === GameMode.Time && remaining !== undefined) {
			return this.formatTime()?.(remaining) ?? `${remaining}s`;
		}
		if (this.gameMode() === GameMode.Notes && limit !== undefined) {
			return `${this.total()}/${limit}`;
		}
		return "";
	});
}
