// frontend-react/src/pages/AssignmentsPage.tsx
import { JoinClassCard } from "@/features/classes/components/JoinClassCard";
import { StudentAssignmentsList } from "@/features/classes/components/StudentAssignmentsList";

/**
 * Student-facing page: join a class by code and see assigned practice
 * with progress against each assignment's (advisory) target.
 */
export function AssignmentsPage() {
	return (
		<div className="min-h-screen px-4 py-8">
			<div className="container mx-auto max-w-3xl space-y-6">
				<h1 className="font-display text-3xl font-bold">Assignments</h1>
				<JoinClassCard />
				<StudentAssignmentsList />
			</div>
		</div>
	);
}

// frontend/src/app/features/classes/components/assignments-page/assignments-page.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";

import { JoinClassCardComponent } from "../join-class-card/join-class-card.component";
import { StudentAssignmentsListComponent } from "../student-assignments-list/student-assignments-list.component";

/**
 * `/assignments` -- the student-facing page: join a class by code and see
 * assigned practice with progress against each assignment's (advisory)
 * target. Port of frontend-react/src/pages/AssignmentsPage.tsx.
 *
 * The heading is **"Assignments"** and the card below it is "My
 * Assignments"; the parity suite asks for the first with `exact: true`
 * precisely so the two do not collide.
 */
@Component({
	selector: "app-assignments-page",
	imports: [JoinClassCardComponent, StudentAssignmentsListComponent],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./assignments-page.component.html",
})
export class AssignmentsPageComponent {}

<div class="min-h-screen px-4 py-8">
	<div class="container mx-auto max-w-3xl space-y-6">
		<h1 class="font-display text-3xl font-bold">Assignments</h1>
		<app-join-class-card />
		<app-student-assignments-list />
	</div>
</div>
