// frontend-react/src/features/note-game/components/StaffRangePicker.tsx
import { useCallback, useRef } from "react";
import { ChevronUp, ChevronDown } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import type { RangeClef } from "@/services/api/types";
import { CLEF_UNICODE } from "@/features/identification-game";
import {
	noteToIndex,
	indexToNote,
	staffSteps,
	ledgerSteps,
	BOTTOM_LINE_INDEX,
	RANGE_BOUNDS,
} from "../rangeUtils";

export interface StaffRangePickerProps {
	clef: RangeClef;
	/** Low endpoint, natural note (e.g. "C4") */
	low: string;
	/** High endpoint, natural note (e.g. "C6") */
	high: string;
	onChange: (low: string, high: string) => void;
}

// SVG geometry: one staff-position step is half the line spacing.
const LINE_SPACING = 14;
const STEP = LINE_SPACING / 2;
const STAFF_TOP = 56; // y of the top staff line
const STAFF_LEFT = 44;
const STAFF_WIDTH = 168;
const HEIGHT = 168;
const WIDTH = STAFF_LEFT + STAFF_WIDTH + 8;
const LOW_X = STAFF_LEFT + 46;
const HIGH_X = STAFF_LEFT + 122;

const CLEF_GLYPHS: Record<RangeClef, { glyph: string; dy: number }> = {
	// Codepoints shared with ClefGlyph; dy positions at this scale.
	treble: { glyph: CLEF_UNICODE.treble, dy: 3.1 * LINE_SPACING },
	bass: { glyph: CLEF_UNICODE.bass, dy: 1.05 * LINE_SPACING },
};

/** y coordinate of a staff-position step (0 = bottom line). */
function stepToY(steps: number): number {
	return STAFF_TOP + 4 * LINE_SPACING - steps * STEP;
}

function WholeNote({
	index,
	clef,
	x,
	onPointerDown,
}: {
	index: number;
	clef: RangeClef;
	x: number;
	onPointerDown: (e: React.PointerEvent) => void;
}) {
	const y = stepToY(staffSteps(index, clef));
	return (
		<g
			onPointerDown={onPointerDown}
			className="cursor-grab touch-none"
			role="presentation"
		>
			{ledgerSteps(index, clef).map((s) => (
				<line
					key={s}
					x1={x - 13}
					x2={x + 13}
					y1={stepToY(s)}
					y2={stepToY(s)}
					stroke="currentColor"
					strokeWidth={1.5}
				/>
			))}
			{/* invisible hit area so grabbing is easy */}
			<rect x={x - 16} y={y - 16} width={32} height={32} fill="transparent" />
			<ellipse
				cx={x}
				cy={y}
				rx={8.5}
				ry={5.5}
				fill="currentColor"
				transform={`rotate(-14 ${x} ${y})`}
			/>
			<ellipse
				cx={x}
				cy={y}
				rx={4.6}
				ry={3}
				className="fill-card"
				transform={`rotate(24 ${x} ${y})`}
			/>
		</g>
	);
}

/**
 * Staff-based note range selector.
 *
 * Renders a mini staff with the low and high range endpoints as whole
 * notes. Endpoints move by one staff position via the chevron buttons
 * or by dragging the note heads. Endpoints are natural notes.
 */
export function StaffRangePicker({
	clef,
	low,
	high,
	onChange,
}: StaffRangePickerProps) {
	const svgRef = useRef<SVGSVGElement>(null);
	const dragRef = useRef<"low" | "high" | null>(null);

	const lowIdx = noteToIndex(low);
	const highIdx = noteToIndex(high);
	const bounds = RANGE_BOUNDS[clef];

	const moveEndpoint = useCallback(
		(which: "low" | "high", targetIdx: number) => {
			if (which === "low") {
				const next = Math.max(bounds.min, Math.min(targetIdx, highIdx - 1));
				if (next !== lowIdx) onChange(indexToNote(next), high);
			} else {
				const next = Math.min(bounds.max, Math.max(targetIdx, lowIdx + 1));
				if (next !== highIdx) onChange(low, indexToNote(next));
			}
		},
		[bounds, lowIdx, highIdx, low, high, onChange],
	);

	const yToIndex = useCallback(
		(clientY: number): number => {
			const svg = svgRef.current;
			if (!svg) return 0;
			const rect = svg.getBoundingClientRect();
			const y = ((clientY - rect.top) / rect.height) * HEIGHT;
			const steps = Math.round((STAFF_TOP + 4 * LINE_SPACING - y) / STEP);
			return steps + BOTTOM_LINE_INDEX[clef];
		},
		[clef],
	);

	const handlePointerDown = useCallback(
		(which: "low" | "high") => (e: React.PointerEvent) => {
			dragRef.current = which;
			(e.target as Element).setPointerCapture?.(e.pointerId);
		},
		[],
	);

	const handlePointerMove = useCallback(
		(e: React.PointerEvent) => {
			if (!dragRef.current) return;
			moveEndpoint(dragRef.current, yToIndex(e.clientY));
		},
		[moveEndpoint, yToIndex],
	);

	const handlePointerUp = useCallback(() => {
		dragRef.current = null;
	}, []);

	const stepper = (which: "low" | "high", idx: number) => (
		<div className="flex flex-col gap-1">
			<Button
				type="button"
				size="sm"
				variant="outline"
				className="h-7 w-7 p-0"
				aria-label={`${which === "low" ? "Lowest" : "Highest"} note up`}
				onClick={() => moveEndpoint(which, idx + 1)}
			>
				<ChevronUp className="h-4 w-4" />
			</Button>
			<Button
				type="button"
				size="sm"
				variant="outline"
				className="h-7 w-7 p-0"
				aria-label={`${which === "low" ? "Lowest" : "Highest"} note down`}
				onClick={() => moveEndpoint(which, idx - 1)}
			>
				<ChevronDown className="h-4 w-4" />
			</Button>
		</div>
	);

	const clefGlyph = CLEF_GLYPHS[clef];

	return (
		<div className="flex items-center gap-2">
			{stepper("low", lowIdx)}
			<svg
				ref={svgRef}
				viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
				className="w-56 text-foreground select-none"
				onPointerMove={handlePointerMove}
				onPointerUp={handlePointerUp}
				onPointerLeave={handlePointerUp}
				aria-label={`Note range from ${low} to ${high}`}
				role="img"
			>
				{[0, 1, 2, 3, 4].map((line) => (
					<line
						key={line}
						x1={STAFF_LEFT - 30}
						x2={STAFF_LEFT + STAFF_WIDTH}
						y1={STAFF_TOP + line * LINE_SPACING}
						y2={STAFF_TOP + line * LINE_SPACING}
						stroke="currentColor"
						strokeWidth={1.2}
					/>
				))}
				<text
					x={STAFF_LEFT - 28}
					y={STAFF_TOP + clefGlyph.dy}
					fontSize={LINE_SPACING * 3.4}
					fill="currentColor"
				>
					{clefGlyph.glyph}
				</text>
				<WholeNote
					index={lowIdx}
					clef={clef}
					x={LOW_X}
					onPointerDown={handlePointerDown("low")}
				/>
				<WholeNote
					index={highIdx}
					clef={clef}
					x={HIGH_X}
					onPointerDown={handlePointerDown("high")}
				/>
			</svg>
			{stepper("high", highIdx)}
		</div>
	);
}

// frontend/src/app/features/note-game/components/staff-range-picker/staff-range-picker.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	ElementRef,
	input,
	output,
	viewChild,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import type { RangeClef } from "../../../../shared/models/music.models";
import { CLEF_UNICODE } from "@features/identification-game";
import {
	BOTTOM_LINE_INDEX,
	indexToNote,
	ledgerSteps,
	noteToIndex,
	RANGE_BOUNDS,
	staffSteps,
} from "../../models/range.utils";

/**
 * Staff-based note range selector. Port of
 * frontend-react/src/features/note-game/components/StaffRangePicker.tsx.
 *
 * A mini staff with the two range endpoints drawn as whole notes. Each moves
 * one staff position at a time, by the chevron buttons or by dragging the
 * note head. Endpoints are natural notes, so one index step is one line or
 * space -- all of that arithmetic is in `models/range.utils.ts`.
 *
 * Every geometry constant below is React's, unchanged: the picker is
 * photographed by the note-game baselines.
 *
 * `RangeClef` is treble/bass only, and deliberately so
 * (`frontend/CLAUDE.md`).
 */

// SVG geometry: one staff-position step is half the line spacing.
const LINE_SPACING = 14;
const STEP = LINE_SPACING / 2;
const STAFF_TOP = 56; // y of the top staff line
const STAFF_LEFT = 44;
const STAFF_WIDTH = 168;
const HEIGHT = 168;
const WIDTH = STAFF_LEFT + STAFF_WIDTH + 8;
const LOW_X = STAFF_LEFT + 46;
const HIGH_X = STAFF_LEFT + 122;

/** Codepoints shared with the clef glyph; `dy` positions them at this scale. */
const CLEF_GLYPHS: Record<RangeClef, { glyph: string; dy: number }> = {
	treble: { glyph: CLEF_UNICODE.treble, dy: 3.1 * LINE_SPACING },
	bass: { glyph: CLEF_UNICODE.bass, dy: 1.05 * LINE_SPACING },
};

/** y coordinate of a staff-position step (0 = bottom line). */
function stepToY(steps: number): number {
	return STAFF_TOP + 4 * LINE_SPACING - steps * STEP;
}

type Endpoint = "low" | "high";

interface WholeNoteGeometry {
	x: number;
	y: number;
	ledgers: { y: number; x1: number; x2: number }[];
	hitX: number;
	hitY: number;
	lowRotate: string;
	highRotate: string;
}

@Component({
	selector: "app-staff-range-picker",
	imports: [ButtonComponent, NgIcon],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	template: `
		<div class="flex items-center gap-2">
			<div class="flex flex-col gap-1">
				<app-button
					size="sm"
					variant="outline"
					className="h-7 w-7 p-0"
					ariaLabel="Lowest note up"
					(click)="move('low', lowIndex() + 1)"
				>
					<ng-icon name="lucideChevronUp" size="1rem" aria-hidden="true" />
				</app-button>
				<app-button
					size="sm"
					variant="outline"
					className="h-7 w-7 p-0"
					ariaLabel="Lowest note down"
					(click)="move('low', lowIndex() - 1)"
				>
					<ng-icon name="lucideChevronDown" size="1rem" aria-hidden="true" />
				</app-button>
			</div>

			<svg
				#staff
				[attr.viewBox]="viewBox"
				class="w-56 text-foreground select-none"
				role="img"
				[attr.aria-label]="'Note range from ' + low() + ' to ' + high()"
				(pointermove)="onPointerMove($event)"
				(pointerup)="onPointerUp()"
				(pointerleave)="onPointerUp()"
			>
				@for (line of staffLines; track line) {
					<line
						[attr.x1]="staffLeft - 30"
						[attr.x2]="staffLeft + staffWidth"
						[attr.y1]="staffTop + line * lineSpacing"
						[attr.y2]="staffTop + line * lineSpacing"
						stroke="currentColor"
						stroke-width="1.2"
					/>
				}
				<text
					[attr.x]="staffLeft - 28"
					[attr.y]="staffTop + clefGlyph().dy"
					[attr.font-size]="lineSpacing * 3.4"
					fill="currentColor"
				>
					{{ clefGlyph().glyph }}
				</text>

				@for (endpoint of endpoints; track endpoint) {
					@let note = geometry()[endpoint];
					<g
						class="cursor-grab touch-none"
						role="presentation"
						(pointerdown)="onPointerDown(endpoint, $event)"
					>
						@for (ledger of note.ledgers; track ledger.y) {
							<line
								[attr.x1]="ledger.x1"
								[attr.x2]="ledger.x2"
								[attr.y1]="ledger.y"
								[attr.y2]="ledger.y"
								stroke="currentColor"
								stroke-width="1.5"
							/>
						}
						<!-- invisible hit area so grabbing is easy -->
						<rect
							[attr.x]="note.hitX"
							[attr.y]="note.hitY"
							width="32"
							height="32"
							fill="transparent"
						/>
						<ellipse
							[attr.cx]="note.x"
							[attr.cy]="note.y"
							rx="8.5"
							ry="5.5"
							fill="currentColor"
							[attr.transform]="note.lowRotate"
						/>
						<ellipse
							[attr.cx]="note.x"
							[attr.cy]="note.y"
							rx="4.6"
							ry="3"
							class="fill-card"
							[attr.transform]="note.highRotate"
						/>
					</g>
				}
			</svg>

			<div class="flex flex-col gap-1">
				<app-button
					size="sm"
					variant="outline"
					className="h-7 w-7 p-0"
					ariaLabel="Highest note up"
					(click)="move('high', highIndex() + 1)"
				>
					<ng-icon name="lucideChevronUp" size="1rem" aria-hidden="true" />
				</app-button>
				<app-button
					size="sm"
					variant="outline"
					className="h-7 w-7 p-0"
					ariaLabel="Highest note down"
					(click)="move('high', highIndex() - 1)"
				>
					<ng-icon name="lucideChevronDown" size="1rem" aria-hidden="true" />
				</app-button>
			</div>
		</div>
	`,
})
export class StaffRangePickerComponent {
	readonly clef = input.required<RangeClef>();
	/** Low endpoint, natural note (e.g. "C4"). */
	readonly low = input.required<string>();
	/** High endpoint, natural note (e.g. "C6"). */
	readonly high = input.required<string>();

	readonly rangeChange = output<{ low: string; high: string }>();

	private readonly svg = viewChild<ElementRef<SVGSVGElement>>("staff");

	private dragging: Endpoint | null = null;

	protected readonly viewBox = `0 0 ${WIDTH} ${HEIGHT}`;
	protected readonly staffLines = [0, 1, 2, 3, 4];
	protected readonly staffLeft = STAFF_LEFT;
	protected readonly staffWidth = STAFF_WIDTH;
	protected readonly staffTop = STAFF_TOP;
	protected readonly lineSpacing = LINE_SPACING;
	protected readonly endpoints: Endpoint[] = ["low", "high"];

	protected readonly lowIndex = computed(() => noteToIndex(this.low()));
	protected readonly highIndex = computed(() => noteToIndex(this.high()));
	protected readonly clefGlyph = computed(() => CLEF_GLYPHS[this.clef()]);

	protected readonly geometry = computed<Record<Endpoint, WholeNoteGeometry>>(
		() => ({
			low: this.wholeNote(this.lowIndex(), LOW_X),
			high: this.wholeNote(this.highIndex(), HIGH_X),
		}),
	);

	/**
	 * Moves one endpoint, keeping it inside the clef's bounds and at least
	 * one step clear of the other. React's clamping, unchanged.
	 */
	protected move(which: Endpoint, targetIndex: number): void {
		const bounds = RANGE_BOUNDS[this.clef()];
		const lowIndex = this.lowIndex();
		const highIndex = this.highIndex();

		if (which === "low") {
			const next = Math.max(bounds.min, Math.min(targetIndex, highIndex - 1));
			if (next !== lowIndex) {
				this.rangeChange.emit({ low: indexToNote(next), high: this.high() });
			}
			return;
		}

		const next = Math.min(bounds.max, Math.max(targetIndex, lowIndex + 1));
		if (next !== highIndex) {
			this.rangeChange.emit({ low: this.low(), high: indexToNote(next) });
		}
	}

	protected onPointerDown(which: Endpoint, event: PointerEvent): void {
		this.dragging = which;
		(event.target as Element).setPointerCapture?.(event.pointerId);
	}

	protected onPointerMove(event: PointerEvent): void {
		if (!this.dragging) return;
		this.move(this.dragging, this.yToIndex(event.clientY));
	}

	protected onPointerUp(): void {
		this.dragging = null;
	}

	private yToIndex(clientY: number): number {
		const svg = this.svg()?.nativeElement;
		if (!svg) return 0;
		const rect = svg.getBoundingClientRect();
		const y = ((clientY - rect.top) / rect.height) * HEIGHT;
		const steps = Math.round((STAFF_TOP + 4 * LINE_SPACING - y) / STEP);
		return steps + BOTTOM_LINE_INDEX[this.clef()];
	}

	private wholeNote(index: number, x: number): WholeNoteGeometry {
		const clef = this.clef();
		const y = stepToY(staffSteps(index, clef));
		return {
			x,
			y,
			ledgers: ledgerSteps(index, clef).map((step) => ({
				y: stepToY(step),
				x1: x - 13,
				x2: x + 13,
			})),
			hitX: x - 16,
			hitY: y - 16,
			lowRotate: `rotate(-14 ${x} ${y})`,
			highRotate: `rotate(24 ${x} ${y})`,
		};
	}
}
