// frontend/src/app/features/classes/components/assignment-results-grid/assignment-results-grid.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	inject,
	input,
	signal,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import { NgIcon } from "@ng-icons/core";

import { AppErrorComponent } from "../../../../core/components/app-error/app-error.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { cn } from "../../../../shared/utils/cn";
import type { Assignment, AssignmentResult } from "../../models/classes.models";
import { ClassesService } from "../../services/classes.service";
import { AttemptDrilldownComponent } from "../attempt-drilldown/attempt-drilldown.component";
import { ClassInsightTilesComponent } from "../class-insight-tiles/class-insight-tiles.component";

/** The five-column track shared by the header row and every result row. */
const COLS = "grid grid-cols-[1.6fr_repeat(4,1fr)] gap-2 items-center";

/**
 * Port of
 * frontend-react/src/features/classes/components/AssignmentResultsGrid.tsx:
 * one row per enrolled student, expandable into that student's attempt
 * history.
 *
 * Two behaviours the React tests pin and this keeps:
 *
 * - A zero-attempt student is a plain `div` reading "Not started", **not** a
 *   button -- there is nothing to expand, so it must not be reachable by
 *   keyboard as though there were.
 * - The drill-down is not rendered, and therefore not fetched, until its row
 *   is expanded.
 */
@Component({
	selector: "app-assignment-results-grid",
	imports: [
		AppErrorComponent,
		AttemptDrilldownComponent,
		ClassInsightTilesComponent,
		NgIcon,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./assignment-results-grid.component.html",
})
export class AssignmentResultsGridComponent {
	readonly assignment = input.required<Assignment>();

	private readonly classesService = inject(ClassesService);

	readonly results = rxResource({
		params: () => this.assignment().id,
		stream: ({ params }) => this.classesService.getAssignmentResults(params),
		defaultValue: [] as AssignmentResult[],
	});

	readonly expandedStudentId = signal<number | null>(null);

	protected readonly cols = COLS;
	protected readonly headerClasses = cn(
		COLS,
		"px-3 pb-1 text-[10px] uppercase tracking-wide text-muted-foreground",
	);
	protected readonly notStartedClasses = cn(
		COLS,
		"px-3 py-2 rounded-lg text-muted-foreground",
	);
	protected readonly rowButtonClasses = cn(
		COLS,
		"w-full px-3 py-2 rounded-lg transition-colors hover:bg-accent/50 text-left",
	);

	/** A student with no attempt at all -- either counter can say so. */
	notStarted(row: AssignmentResult): boolean {
		return row.attemptCount === 0 || row.lastAttemptDate === "";
	}

	fullName(row: AssignmentResult): string {
		return `${row.firstName} ${row.lastName}`;
	}

	/** Clamped so a bad number from the server cannot overflow the meter. */
	accuracyWidth(row: AssignmentResult): string {
		return `${Math.min(100, Math.max(0, row.bestAccuracy))}%`;
	}

	toggle(row: AssignmentResult): void {
		this.expandedStudentId.update((current) =>
			current === row.studentId ? null : row.studentId,
		);
	}
}

<div appCard>
	<div appCardHeader className="space-y-0">
		<h3 appCardTitle className="font-display text-xl">Results</h3>
		<p class="text-sm text-muted-foreground truncate">
			{{ assignment().title }}
		</p>
	</div>
	<div appCardContent className="p-4 pt-0">
		<app-class-insight-tiles
			[results]="results.value()"
			[isLoading]="results.isLoading()"
		/>

		@if (results.isLoading()) {
			<div class="flex items-center justify-center h-24">
				<ng-icon
					name="lucideLoader2"
					size="1.5rem"
					aria-hidden="true"
					class="animate-spin text-muted-foreground"
				/>
			</div>
		} @else if (results.error()) {
			<app-error [error]="results.error()" />
		} @else if (results.value().length === 0) {
			<div
				class="flex flex-col items-center justify-center h-24 gap-1 text-center"
			>
				<p class="text-sm font-medium text-muted-foreground">
					No students enrolled yet.
				</p>
			</div>
		} @else {
			<div class="overflow-x-auto">
				<div class="min-w-[32rem] space-y-1">
					<div [class]="headerClasses">
						<span>Student</span>
						<span class="text-right">Attempts</span>
						<span class="text-right">Best / Most</span>
						<span class="text-right">Accuracy</span>
						<span class="text-right">Last attempt</span>
					</div>

					@for (row of results.value(); track row.studentId) {
						@if (notStarted(row)) {
							<div [class]="notStartedClasses">
								<span class="text-sm font-medium truncate">{{
									fullName(row)
								}}</span>
								<span class="col-span-4 text-xs">Not started</span>
							</div>
						} @else {
							<div class="rounded-lg overflow-hidden">
								<button
									type="button"
									[class]="rowButtonClasses"
									[attr.aria-expanded]="expandedStudentId() === row.studentId"
									(click)="toggle(row)"
								>
									<span
										class="flex items-center gap-1.5 text-sm font-medium truncate"
									>
										<ng-icon
											name="lucideChevronDown"
											size="0.875rem"
											aria-hidden="true"
											[class]="
												expandedStudentId() === row.studentId
													? 'shrink-0 text-muted-foreground transition-transform rotate-180'
													: 'shrink-0 text-muted-foreground transition-transform'
											"
										/>
										{{ fullName(row) }}
									</span>
									<span class="tabular-nums text-sm text-right">{{
										row.attemptCount
									}}</span>
									<span class="tabular-nums text-sm text-right">
										{{ row.bestCorrect
										}}<span class="text-muted-foreground">
											/ {{ row.mostQuestions }}</span
										>
									</span>
									<div class="flex flex-col items-end gap-1">
										<span class="tabular-nums text-sm font-semibold text-brass"
											>{{ row.bestAccuracy }}%</span
										>
										<span
											class="h-1 w-full max-w-16 rounded-full bg-brass/20 overflow-hidden"
											aria-hidden="true"
										>
											<span
												class="block h-full rounded-full bg-brass"
												[style.width]="accuracyWidth(row)"
											></span>
										</span>
									</div>
									<span
										class="tabular-nums text-xs text-muted-foreground text-right"
										>{{ row.lastAttemptDate }}</span
									>
								</button>
								@if (expandedStudentId() === row.studentId) {
									<app-attempt-drilldown
										[assignmentId]="assignment().id"
										[studentId]="row.studentId"
									/>
								}
							</div>
						}
					}
				</div>
			</div>
		}
	</div>
</div>

// frontend/src/features/classes/components/AssignmentResultsGrid.tsx
import { useState } from "react";
import { ChevronDown, Loader2 } from "lucide-react";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import { QueryState } from "@/shared/components/QueryState";
import { cn } from "@/lib/utils";
import { useAssignmentResults } from "@/shared/hooks/queries";
import { AttemptDrilldown } from "./AttemptDrilldown";
import { ClassInsightTiles } from "./ClassInsightTiles";
import type { Assignment, AssignmentResult } from "@/features/classes/types";

interface AssignmentResultsGridProps {
	assignment: Assignment;
}

const COLS = "grid grid-cols-[1.6fr_repeat(4,1fr)] gap-2 items-center";

interface ResultRowProps {
	row: AssignmentResult;
	assignmentId: number;
	isExpanded: boolean;
	onToggle: () => void;
}

function ResultRow({
	row,
	assignmentId,
	isExpanded,
	onToggle,
}: ResultRowProps) {
	const notStarted = row.attemptCount === 0 || row.lastAttemptDate === "";

	if (notStarted) {
		return (
			<div className={cn(COLS, "px-3 py-2 rounded-lg text-muted-foreground")}>
				<span className="text-sm font-medium truncate">
					{row.firstName} {row.lastName}
				</span>
				<span className="col-span-4 text-xs">Not started</span>
			</div>
		);
	}

	return (
		<div className="rounded-lg overflow-hidden">
			<button
				type="button"
				onClick={onToggle}
				aria-expanded={isExpanded}
				className={cn(
					COLS,
					"w-full px-3 py-2 rounded-lg transition-colors hover:bg-accent/50 text-left",
				)}
			>
				<span className="flex items-center gap-1.5 text-sm font-medium truncate">
					<ChevronDown
						className={cn(
							"h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform",
							isExpanded && "rotate-180",
						)}
						aria-hidden="true"
					/>
					{row.firstName} {row.lastName}
				</span>
				<span className="tabular-nums text-sm text-right">
					{row.attemptCount}
				</span>
				<span className="tabular-nums text-sm text-right">
					{row.bestCorrect}
					<span className="text-muted-foreground"> / {row.mostQuestions}</span>
				</span>
				<div className="flex flex-col items-end gap-1">
					<span className="tabular-nums text-sm font-semibold text-brass">
						{row.bestAccuracy}%
					</span>
					<span
						className="h-1 w-full max-w-16 rounded-full bg-brass/20 overflow-hidden"
						aria-hidden="true"
					>
						<span
							className="block h-full rounded-full bg-brass"
							style={{
								width: `${Math.min(100, Math.max(0, row.bestAccuracy))}%`,
							}}
						/>
					</span>
				</div>
				<span className="tabular-nums text-xs text-muted-foreground text-right">
					{row.lastAttemptDate}
				</span>
			</button>
			{isExpanded && (
				<AttemptDrilldown
					assignmentId={assignmentId}
					studentId={row.studentId}
				/>
			)}
		</div>
	);
}

export function AssignmentResultsGrid({
	assignment,
}: AssignmentResultsGridProps) {
	const {
		data: results = [],
		isLoading,
		isError,
		error,
	} = useAssignmentResults(assignment.id);
	const [expandedStudentId, setExpandedStudentId] = useState<number | null>(
		null,
	);

	return (
		<Card>
			<CardHeader className="space-y-0">
				<CardTitle className="font-display text-xl">Results</CardTitle>
				<p className="text-sm text-muted-foreground truncate">
					{assignment.title}
				</p>
			</CardHeader>
			<CardContent className="p-4 pt-0">
				<ClassInsightTiles results={results} isLoading={isLoading} />
				<QueryState
					isLoading={isLoading}
					isError={isError}
					error={error}
					loading={
						<div className="flex items-center justify-center h-24">
							<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
						</div>
					}
					isEmpty={results.length === 0}
					empty={
						<div className="flex flex-col items-center justify-center h-24 gap-1 text-center">
							<p className="text-sm font-medium text-muted-foreground">
								No students enrolled yet.
							</p>
						</div>
					}
				>
					<div className="overflow-x-auto">
						<div className="min-w-[32rem] space-y-1">
							<div
								className={cn(
									COLS,
									"px-3 pb-1 text-[10px] uppercase tracking-wide text-muted-foreground",
								)}
							>
								<span>Student</span>
								<span className="text-right">Attempts</span>
								<span className="text-right">Best / Most</span>
								<span className="text-right">Accuracy</span>
								<span className="text-right">Last attempt</span>
							</div>
							{results.map((row) => (
								<ResultRow
									key={row.studentId}
									row={row}
									assignmentId={assignment.id}
									isExpanded={expandedStudentId === row.studentId}
									onToggle={() =>
										setExpandedStudentId((prev) =>
											prev === row.studentId ? null : row.studentId,
										)
									}
								/>
							))}
						</div>
					</div>
				</QueryState>
			</CardContent>
		</Card>
	);
}
