// frontend/src/app/features/classes/components/create-assignment-dialog/create-assignment-dialog.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	model,
	output,
	signal,
} from "@angular/core";
import {
	form,
	FormField,
	validateStandardSchema,
} from "@angular/forms/signals";
import { z } from "zod";

import { NotificationService } from "../../../../core/services/notification.service";
import { FormFieldComponent } from "../../../../shared/components/forms/form-field.component";
import { FormInputDirective } from "../../../../shared/components/forms/form-input.directive";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { DIALOG_DIRECTIVES } from "../../../../shared/components/ui/dialog.component";
import { SelectComponent } from "../../../../shared/components/ui/select.component";
import type { GameType } from "../../../../shared/models/game.types";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type {
	Assignment,
	CreateAssignmentRequest,
} from "../../models/classes.models";
import {
	defaultAssignmentConfig,
	GAME_TYPE_LABELS,
	GAME_TYPE_OPTIONS,
} from "../../models/game-definitions";
import { ClassesService } from "../../services/classes.service";

/**
 * The title is the only thing React validated in TypeScript; its `min`/`max`
 * on the two target inputs were native constraints, which Signal Forms
 * refuses to let a template write on a `[formField]` element (NG8022). Both
 * targets are optional strings on the way in, so the same bounds are stated
 * here as refinements and now come with a message instead of a browser
 * tooltip.
 */
const optionalNumber = (label: string, min: number, max?: number) =>
	z.string().refine(
		(raw) => {
			if (!raw.trim()) return true;
			const value = Number(raw);
			return (
				Number.isFinite(value) &&
				value >= min &&
				(max === undefined || value <= max)
			);
		},
		max === undefined
			? `${label} must be ${min} or more`
			: `${label} must be between ${min} and ${max}`,
	);

export const createAssignmentSchema = z.object({
	title: z.string().trim().min(1, "Title is required"),
	dueAt: z.string(),
	targetQuestions: optionalNumber("Target questions", 1),
	targetAccuracy: optionalNumber("Target accuracy", 1, 100),
});

export type CreateAssignmentFormData = z.infer<typeof createAssignmentSchema>;

/**
 * Port of
 * frontend-react/src/features/classes/components/CreateAssignmentDialog.tsx.
 *
 * **Scope boundary.** React's dialog embedded each game's own settings UI
 * (`SettingsControls`, `GameModeLimitControls`, `StaffRangePicker`) so a
 * teacher could tune the frozen config before creating the assignment.
 * Those controls are the game engine's (Phase 5) and the note game's
 * (Phase 6); this slice ports everything around them and freezes the
 * chosen game's **defaults** as the config, which is what React froze when
 * a teacher touched nothing. `defaultAssignmentConfig()` carries those
 * defaults and names the phase that has to replace it.
 *
 * `gameType` and `config` stay plain signals rather than form fields: the
 * config is an opaque JSONB blob, not something zod has an opinion about,
 * and switching games snapshots the new game's defaults rather than
 * migrating the old ones -- the same reset React did in `changeGameType`.
 */
@Component({
	selector: "app-create-assignment-dialog",
	imports: [
		ButtonComponent,
		FormField,
		FormFieldComponent,
		FormInputDirective,
		SelectComponent,
		...DIALOG_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./create-assignment-dialog.component.html",
})
export class CreateAssignmentDialogComponent {
	readonly classId = input.required<number>();
	readonly open = model.required<boolean>();

	readonly created = output<Assignment>();

	private readonly classesService = inject(ClassesService);
	private readonly notifications = inject(NotificationService);

	readonly gameTypeOptions = GAME_TYPE_OPTIONS;

	private readonly formModel = signal<CreateAssignmentFormData>({
		title: "",
		dueAt: "",
		targetQuestions: "",
		targetAccuracy: "",
	});

	readonly assignmentForm = form(this.formModel, (path) => {
		validateStandardSchema(path, createAssignmentSchema);
	});

	readonly gameType = signal<GameType>("note");
	readonly config = signal<Record<string, unknown>>(
		defaultAssignmentConfig("note"),
	);
	readonly pending = signal(false);

	readonly gameLabel = computed(() => GAME_TYPE_LABELS[this.gameType()]);

	changeGameType(value: string): void {
		const next = value as GameType;
		this.gameType.set(next);
		// Switching games snapshots that game's own defaults as the config.
		this.config.set(defaultAssignmentConfig(next));
	}

	close(): void {
		this.assignmentForm().reset({
			title: "",
			dueAt: "",
			targetQuestions: "",
			targetAccuracy: "",
		});
		this.gameType.set("note");
		this.config.set(defaultAssignmentConfig("note"));
		this.pending.set(false);
		this.open.set(false);
	}

	submit(event: Event): void {
		event.preventDefault();
		if (this.pending()) return;

		this.assignmentForm().markAsTouched();
		if (this.assignmentForm().invalid()) return;

		const values = this.formModel();
		const request: CreateAssignmentRequest = {
			title: values.title.trim(),
			game_type: this.gameType(),
			config: this.config(),
			due_at: values.dueAt ? new Date(values.dueAt).toISOString() : null,
			target_questions: values.targetQuestions.trim()
				? Number(values.targetQuestions)
				: null,
			target_accuracy: values.targetAccuracy.trim()
				? Number(values.targetAccuracy)
				: null,
		};

		this.pending.set(true);

		this.classesService.createAssignment(this.classId(), request).subscribe({
			next: (assignment) => {
				this.created.emit(assignment);
				this.close();
			},
			error: (err: unknown) => {
				this.pending.set(false);
				this.notifications.showError(
					getErrorMessage(err),
					"Failed to create assignment",
				);
			},
		});
	}
}

<app-dialog [(open)]="open">
	<div appDialogContent class="max-h-[90vh] overflow-y-auto">
		<form (submit)="submit($event)">
			<div appDialogHeader>
				<h2 appDialogTitle class="font-display">New assignment</h2>
			</div>

			<div class="p-6 space-y-4">
				<app-form-field
					label="Title"
					htmlFor="assignment-title"
					[required]="true"
					[field]="assignmentForm.title"
				>
					<input
						appFormInput
						id="assignment-title"
						placeholder="Week 1: Treble Notes"
						[formField]="assignmentForm.title"
					/>
				</app-form-field>

				<app-form-field label="Game" htmlFor="assignment-game-type">
					<app-select
						selectId="assignment-game-type"
						[value]="gameType()"
						(valueChange)="changeGameType($event)"
					>
						@for (option of gameTypeOptions; track option.value) {
							<option [value]="option.value">{{ option.label }}</option>
						}
					</app-select>
				</app-form-field>

				<div class="rounded-lg border-2 border-border p-4 space-y-4">
					<div class="flex items-start justify-between gap-2">
						<div class="space-y-1">
							<h3 class="font-medium">{{ gameLabel() }} settings</h3>
							<p class="text-xs text-muted-foreground">
								Frozen when you create the assignment. Changing your own
								settings later will not change it.
							</p>
						</div>
						<app-button variant="ghost" size="sm" (click)="resetSettings()">
							Reset to defaults
						</app-button>
					</div>

					<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
						<app-game-mode-limit-controls
							[settings]="baseSettings()"
							[unit]="isNoteGame() ? 'notes' : 'questions'"
							(changed)="applySettings($event)"
						/>
						@if (settingsSchema(); as schema) {
							<app-settings-controls
								[schema]="schema"
								[settings]="gameSettings()"
								(changed)="applySettings($event)"
							/>
						} @else {
							<div class="space-y-1">
								<label for="assignment-scale" class="text-xs font-medium">
									Scale
								</label>
								<app-select
									selectId="assignment-scale"
									[value]="noteSettings().scale"
									(valueChange)="applySettings({ scale: $event })"
								>
									@for (scale of scales; track scale) {
										<option [value]="scale">{{ scale }}</option>
									}
								</app-select>
							</div>
							<div class="sm:col-span-2">
								<app-note-range-setting
									[clef]="noteSettings().clef"
									[lowNote]="noteSettings().lowNote"
									[highNote]="noteSettings().highNote"
									(settingsChange)="applySettings($event)"
								/>
							</div>
						}
					</div>
				</div>

				<div class="grid grid-cols-1 gap-4 sm:grid-cols-3">
					<app-form-field label="Due date" htmlFor="assignment-due">
						<input
							appFormInput
							id="assignment-due"
							type="datetime-local"
							[formField]="assignmentForm.dueAt"
						/>
					</app-form-field>
					<app-form-field
						label="Target questions"
						htmlFor="assignment-target-q"
						[field]="assignmentForm.targetQuestions"
					>
						<input
							appFormInput
							id="assignment-target-q"
							type="number"
							placeholder="Optional"
							[formField]="assignmentForm.targetQuestions"
						/>
					</app-form-field>
					<app-form-field
						label="Target accuracy %"
						htmlFor="assignment-target-a"
						[field]="assignmentForm.targetAccuracy"
					>
						<input
							appFormInput
							id="assignment-target-a"
							type="number"
							placeholder="Optional"
							[formField]="assignmentForm.targetAccuracy"
						/>
					</app-form-field>
				</div>
			</div>

			<div appDialogFooter>
				<app-button variant="outline" [disabled]="pending()" (click)="close()">
					Cancel
				</app-button>
				<app-button type="submit" variant="brass" [loading]="pending()">
					Create assignment
				</app-button>
			</div>
		</form>
	</div>
</app-dialog>

// frontend/src/features/classes/components/CreateAssignmentDialog.tsx
import { useState } from "react";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogFooter,
} from "@/shared/components/ui/dialog";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Select } from "@/shared/components/ui/select";
import { FormField } from "@/shared/components/forms/FormField";
import {
	SettingsControls,
	GameModeLimitControls,
	CLEF_LABELS,
	TIME_LIMITS,
	NOTE_LIMITS,
	type BaseGameSettings,
	type SettingDescriptor,
} from "@/features/identification-game";
import { SCALES } from "@/features/note-game";
import { StaffRangePicker } from "@/features/note-game/components/StaffRangePicker";
import { DEFAULT_RANGE } from "@/features/note-game/rangeUtils";
import { useCreateAssignment } from "@/shared/hooks/queries";
import {
	GENERIC_GAME_DEFINITIONS as GENERIC_GAMES,
	GAME_TYPE_OPTIONS,
	type GenericGameType,
} from "@/features/classes/gameDefinitions";
import type {
	CreateAssignmentRequest,
	GameType,
	NoteGameSettingsRequest,
} from "@/services/api/types";

// Mirrors the note game's own default settings (see useNoteGame).
const NOTE_DEFAULTS: NoteGameSettingsRequest = {
	low_note: DEFAULT_RANGE.treble.low,
	high_note: DEFAULT_RANGE.treble.high,
	clef: "treble",
	game_mode: "time",
	time_limit: 30,
	note_limit: 25,
	scale: "C Major",
	octave: 4,
};

function defaultConfig(gameType: GameType): Record<string, unknown> {
	if (gameType === "note") {
		return { ...NOTE_DEFAULTS } as unknown as Record<string, unknown>;
	}
	return {
		...GENERIC_GAMES[gameType].defaults,
	} as unknown as Record<string, unknown>;
}

/** Renders a generic game's settings using the same UI the game uses. */
function GenericGameSettings({
	gameType,
	config,
	onPatch,
}: {
	gameType: GenericGameType;
	config: Record<string, unknown>;
	onPatch: (patch: Record<string, unknown>) => void;
}) {
	const definition = GENERIC_GAMES[gameType];
	const settings = config as unknown as BaseGameSettings;
	const patch = (p: Partial<BaseGameSettings>) =>
		onPatch(p as Record<string, unknown>);
	return (
		<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
			<GameModeLimitControls settings={settings} onChange={patch} />
			<SettingsControls
				schema={
					definition.settingsSchema as SettingDescriptor<BaseGameSettings>[]
				}
				settings={settings}
				onChange={patch}
			/>
		</div>
	);
}

/** Minimal controls for the note game's snake_case config shape. */
function NoteGameSettings({
	config,
	onPatch,
}: {
	config: NoteGameSettingsRequest;
	onPatch: (patch: Record<string, unknown>) => void;
}) {
	const isTimeMode = config.game_mode === "time";
	return (
		<div className="space-y-3">
			<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
				<div className="space-y-1">
					<span className="block text-xs font-medium">Mode</span>
					<div className="flex gap-1.5">
						<Button
							size="sm"
							variant={isTimeMode ? "default" : "outline"}
							onClick={() => onPatch({ game_mode: "time" })}
						>
							Time
						</Button>
						<Button
							size="sm"
							variant={!isTimeMode ? "default" : "outline"}
							onClick={() => onPatch({ game_mode: "notes" })}
						>
							Notes
						</Button>
					</div>
				</div>

				<div className="space-y-1">
					<span className="block text-xs font-medium">
						{isTimeMode ? "Time Limit" : "Notes"}
					</span>
					{isTimeMode ? (
						<Select
							aria-label="Time Limit"
							value={String(config.time_limit)}
							onChange={(e) => onPatch({ time_limit: Number(e.target.value) })}
						>
							{TIME_LIMITS.map((limit) => (
								<option key={limit} value={limit}>
									{limit}s
								</option>
							))}
						</Select>
					) : (
						<Select
							aria-label="Note Limit"
							value={String(config.note_limit)}
							onChange={(e) => onPatch({ note_limit: Number(e.target.value) })}
						>
							{NOTE_LIMITS.map((limit) => (
								<option key={limit} value={limit}>
									{limit}
								</option>
							))}
						</Select>
					)}
				</div>

				<div className="space-y-1">
					<span className="block text-xs font-medium">Scale</span>
					<Select
						aria-label="Scale"
						value={config.scale}
						onChange={(e) => onPatch({ scale: e.target.value })}
					>
						{SCALES.map((scale) => (
							<option key={scale} value={scale}>
								{scale}
							</option>
						))}
					</Select>
				</div>

				<div className="space-y-1">
					<span className="block text-xs font-medium">Clef</span>
					<Select
						aria-label="Clef"
						value={config.clef}
						onChange={(e) => {
							const clef = e.target.value as NoteGameSettingsRequest["clef"];
							onPatch({
								clef,
								low_note: DEFAULT_RANGE[clef].low,
								high_note: DEFAULT_RANGE[clef].high,
							});
						}}
					>
						<option value="treble">{CLEF_LABELS.treble}</option>
						<option value="bass">{CLEF_LABELS.bass}</option>
					</Select>
				</div>
			</div>

			<div className="space-y-1">
				<span className="block text-xs font-medium">Note range</span>
				<StaffRangePicker
					clef={config.clef}
					low={config.low_note}
					high={config.high_note}
					onChange={(low, high) => onPatch({ low_note: low, high_note: high })}
				/>
			</div>
		</div>
	);
}

export interface CreateAssignmentDialogProps {
	classId: number;
	open: boolean;
	onOpenChange: (open: boolean) => void;
}

export function CreateAssignmentDialog({
	classId,
	open,
	onOpenChange,
}: CreateAssignmentDialogProps) {
	const createAssignment = useCreateAssignment();

	const [title, setTitle] = useState("");
	const [titleError, setTitleError] = useState<string | undefined>();
	const [gameType, setGameType] = useState<GameType>("note");
	const [config, setConfig] = useState<Record<string, unknown>>(() =>
		defaultConfig("note"),
	);
	const [dueAt, setDueAt] = useState("");
	const [targetQuestions, setTargetQuestions] = useState("");
	const [targetAccuracy, setTargetAccuracy] = useState("");

	// Reset the whole form on close so reopening starts fresh. Done in the
	// open-change handler (an event) rather than an effect.
	function handleOpenChange(next: boolean) {
		if (!next) {
			setTitle("");
			setTitleError(undefined);
			setGameType("note");
			setConfig(defaultConfig("note"));
			setDueAt("");
			setTargetQuestions("");
			setTargetAccuracy("");
		}
		onOpenChange(next);
	}

	function changeGameType(next: GameType) {
		setGameType(next);
		// Switching games snapshots that game's own defaults as the config.
		setConfig(defaultConfig(next));
	}

	function patchConfig(patch: Record<string, unknown>) {
		setConfig((current) => ({ ...current, ...patch }));
	}

	function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		const trimmed = title.trim();
		if (!trimmed) {
			setTitleError("Title is required");
			return;
		}

		const request: CreateAssignmentRequest = {
			title: trimmed,
			game_type: gameType,
			config,
			due_at: dueAt ? new Date(dueAt).toISOString() : null,
			target_questions: targetQuestions.trim() ? Number(targetQuestions) : null,
			target_accuracy: targetAccuracy.trim() ? Number(targetAccuracy) : null,
		};

		createAssignment.mutate(
			{ classId, request },
			{ onSuccess: () => handleOpenChange(false) },
		);
	}

	return (
		<Dialog open={open} onOpenChange={handleOpenChange}>
			<DialogContent
				onOpenChange={handleOpenChange}
				className="max-h-[90vh] overflow-y-auto"
			>
				<form onSubmit={handleSubmit}>
					<DialogHeader>
						<DialogTitle className="font-display">New assignment</DialogTitle>
					</DialogHeader>

					<div className="p-6 space-y-4">
						<FormField
							label="Title"
							required
							htmlFor="assignment-title"
							error={titleError}
						>
							<Input
								id="assignment-title"
								placeholder="Week 1: Treble Notes"
								value={title}
								error={titleError}
								onChange={(e) => {
									setTitle(e.target.value);
									if (titleError) setTitleError(undefined);
								}}
							/>
						</FormField>

						<FormField label="Game" htmlFor="assignment-game-type">
							<Select
								id="assignment-game-type"
								value={gameType}
								onChange={(e) => changeGameType(e.target.value as GameType)}
							>
								{GAME_TYPE_OPTIONS.map((opt) => (
									<option key={opt.value} value={opt.value}>
										{opt.label}
									</option>
								))}
							</Select>
						</FormField>

						<div className="rounded-lg border-2 border-border p-4">
							{gameType === "note" ? (
								<NoteGameSettings
									config={config as unknown as NoteGameSettingsRequest}
									onPatch={patchConfig}
								/>
							) : (
								<GenericGameSettings
									gameType={gameType}
									config={config}
									onPatch={patchConfig}
								/>
							)}
						</div>

						<div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
							<FormField label="Due date" htmlFor="assignment-due">
								<Input
									id="assignment-due"
									type="datetime-local"
									value={dueAt}
									onChange={(e) => setDueAt(e.target.value)}
								/>
							</FormField>
							<FormField label="Target questions" htmlFor="assignment-target-q">
								<Input
									id="assignment-target-q"
									type="number"
									min={1}
									placeholder="Optional"
									value={targetQuestions}
									onChange={(e) => setTargetQuestions(e.target.value)}
								/>
							</FormField>
							<FormField
								label="Target accuracy %"
								htmlFor="assignment-target-a"
							>
								<Input
									id="assignment-target-a"
									type="number"
									min={1}
									max={100}
									placeholder="Optional"
									value={targetAccuracy}
									onChange={(e) => setTargetAccuracy(e.target.value)}
								/>
							</FormField>
						</div>
					</div>

					<DialogFooter>
						<Button
							type="button"
							variant="outline"
							onClick={() => handleOpenChange(false)}
							disabled={createAssignment.isPending}
						>
							Cancel
						</Button>
						<Button
							type="submit"
							variant="brass"
							loading={createAssignment.isPending}
						>
							Create assignment
						</Button>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	);
}
