// frontend/src/features/friends/components/FriendCard.tsx
import type { Friend } from "@/features/friends/types";
import { cn } from "@/lib/utils";

interface FriendCardProps {
	user: Friend;
	action?: React.ReactNode;
	className?: string;
}

export function FriendCard({ user, action, className }: FriendCardProps) {
	return (
		<div
			className={cn(
				"flex items-center gap-3 p-3 rounded-lg transition-colors hover:bg-accent/50",
				className,
			)}
		>
			<img
				src={user.avatarUrl}
				alt={`${user.firstName} ${user.lastName}`}
				className="h-10 w-10 rounded-full"
			/>
			<div className="flex-1 min-w-0">
				<span className="text-sm font-medium truncate block">
					{user.firstName} {user.lastName}
				</span>
				{user.instrument && (
					<p className="text-xs text-muted-foreground truncate">
						{user.instrument}
					</p>
				)}
				{user.school && (
					<p className="text-xs text-muted-foreground truncate">
						{user.school}
					</p>
				)}
			</div>
			{action}
		</div>
	);
}

// frontend/src/app/features/friends/components/friend-card/friend-card.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

import type { Friend } from "../../models/friends.models";

/**
 * One row of the friends panel. Port of
 * frontend-react/src/features/friends/components/FriendCard.tsx.
 *
 * React's `action?: React.ReactNode` prop becomes content projection: the
 * add view puts its button between the tags, the friends list projects
 * nothing and the slot collapses. Same move D9 makes for `GameDefinition` --
 * markup crosses a boundary as a template, never as data.
 *
 * The host is `display: contents` (the same rule `<app-button>` follows) so
 * the row div is the scroll container's own child, exactly as in React.
 */
@Component({
	selector: "app-friend-card",
	imports: [],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: contents;
		}
	`,
	templateUrl: "./friend-card.component.html",
})
export class FriendCardComponent {
	readonly user = input.required<Friend>();
}

<div
	class="flex items-center gap-3 p-3 rounded-lg transition-colors hover:bg-accent/50"
>
	<img
		[src]="user().avatarUrl"
		[alt]="user().firstName + ' ' + user().lastName"
		class="h-10 w-10 rounded-full"
	/>
	<div class="flex-1 min-w-0">
		<span class="text-sm font-medium truncate block"
			>{{ user().firstName }} {{ user().lastName }}</span
		>
		@if (user().instrument) {
			<p class="text-xs text-muted-foreground truncate">
				{{ user().instrument }}
			</p>
		}
		@if (user().school) {
			<p class="text-xs text-muted-foreground truncate">{{ user().school }}</p>
		}
	</div>
	<ng-content />
</div>
