// frontend/src/pages/AssignmentPlayPage.tsx
import { ArrowLeft } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import {
	IdentificationGamePage,
	keySignatureGame,
	scaleGame,
	chordGame,
	intervalGame,
	type BaseGameSettings,
	type GeneratedQuestion,
} from "@/features/identification-game";
import type { GameDefinition } from "@/features/identification-game/games/types";
import { NoteGamePage } from "@/pages/NoteGamePage";
import { Skeleton } from "@/shared/components/ui/skeleton";
import { Button } from "@/shared/components/ui/button";
import { useStudentAssignments } from "@/shared/hooks/queries";
import type { StudentAssignment } from "@/features/classes/types";

/** A game definition with its specifics erased for uniform storage/rendering. */
type AnyGameDefinition = GameDefinition<
	GeneratedQuestion,
	BaseGameSettings,
	unknown
>;

/**
 * Lookup from a generic game type to its declarative definition. The
 * note game is intentionally absent — it renders through NoteGamePage,
 * not the identification shell.
 */
export const GENERIC_GAME_DEFINITIONS: Record<string, AnyGameDefinition> = {
	key_signature: keySignatureGame as unknown as AnyGameDefinition,
	scale: scaleGame as unknown as AnyGameDefinition,
	chord: chordGame as unknown as AnyGameDefinition,
	interval: intervalGame as unknown as AnyGameDefinition,
};

function BackLink() {
	return (
		<Link
			to="/assignments"
			className="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
		>
			<ArrowLeft className="h-4 w-4" />
			Back to assignments
		</Link>
	);
}

function NotFound() {
	return (
		<div className="min-h-screen px-4 py-8">
			<div className="container mx-auto max-w-3xl space-y-4">
				<h1 className="font-display text-2xl font-bold">
					Assignment not found
				</h1>
				<p className="text-sm text-muted-foreground">
					This assignment doesn&apos;t exist or is no longer assigned to you.
				</p>
				<Link to="/assignments">
					<Button variant="default">Back to assignments</Button>
				</Link>
			</div>
		</div>
	);
}

/**
 * Launches an assignment in "assignment mode": the game is configured
 * from the assignment's frozen config (not the student's personal
 * settings), and on completion the score entry is tagged with the
 * assignment id (see IdentificationGamePage / NoteGamePage).
 *
 * There's no direct GET-by-id endpoint, so we find the assignment in
 * the student's assignment list.
 */
export function AssignmentPlayPage() {
	const { id } = useParams<{ id: string }>();
	const assignmentId = Number(id);
	const { data: assignments, isLoading } = useStudentAssignments();

	if (isLoading) {
		return (
			<div className="min-h-screen px-4 py-8">
				<div className="container mx-auto max-w-3xl space-y-4">
					<Skeleton className="h-6 w-40" />
					<Skeleton className="h-64 w-full" />
				</div>
			</div>
		);
	}

	const assignment: StudentAssignment | undefined = assignments?.find(
		(a) => a.id === assignmentId,
	);

	if (!assignment) {
		return <NotFound />;
	}

	const gameConfig = { id: assignment.id, config: assignment.config };

	if (assignment.gameType === "note") {
		return (
			<div className="flex h-[calc(100vh-4rem)] flex-col">
				<div className="px-4 pt-2 sm:px-6">
					<BackLink />
				</div>
				<div className="min-h-0 flex-1">
					<NoteGamePage assignment={gameConfig} />
				</div>
			</div>
		);
	}

	const definition = GENERIC_GAME_DEFINITIONS[assignment.gameType];

	if (!definition) {
		return <NotFound />;
	}

	return (
		<div className="flex h-[calc(100vh-4rem)] flex-col">
			<div className="px-4 pt-2 sm:px-6">
				<BackLink />
			</div>
			<div className="min-h-0 flex-1">
				<IdentificationGamePage
					definition={definition}
					assignment={gameConfig}
				/>
			</div>
		</div>
	);
}

// frontend/src/app/features/classes/components/assignment-play-page/assignment-play-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import { RouterLink } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { SkeletonDirective } from "../../../../shared/components/ui/skeleton.directive";
import type { GameType } from "../../../../shared/models/game.types";
import type { StudentAssignment } from "../../models/classes.models";
import type { AssignmentLaunch } from "../../models/assignment-launch";
import { ClassesService } from "../../services/classes.service";
import { AssignmentGameHostComponent } from "../assignment-game-host/assignment-game-host.component";

/**
 * `/assignments/:id/play` -- launches an assignment in "assignment mode".
 * Port of frontend-react/src/pages/AssignmentPlayPage.tsx.
 *
 * **There is no GET-by-id endpoint for an assignment**, so the assignment
 * is found in the student's own list -- which is also the authorisation
 * check: an assignment for a class the student is not in simply is not in
 * the list, and they get the not-found panel. React relied on exactly the
 * same thing.
 *
 * This slice owns everything up to the handoff: resolve, find, loading,
 * not-found, back link, and the frozen `{ id, config }` launch. The game
 * itself is behind `app-assignment-game-host` (Phases 5 and 6) -- see that
 * component's header.
 *
 * React needed a `useMemo` so the launch object kept a stable identity
 * across re-renders, because the game pages' effects keyed off it. A
 * `computed()` is stable by construction, so that concern has no port.
 */
@Component({
	selector: "app-assignment-play-page",
	imports: [
		AssignmentGameHostComponent,
		ButtonComponent,
		NgIcon,
		RouterLink,
		SkeletonDirective,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./assignment-play-page.component.html",
})
export class AssignmentPlayPageComponent {
	readonly id = input.required<string>();

	private readonly classesService = inject(ClassesService);

	readonly assignmentId = computed(() => Number(this.id()));

	readonly assignments = rxResource({
		stream: () => this.classesService.getStudentAssignments(),
		defaultValue: [] as StudentAssignment[],
	});

	private readonly assignment = computed(() => {
		const id = this.assignmentId();
		if (Number.isNaN(id)) return undefined;
		return this.assignments.value().find((a) => a.id === id);
	});

	/** Everything the game host needs, or `undefined` for the not-found panel. */
	readonly playable = computed<
		{ gameType: GameType; launch: AssignmentLaunch } | undefined
	>(() => {
		const assignment = this.assignment();
		if (!assignment) return undefined;
		return {
			gameType: assignment.gameType,
			launch: { id: assignment.id, config: assignment.config },
		};
	});
}

@if (assignments.isLoading()) {
	<div class="min-h-screen px-4 py-8">
		<div class="container mx-auto max-w-3xl space-y-4">
			<div appSkeleton class="h-6 w-40"></div>
			<div appSkeleton class="h-64 w-full"></div>
		</div>
	</div>
} @else if (assignments.error()) {
	<div class="min-h-screen px-4 py-8">
		<div class="container mx-auto max-w-3xl space-y-4">
			<app-error [error]="assignments.error()" />
			<a routerLink="/assignments">
				<app-button variant="default">Back to assignments</app-button>
			</a>
		</div>
	</div>
} @else if (playable(); as ready) {
	<div class="flex h-[calc(100vh-4rem-2px)] flex-col">
		<div class="px-4 pt-2 sm:px-6">
			<a
				routerLink="/assignments"
				class="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
			>
				<ng-icon name="lucideArrowLeft" size="1rem" aria-hidden="true" />
				Back to assignments
			</a>
		</div>
		<div class="min-h-0 flex-1">
			<app-assignment-game-host
				[gameType]="ready.gameType"
				[launch]="ready.launch"
			/>
		</div>
	</div>
} @else {
	<div class="min-h-screen px-4 py-8">
		<div class="container mx-auto max-w-3xl space-y-4">
			<h1 class="font-display text-2xl font-bold">Assignment not found</h1>
			<p class="text-sm text-muted-foreground">
				This assignment doesn't exist or is no longer assigned to you.
			</p>
			<a routerLink="/assignments">
				<app-button variant="default">Back to assignments</app-button>
			</a>
		</div>
	</div>
}
