// frontend/src/app/features/friends/components/my-friends-view/my-friends-view.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	output,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import { NgIcon } from "@ng-icons/core";

import { AppErrorComponent } from "../../../../core/components/app-error/app-error.component";
import { SpinnerComponent } from "../../../../core/components/spinner/spinner.component";
import { NotificationService } from "../../../../core/services/notification.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { InputDirective } from "../../../../shared/components/ui/input.directive";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import type { Friend } from "../../models/friends.models";
import { FriendsService } from "../../services/friends.service";
import { FriendsUiStore } from "../../services/friends.store";
import { FriendCardComponent } from "../friend-card/friend-card.component";

/**
 * The friends panel's default view. Port of
 * frontend-react/src/features/friends/components/MyFriendsView.tsx.
 *
 * PLAN.md 5.2 in miniature: `useFriends()` becomes an `rxResource`, and the
 * `isLoading / isError / data` ladder becomes the `@if` block in the
 * template. There is no cache and no `staleTime` (D6) -- the panel destroys
 * this component while the add view is up, so coming back is what refetches,
 * which is the behaviour React bought with `invalidateQueries`.
 *
 * The filter is client-side in React and stays client-side here: the search
 * box narrows the list already fetched and never hits `/api/friends/search`
 * (that is the *add* view's endpoint).
 *
 * Accessible names are contracts of `e2e/specs/friends-and-theme.spec.ts`:
 * the "Friends" heading, "Add friend", "Close friends", and the empty-state
 * copy "Looks lonely in here. Add some friends!".
 */
@Component({
	selector: "app-my-friends-view",
	imports: [
		AppErrorComponent,
		ButtonComponent,
		FriendCardComponent,
		InputDirective,
		NgIcon,
		SpinnerComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: contents;
		}
	`,
	templateUrl: "./my-friends-view.component.html",
})
export class MyFriendsViewComponent {
	private readonly service = inject(FriendsService);
	private readonly notifications = inject(NotificationService);

	/** The search box's text lives on the store, exactly as in React. */
	protected readonly ui = inject(FriendsUiStore);

	readonly addFriend = output<void>();
	readonly closed = output<void>();

	protected readonly friends = rxResource({
		stream: () => this.service.getFriends(),
		defaultValue: [] as Friend[],
	});

	/**
	 * `resource.value()` **rethrows** when the resource is in its error
	 * state -- `defaultValue` only covers idle and loading -- and the count
	 * badge sits in the header, outside the template's error branch. React's
	 * `data = []` default swallowed the failure the same way, so the badge
	 * reads 0 rather than taking down the panel.
	 */
	protected readonly allFriends = computed(() =>
		this.friends.error() ? [] : this.friends.value(),
	);

	protected readonly filteredFriends = computed(() => {
		const friends = this.allFriends();
		const query = this.ui.searchQuery().trim().toLowerCase();
		if (!query) return friends;

		return friends.filter(
			(f) =>
				f.firstName.toLowerCase().includes(query) ||
				f.lastName.toLowerCase().includes(query) ||
				f.instrument.toLowerCase().includes(query) ||
				f.school.toLowerCase().includes(query),
		);
	});

	constructor() {
		// React's QueryClient toasted every failed query whose meta named an
		// `errorTitle`, on top of whatever the component rendered inline
		// (App.tsx's `QueryCache.onError`). `useFriends` set
		// "Failed to load friends", so this fetch owes both. The effect fires
		// on each null -> error transition, which is once per failed attempt,
		// the same cadence the cache handler had.
		effect(() => {
			const error = this.friends.error();
			if (error) {
				this.notifications.showError(
					getErrorMessage(error),
					"Failed to load friends",
				);
			}
		});
	}

	protected onSearch(event: Event): void {
		this.ui.setSearchQuery((event.target as HTMLInputElement).value);
	}
}

<div class="p-4 border-b-2 border-border flex items-center justify-between">
	<div class="flex items-center gap-2">
		<h2 class="text-lg font-bold">Friends</h2>
		<span
			class="px-2 py-0.5 rounded-full bg-primary/10 text-primary text-xs font-medium"
			>{{ allFriends().length }}</span
		>
		<app-button
			variant="ghost"
			size="icon"
			className="rounded-full h-8 w-8"
			ariaLabel="Add friend"
			(click)="addFriend.emit()"
		>
			<ng-icon size="1rem" name="lucideUserPlus" aria-hidden="true" />
		</app-button>
	</div>
	<app-button
		variant="ghost"
		size="icon"
		className="rounded-full h-8 w-8"
		ariaLabel="Close friends"
		(click)="closed.emit()"
	>
		<ng-icon size="1rem" name="lucideX" aria-hidden="true" />
	</app-button>
</div>

<div class="p-4 border-b-2 border-border">
	<div class="relative">
		<ng-icon
			size="1rem"
			name="lucideSearch"
			aria-hidden="true"
			class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
		/>
		<input
			appInput
			type="text"
			placeholder="Search friends..."
			class="pl-9"
			[value]="ui.searchQuery()"
			(input)="onSearch($event)"
		/>
	</div>
</div>

<div class="flex-1 overflow-y-auto p-2">
	@if (friends.isLoading()) {
		<app-spinner label="Loading friends" />
	} @else if (friends.error()) {
		<app-error [error]="friends.error()" fallback="Failed to load friends" />
	} @else if (filteredFriends().length > 0) {
		@for (friend of filteredFriends(); track friend.id) {
			<app-friend-card [user]="friend" />
		}
	} @else {
		<div class="flex flex-col items-center justify-center h-32 gap-1">
			<p class="text-sm font-medium text-muted-foreground">
				{{
					ui.searchQuery().trim()
						? "No friends found"
						: "Looks lonely in here. Add some friends!"
				}}
			</p>
		</div>
	}
</div>

// frontend/src/features/friends/components/MyFriendsView.tsx
import { useMemo } from "react";
import { X, Search, Loader2, UserPlus } from "lucide-react";
import { useFriendsStore } from "@/stores/friends.store";
import { useFriends } from "@/shared/hooks/queries";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FriendCard } from "./FriendCard";

interface MyFriendsViewProps {
	onAddFriend: () => void;
	onClose: () => void;
}

export function MyFriendsView({ onAddFriend, onClose }: MyFriendsViewProps) {
	const searchQuery = useFriendsStore((state) => state.searchQuery);
	const setSearchQuery = useFriendsStore((state) => state.setSearchQuery);

	const { data: friends = [], isLoading, isError, error } = useFriends();

	const filteredFriends = useMemo(() => {
		if (!searchQuery.trim()) return friends;
		const q = searchQuery.toLowerCase();
		return friends.filter(
			(f) =>
				f.firstName.toLowerCase().includes(q) ||
				f.lastName.toLowerCase().includes(q) ||
				f.instrument.toLowerCase().includes(q) ||
				f.school.toLowerCase().includes(q),
		);
	}, [friends, searchQuery]);

	return (
		<>
			<div className="p-4 border-b-2 border-border flex items-center justify-between">
				<div className="flex items-center gap-2">
					<h2 className="text-lg font-bold">Friends</h2>
					<span className="px-2 py-0.5 rounded-full bg-primary/10 text-primary text-xs font-medium">
						{friends.length}
					</span>
					<Button
						variant="ghost"
						size="icon"
						onClick={onAddFriend}
						className="rounded-full h-8 w-8"
					>
						<UserPlus className="h-4 w-4" />
					</Button>
				</div>
				<Button
					variant="ghost"
					size="icon"
					onClick={onClose}
					className="rounded-full h-8 w-8"
				>
					<X className="h-4 w-4" />
				</Button>
			</div>

			<div className="p-4 border-b-2 border-border">
				<div className="relative">
					<Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
					<Input
						placeholder="Search friends..."
						value={searchQuery}
						onChange={(e) => setSearchQuery(e.target.value)}
						className="pl-9"
					/>
				</div>
			</div>

			<div className="flex-1 overflow-y-auto p-2">
				{isLoading ? (
					<div className="flex items-center justify-center h-32">
						<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
					</div>
				) : isError ? (
					<div className="flex items-center justify-center h-32">
						<p className="text-sm text-destructive">
							{error?.message ?? "Failed to load friends"}
						</p>
					</div>
				) : filteredFriends.length > 0 ? (
					filteredFriends.map((friend) => (
						<FriendCard key={friend.id} user={friend} />
					))
				) : (
					<div className="flex flex-col items-center justify-center h-32 gap-1">
						<p className="text-sm font-medium text-muted-foreground">
							{searchQuery.trim()
								? "No friends found"
								: "Looks lonely in here. Add some friends!"}
						</p>
					</div>
				)}
			</div>
		</>
	);
}
