// new-frontend/src/features/dashboard/components/DashboardStats.tsx
/**
 * Dashboard Stats Component
 * 
 * Displays a grid of 4 stat cards showing:
 * - Average NPM (Notes Per Minute)
 * - Average Accuracy
 * - Total Time
 * - Total Sessions
 */

import { Card, CardContent } from '@/components/ui/card';
import { TrendingUp, Clock, Target, Calendar } from 'lucide-react';

interface DashboardStatsProps {
  avgNPM: number;
  avgAccuracy: number;
  timeReading: string;
  totalSessions: number;
}

export function DashboardStats({
  avgNPM,
  avgAccuracy,
  timeReading,
  totalSessions,
}: DashboardStatsProps) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      {/* Average NPM */}
      <Card className="hover:shadow-lg transition-shadow">
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">Average NPM</p>
              <p className="text-3xl font-bold text-primary">{avgNPM}</p>
            </div>
            <div className="rounded-lg bg-primary/10 p-2">
              <TrendingUp className="h-6 w-6 text-primary" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Average Accuracy */}
      <Card className="hover:shadow-lg transition-shadow">
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">Avg Accuracy</p>
              <p className="text-3xl font-bold text-accent">{avgAccuracy}%</p>
            </div>
            <div className="rounded-lg bg-accent/10 p-2">
              <Target className="h-6 w-6 text-accent" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Total Time */}
      <Card className="hover:shadow-lg transition-shadow">
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">Total Time</p>
              <p className="text-3xl font-bold">{timeReading}</p>
            </div>
            <div className="rounded-lg bg-primary/10 p-2">
              <Clock className="h-6 w-6 text-primary" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Total Sessions */}
      <Card className="hover:shadow-lg transition-shadow">
        <CardContent className="p-6">
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">Total Sessions</p>
              <p className="text-3xl font-bold">{totalSessions}</p>
            </div>
            <div className="rounded-lg bg-accent/10 p-2">
              <Calendar className="h-6 w-6 text-accent" />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// frontend/src/app/features/dashboard/components/dashboard-stats/dashboard-stats.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";

/**
 * Port of frontend-react/src/features/dashboard/components/DashboardStats.tsx:
 * the four-up stat grid under the performance chart.
 *
 * DESIGN.md rule 4 -- brass is the accuracy/NPM highlight; accuracy and total
 * sessions carry it here, average NPM and total time stay ink. That split is
 * React's and is what the baselines were captured from.
 */
@Component({
	selector: "app-dashboard-stats",
	imports: [NgIcon, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: "block" },
	templateUrl: "./dashboard-stats.component.html",
})
export class DashboardStatsComponent {
	readonly avgNPM = input.required<number>();
	readonly avgAccuracy = input.required<number>();
	readonly timeReading = input.required<string>();
	readonly totalSessions = input.required<number>();
}

<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
	<!-- Average NPM -->
	<div appCard className="hover:shadow-lg transition-shadow">
		<div appCardContent className="p-6">
			<div class="flex items-start justify-between">
				<div class="space-y-2">
					<p class="text-sm text-muted-foreground">Average NPM</p>
					<p class="text-3xl font-bold text-primary">{{ avgNPM() }}</p>
				</div>
				<div class="rounded-lg bg-primary/10 p-2">
					<ng-icon
						name="lucideTrendingUp"
						size="1.5rem"
						aria-hidden="true"
						class="h-6 w-6 text-primary"
					/>
				</div>
			</div>
		</div>
	</div>

	<!-- Average accuracy -->
	<div appCard className="hover:shadow-lg transition-shadow">
		<div appCardContent className="p-6">
			<div class="flex items-start justify-between">
				<div class="space-y-2">
					<p class="text-sm text-muted-foreground">Avg Accuracy</p>
					<p class="text-3xl font-bold text-brass">{{ avgAccuracy() }}%</p>
				</div>
				<div class="rounded-lg bg-brass/10 p-2">
					<ng-icon
						name="lucideTarget"
						size="1.5rem"
						aria-hidden="true"
						class="h-6 w-6 text-brass"
					/>
				</div>
			</div>
		</div>
	</div>

	<!-- Total time -->
	<div appCard className="hover:shadow-lg transition-shadow">
		<div appCardContent className="p-6">
			<div class="flex items-start justify-between">
				<div class="space-y-2">
					<p class="text-sm text-muted-foreground">Total Time</p>
					<p class="text-3xl font-bold">{{ timeReading() }}</p>
				</div>
				<div class="rounded-lg bg-primary/10 p-2">
					<ng-icon
						name="lucideClock"
						size="1.5rem"
						aria-hidden="true"
						class="h-6 w-6 text-primary"
					/>
				</div>
			</div>
		</div>
	</div>

	<!-- Total sessions -->
	<div appCard className="hover:shadow-lg transition-shadow">
		<div appCardContent className="p-6">
			<div class="flex items-start justify-between">
				<div class="space-y-2">
					<p class="text-sm text-muted-foreground">Total Sessions</p>
					<p class="text-3xl font-bold">{{ totalSessions() }}</p>
				</div>
				<div class="rounded-lg bg-brass/10 p-2">
					<ng-icon
						name="lucideCalendar"
						size="1.5rem"
						aria-hidden="true"
						class="h-6 w-6 text-brass"
					/>
				</div>
			</div>
		</div>
	</div>
</div>
