// frontend/src/app/auth/components/google-callback/google-callback-page.component.ts
import { ChangeDetectionStrategy, Component, inject } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";

import { SpinnerComponent } from "../../../core/components/spinner/spinner.component";
import { getErrorMessage } from "../../../shared/utils/error.utils";
import type { LoginResponse } from "../../models/auth.models";
import { AuthService } from "../../services/auth.service";
import { AuthStore } from "../../services/auth.store";
import { GoogleOAuthService } from "../../services/google-oauth.service";

/**
 * Port of frontend-react/src/pages/GoogleCallbackPage.tsx.
 *
 * Google sends the browser back here with `?code=&state=` (or `?error=`).
 * The page never renders anything but a spinner: every path ends in a
 * navigation, so there is nothing to show and therefore no `rxResource`
 * (D6) -- the token exchange is a one-shot action and takes PLAN.md 5.6's
 * plain `.subscribe()`. See the handoff for why sub-feature 1 does not
 * demonstrate the resource pattern.
 *
 * The four failure paths all land on `/login` with a message, exactly as
 * React did; `AuthStore.setNotice()` carries it in place of react-router's
 * location state.
 *
 * The work runs once, in the constructor. React needed a `useRef` guard
 * because StrictMode double-invokes effects; an Angular component is
 * constructed once, so the guard has no port.
 */
@Component({
	selector: "app-google-callback-page",
	imports: [SpinnerComponent],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./google-callback-page.component.html",
})
export class GoogleCallbackPageComponent {
	private readonly auth = inject(AuthService);
	private readonly oauth = inject(GoogleOAuthService);
	private readonly store = inject(AuthStore);
	private readonly router = inject(Router);
	private readonly route = inject(ActivatedRoute);

	constructor() {
		this.exchange();
	}

	private exchange(): void {
		const params = this.route.snapshot.queryParamMap;
		const error = params.get("error");
		const code = params.get("code");
		const state = params.get("state");

		if (error) {
			this.failToLogin(
				error === "access_denied"
					? "Google sign-in was cancelled."
					: "Google sign-in failed. Please try again.",
			);
			return;
		}

		if (!code || !state) {
			this.failToLogin("OAuth callback missing required parameters.");
			return;
		}

		if (!this.oauth.verifyState(state)) {
			this.failToLogin("OAuth state verification failed. Please try again.");
			return;
		}

		this.auth
			.googleCallback({ code, redirect_uri: this.oauth.getRedirectUri() })
			.subscribe({
				next: (response: LoginResponse) => {
					// `AuthService.googleCallback` has already stored the tokens
					// and the user, so this is only the "where next" half.
					if (response.account_linked) {
						this.store.setNotice(
							"info",
							"Your Google account has been linked to your existing account.",
						);
					}
					void this.router.navigateByUrl("/dashboard", { replaceUrl: true });
				},
				error: (err: unknown) => this.failToLogin(getErrorMessage(err)),
			});
	}

	private failToLogin(message: string): void {
		this.store.setNotice("error", message);
		void this.router.navigateByUrl("/login", { replaceUrl: true });
	}
}

<section class="flex min-h-screen items-center justify-center">
	<div class="space-y-4 text-center">
		<app-spinner label="Signing in with Google" />
		<p class="text-muted-foreground">Signing in with Google...</p>
	</div>
</section>

// frontend/src/pages/GoogleCallbackPage.tsx
import { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { useGoogleCallback } from "@/shared/hooks/queries/useAuthQuery";
import {
	verifyOAuthState,
	getRedirectUri,
} from "@/features/auth/services/google-oauth";
import type { LoginLocationState } from "@/shared/types";
import { getErrorMessage } from "@/shared/utils/error.utils";

export function GoogleCallbackPage() {
	const navigate = useNavigate();
	const googleCallback = useGoogleCallback();
	const calledRef = useRef(false);

	useEffect(() => {
		if (calledRef.current) return;
		calledRef.current = true;

		const params = new URLSearchParams(window.location.search);
		const code = params.get("code");
		const state = params.get("state");

		const errorParam = params.get("error");
		if (errorParam) {
			const message =
				errorParam === "access_denied"
					? "Google sign-in was cancelled."
					: "Google sign-in failed. Please try again.";
			navigate("/login", {
				state: { errorMessage: message } satisfies LoginLocationState,
				replace: true,
			});
			return;
		}

		if (!code || !state) {
			navigate("/login", {
				state: {
					errorMessage: "OAuth callback missing required parameters.",
				} satisfies LoginLocationState,
				replace: true,
			});
			return;
		}

		if (!verifyOAuthState(state)) {
			navigate("/login", {
				state: {
					errorMessage: "OAuth state verification failed. Please try again.",
				} satisfies LoginLocationState,
				replace: true,
			});
			return;
		}

		googleCallback.mutate(
			{ code, redirect_uri: getRedirectUri() },
			{
				onSuccess: (response) => {
					if (response.account_linked) {
						// Use a small delay so the toast shows after navigation
						setTimeout(() => {
							window.dispatchEvent(
								new CustomEvent("toast:info", {
									detail:
										"Your Google account has been linked to your existing account.",
								}),
							);
						}, 500);
					}
					navigate("/dashboard", { replace: true });
				},
				onError: (error) => {
					navigate("/login", {
						state: {
							errorMessage: getErrorMessage(error),
						} satisfies LoginLocationState,
						replace: true,
					});
				},
			},
		);
	}, [googleCallback, navigate]);

	return (
		<div className="min-h-screen flex items-center justify-center">
			<div className="text-center space-y-4">
				<div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto" />
				<p className="text-muted-foreground">Signing in with Google...</p>
			</div>
		</div>
	);
}
