// frontend/src/features/classes/components/ClassAssignmentsList.tsx
import { useState } from "react";
import { Plus, Trash2, Loader2 } from "lucide-react";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogFooter,
} from "@/shared/components/ui/dialog";
import { cn } from "@/lib/utils";
import {
	useClassAssignments,
	useDeleteAssignment,
} from "@/shared/hooks/queries";
import type { Assignment } from "@/features/classes/types";
import type { GameType } from "@/services/api/types";
import { CreateAssignmentDialog } from "./CreateAssignmentDialog";

interface ClassAssignmentsListProps {
	classId: number;
	selectedId: number | null;
	onSelect: (assignment: Assignment) => void;
}

const GAME_TYPE_LABELS: Record<GameType, string> = {
	note: "Note",
	key_signature: "Key Signature",
	scale: "Scale",
	chord: "Chord",
	interval: "Interval",
};

function formatDueDate(iso: string | null): string | null {
	if (!iso) return null;
	const date = new Date(iso);
	if (Number.isNaN(date.getTime())) return null;
	return date.toLocaleDateString(undefined, {
		year: "numeric",
		month: "short",
		day: "numeric",
	});
}

function AssignmentRow({
	assignment,
	selected,
	onSelect,
}: {
	assignment: Assignment;
	selected: boolean;
	onSelect: () => void;
}) {
	const [confirmOpen, setConfirmOpen] = useState(false);
	const deleteAssignment = useDeleteAssignment();
	const due = formatDueDate(assignment.dueAt);

	const targets: string[] = [];
	if (assignment.targetQuestions != null) {
		targets.push(`${assignment.targetQuestions} questions`);
	}
	if (assignment.targetAccuracy != null) {
		targets.push(`${assignment.targetAccuracy}% accuracy`);
	}

	function handleDelete() {
		deleteAssignment.mutate(
			{ assignmentId: assignment.id, classId: assignment.classId },
			{ onSuccess: () => setConfirmOpen(false) },
		);
	}

	return (
		<div
			role="button"
			tabIndex={0}
			onClick={onSelect}
			onKeyDown={(e) => {
				if (e.key === "Enter" || e.key === " ") {
					e.preventDefault();
					onSelect();
				}
			}}
			className={cn(
				"flex items-center gap-3 p-3 rounded-lg cursor-pointer transition-colors",
				selected ? "bg-primary text-primary-foreground" : "hover:bg-accent/50",
			)}
		>
			<div className="flex-1 min-w-0">
				<span className="text-sm font-medium truncate block">
					{assignment.title}
				</span>
				<p
					className={cn(
						"text-xs truncate",
						selected ? "text-primary-foreground/70" : "text-muted-foreground",
					)}
				>
					{GAME_TYPE_LABELS[assignment.gameType]}
					{due ? ` · Due ${due}` : ""}
					{targets.length > 0 ? ` · ${targets.join(", ")}` : ""}
				</p>
			</div>
			<Button
				variant="ghost"
				size="icon"
				aria-label={`Delete ${assignment.title}`}
				className={cn(
					selected
						? "text-primary-foreground hover:bg-primary-foreground/10"
						: "text-muted-foreground hover:text-destructive",
				)}
				onClick={(e) => {
					e.stopPropagation();
					setConfirmOpen(true);
				}}
			>
				<Trash2 className="h-4 w-4" />
			</Button>

			<Dialog open={confirmOpen} onOpenChange={setConfirmOpen}>
				<DialogContent onOpenChange={setConfirmOpen} className="max-w-md">
					<DialogHeader>
						<DialogTitle className="font-display">
							Delete assignment?
						</DialogTitle>
					</DialogHeader>
					<div className="p-6">
						<p className="text-sm text-muted-foreground">
							Delete{" "}
							<span className="font-medium text-foreground">
								{assignment.title}
							</span>
							? Student attempts for it will no longer be tracked.
						</p>
					</div>
					<DialogFooter>
						<Button
							type="button"
							variant="outline"
							onClick={() => setConfirmOpen(false)}
							disabled={deleteAssignment.isPending}
						>
							Cancel
						</Button>
						<Button
							type="button"
							variant="destructive"
							loading={deleteAssignment.isPending}
							onClick={handleDelete}
						>
							Delete
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</div>
	);
}

export function ClassAssignmentsList({
	classId,
	selectedId,
	onSelect,
}: ClassAssignmentsListProps) {
	const [isCreateOpen, setIsCreateOpen] = useState(false);
	const {
		data: assignments = [],
		isLoading,
		isError,
		error,
	} = useClassAssignments(classId);

	return (
		<Card>
			<CardHeader className="flex-row items-center justify-between space-y-0">
				<CardTitle className="font-display text-xl">Assignments</CardTitle>
				<Button variant="brass" size="sm" onClick={() => setIsCreateOpen(true)}>
					<Plus className="mr-2 h-4 w-4" />
					New assignment
				</Button>
			</CardHeader>
			<CardContent className="p-2">
				{isLoading ? (
					<div className="flex items-center justify-center h-24">
						<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
					</div>
				) : isError ? (
					<div className="flex items-center justify-center h-24">
						<p className="text-sm text-destructive">
							{error?.message ?? "Failed to load assignments"}
						</p>
					</div>
				) : assignments.length > 0 ? (
					assignments.map((assignment) => (
						<AssignmentRow
							key={assignment.id}
							assignment={assignment}
							selected={assignment.id === selectedId}
							onSelect={() => onSelect(assignment)}
						/>
					))
				) : (
					<div className="flex flex-col items-center justify-center h-24 gap-1 text-center">
						<p className="text-sm font-medium text-muted-foreground">
							No assignments yet — create one to start tracking practice.
						</p>
					</div>
				)}
			</CardContent>

			<CreateAssignmentDialog
				classId={classId}
				open={isCreateOpen}
				onOpenChange={setIsCreateOpen}
			/>
		</Card>
	);
}

// frontend/src/app/features/classes/components/class-assignments-list/class-assignments-list.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	signal,
} from "@angular/core";
import { rxResource } from "@angular/core/rxjs-interop";
import { NgIcon } from "@ng-icons/core";

import { AppErrorComponent } from "../../../../core/components/app-error/app-error.component";
import { ConfirmDialogComponent } from "../../../../core/components/confirm-dialog/confirm-dialog.component";
import { NotificationService } from "../../../../core/services/notification.service";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import { cn } from "../../../../shared/utils/cn";
import { formatDate } from "../../../../shared/utils/date.utils";
import { getErrorMessage } from "../../../../shared/utils/error.utils";
import { GAME_TYPE_LABELS } from "../../models/game-definitions";
import type { Assignment } from "../../models/classes.models";
import { ClassesService } from "../../services/classes.service";
import { CreateAssignmentDialogComponent } from "../create-assignment-dialog/create-assignment-dialog.component";

/**
 * Port of
 * frontend-react/src/features/classes/components/ClassAssignmentsList.tsx:
 * the class's assignments, one selectable row each, plus create and delete.
 *
 * Selecting a row is what reveals the results grid, so the selection lives
 * on the page (`selectedId` in, `assignmentSelected` out) exactly as it did
 * in React -- named the long way because `select` is a DOM event and
 * `@angular-eslint/no-output-native` rightly refuses it.
 * Deleting the selected assignment clears that selection -- React left it
 * pointing at a row that no longer existed, and the grid then fetched
 * results for a deleted id.
 *
 * As in the roster, per-row confirm state is one signal and one dialog
 * rather than a component per row.
 */
@Component({
	selector: "app-class-assignments-list",
	imports: [
		AppErrorComponent,
		ButtonComponent,
		ConfirmDialogComponent,
		CreateAssignmentDialogComponent,
		NgIcon,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./class-assignments-list.component.html",
})
export class ClassAssignmentsListComponent {
	readonly classId = input.required<number>();
	readonly selectedId = input<number | null>(null);

	readonly assignmentSelected = output<Assignment>();
	/** Raised when the selected assignment vanished under the selection. */
	readonly selectionCleared = output<void>();

	private readonly classesService = inject(ClassesService);
	private readonly notifications = inject(NotificationService);

	readonly assignments = rxResource({
		params: () => this.classId(),
		stream: ({ params }) => this.classesService.getClassAssignments(params),
		defaultValue: [] as Assignment[],
	});

	readonly isCreateOpen = signal(false);
	readonly confirming = signal<Assignment | null>(null);
	readonly pending = signal(false);

	readonly confirmDescription = computed(() => {
		const assignment = this.confirming();
		if (!assignment) return "";
		return `Delete ${assignment.title}? Student attempts for it will no longer be tracked.`;
	});

	/**
	 * "Key Signature · Due Jul 20, 2026 · 20 questions, 80% accuracy" --
	 * the same three optional segments React joined with " · ".
	 */
	subtitle(assignment: Assignment): string {
		const targets: string[] = [];
		if (assignment.targetQuestions != null) {
			targets.push(`${assignment.targetQuestions} questions`);
		}
		if (assignment.targetAccuracy != null) {
			targets.push(`${assignment.targetAccuracy}% accuracy`);
		}

		const due = formatDate(assignment.dueAt);
		return (
			GAME_TYPE_LABELS[assignment.gameType] +
			(due ? ` · Due ${due}` : "") +
			(targets.length > 0 ? ` · ${targets.join(", ")}` : "")
		);
	}

	rowClasses(assignment: Assignment): string {
		return cn(
			"flex items-center gap-3 p-3 rounded-lg cursor-pointer transition-colors",
			assignment.id === this.selectedId()
				? "bg-primary text-primary-foreground"
				: "hover:bg-accent/50",
		);
	}

	subtitleClasses(assignment: Assignment): string {
		return cn(
			"text-xs truncate",
			assignment.id === this.selectedId()
				? "text-primary-foreground/70"
				: "text-muted-foreground",
		);
	}

	deleteButtonClasses(assignment: Assignment): string {
		return assignment.id === this.selectedId()
			? "text-primary-foreground hover:bg-primary-foreground/10"
			: "text-muted-foreground hover:text-destructive";
	}

	onRowKeydown(event: KeyboardEvent, assignment: Assignment): void {
		if (event.key === "Enter" || event.key === " ") {
			event.preventDefault();
			this.assignmentSelected.emit(assignment);
		}
	}

	confirmOpenChange(open: boolean): void {
		if (!open) this.confirming.set(null);
	}

	onCreated(): void {
		this.assignments.reload();
	}

	remove(): void {
		const assignment = this.confirming();
		if (!assignment || this.pending()) return;
		this.pending.set(true);

		this.classesService.deleteAssignment(assignment.id).subscribe({
			next: () => {
				this.pending.set(false);
				this.confirming.set(null);
				if (assignment.id === this.selectedId()) this.selectionCleared.emit();
				this.assignments.reload();
			},
			error: (err: unknown) => {
				this.pending.set(false);
				this.notifications.showError(
					getErrorMessage(err),
					"Failed to delete assignment",
				);
			},
		});
	}
}

<div appCard>
	<div
		appCardHeader
		className="flex-row items-center justify-between space-y-0"
	>
		<h3 appCardTitle className="font-display text-xl">Assignments</h3>
		<app-button variant="brass" size="sm" (click)="isCreateOpen.set(true)">
			<ng-icon name="lucidePlus" size="1rem" aria-hidden="true" class="mr-2" />
			New assignment
		</app-button>
	</div>
	<div appCardContent className="p-2">
		@if (assignments.status() === "loading") {
			<div class="flex items-center justify-center h-24">
				<ng-icon
					name="lucideLoader2"
					size="1.5rem"
					aria-hidden="true"
					class="animate-spin text-muted-foreground"
				/>
			</div>
		} @else if (assignments.error()) {
			<app-error [error]="assignments.error()" />
		} @else if (assignments.value().length === 0) {
			<div
				class="flex flex-col items-center justify-center h-24 gap-1 text-center"
			>
				<p class="text-sm font-medium text-muted-foreground">
					No assignments yet — create one to start tracking practice.
				</p>
			</div>
		} @else {
			@for (assignment of assignments.value(); track assignment.id) {
				<div
					role="button"
					tabindex="0"
					[class]="rowClasses(assignment)"
					(click)="assignmentSelected.emit(assignment)"
					(keydown)="onRowKeydown($event, assignment)"
				>
					<div class="flex-1 min-w-0">
						<span class="text-sm font-medium truncate block">{{
							assignment.title
						}}</span>
						<p [class]="subtitleClasses(assignment)">
							{{ subtitle(assignment) }}
						</p>
					</div>
					<app-button
						variant="ghost"
						size="icon"
						[ariaLabel]="'Delete ' + assignment.title"
						[appTooltip]="'Delete ' + assignment.title"
						[className]="deleteButtonClasses(assignment)"
						(click)="$event.stopPropagation(); confirming.set(assignment)"
					>
						<ng-icon name="lucideTrash2" size="1rem" aria-hidden="true" />
					</app-button>
				</div>
			}
		}
	</div>

	<app-confirm-dialog
		[open]="confirming() !== null"
		(openChange)="confirmOpenChange($event)"
		title="Delete assignment?"
		[description]="confirmDescription()"
		confirmLabel="Delete"
		[pending]="pending()"
		(confirm)="remove()"
	/>

	<app-create-assignment-dialog
		[classId]="classId()"
		[(open)]="isCreateOpen"
		(created)="onCreated()"
	/>
</div>
