// frontend/src/pages/HomePage.tsx
import { Link } from "react-router-dom";
import { Music2, TrendingUp, Target, School, User, Users } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";

export function HomePage() {
	return (
		<div className="min-h-screen">
			{/* Hero: ink headline set on faint engraved staff lines */}
			<section className="relative overflow-hidden py-24 px-4">
				<div
					aria-hidden="true"
					className="absolute inset-x-0 top-1/2 -translate-y-1/2 flex flex-col gap-7"
				>
					{[0, 1, 2, 3, 4].map((line) => (
						<div key={line} className="h-px w-full bg-foreground/10" />
					))}
				</div>
				<div className="container mx-auto max-w-6xl relative">
					<div className="text-center space-y-6 animate-fade-in">
						<h1 className="font-display text-5xl md:text-7xl font-bold leading-tight text-balance">
							Master music sight reading
						</h1>
						<p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
							Practice reading notes, key signatures, intervals, scales, and
							chords — built for music students, teachers, and performers
						</p>
						<div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-6">
							<Link to="/note-game">
								<Button size="xl" variant="brass" className="w-full sm:w-auto">
									<Music2 className="mr-2 h-5 w-5" />
									Start practicing
								</Button>
							</Link>
						</div>
					</div>
				</div>
			</section>

			{/* Features Section */}
			<section className="py-20 px-4">
				<div className="container mx-auto max-w-6xl">
					<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
						<Card className="group hover:border-primary hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
									<Music2 className="h-6 w-6 text-primary" />
								</div>
								<CardTitle>Note Recognition Game</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Interactive games that help you identify notes quickly and
									accurately. Track your speed and accuracy in real-time.
								</CardDescription>
							</CardContent>
						</Card>

						<Card className="group hover:border-primary hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-brass/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
									<Target className="h-6 w-6 text-brass" />
								</div>
								<CardTitle>Rhythm Practice</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Customizable exercises focusing on specific rhythm patterns.
									Perfect for UIL preparation and auditions.
								</CardDescription>
							</CardContent>
						</Card>

						<Card className="group hover:border-primary hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
									<TrendingUp className="h-6 w-6 text-primary" />
								</div>
								<CardTitle>Track Progress</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Detailed analytics showing your improvement over time. Set
									goals and celebrate your musical growth.
								</CardDescription>
							</CardContent>
						</Card>
					</div>
				</div>
			</section>

			{/* How It Works Section */}
			<section className="py-20 px-4 bg-muted/30">
				<div className="container mx-auto max-w-4xl">
					<h2 className="font-display text-4xl font-bold text-center mb-12">
						How It Works
					</h2>
					<div className="space-y-8">
						{[
							{
								step: 1,
								title: "Choose Your Exercise",
								description:
									"Select from note games, rhythm practice, or custom exercises tailored to your needs.",
							},
							{
								step: 2,
								title: "Practice & Learn",
								description:
									"Work through exercises tailored to your skill level and goals with immediate feedback.",
							},
							{
								step: 3,
								title: "Track Improvement",
								description:
									"View your progress and celebrate your musical growth with detailed analytics.",
							},
						].map((item) => (
							<div key={item.step} className="flex gap-6 items-start">
								<div className="flex-shrink-0 w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xl font-bold">
									{item.step}
								</div>
								<div className="flex-1">
									<h3 className="text-2xl font-bold mb-2">{item.title}</h3>
									<p className="text-muted-foreground text-lg">
										{item.description}
									</p>
								</div>
							</div>
						))}
					</div>
				</div>
			</section>

			{/* Built For Everyone Section */}
			<section className="py-20 px-4">
				<div className="container mx-auto max-w-6xl">
					<h2 className="font-display text-4xl font-bold text-center mb-12">
						Built For Everyone
					</h2>
					<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
						<Card className="hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
									<School className="h-6 w-6 text-primary" />
								</div>
								<CardTitle>Music Teachers</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Create custom exercises, track student progress, and assign
									practice sessions. Perfect for classroom and individual
									instruction.
								</CardDescription>
							</CardContent>
						</Card>

						<Card className="hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-brass/10 flex items-center justify-center mb-4">
									<User className="h-6 w-6 text-brass" />
								</div>
								<CardTitle>Students</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Build sight-reading confidence for auditions, competitions,
									and UIL practice. Work at your own pace and track your
									improvement.
								</CardDescription>
							</CardContent>
						</Card>

						<Card className="hover:shadow-lg transition-all">
							<CardHeader>
								<div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
									<Users className="h-6 w-6 text-primary" />
								</div>
								<CardTitle>Musicians</CardTitle>
							</CardHeader>
							<CardContent>
								<CardDescription className="text-base">
									Advanced practice for specific chord structures, scale
									patterns, and complex rhythms. Take your skills to the next
									level.
								</CardDescription>
							</CardContent>
						</Card>
					</div>
				</div>
			</section>

			{/* Final CTA Section */}
			<section className="py-20 px-4 bg-muted/30">
				<div className="container mx-auto max-w-4xl text-center space-y-6">
					<h2 className="font-display text-4xl font-bold">
						Ready to Improve Your Sight Reading?
					</h2>
					<p className="text-xl text-muted-foreground">
						Join students and teachers who are already seeing results
					</p>
					<div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-4">
						<Link to="/note-game">
							<Button size="lg">
								<Music2 className="mr-2 h-5 w-5" />
								Start Note Game
							</Button>
						</Link>
						<Link to="/sheet-music">
							<Button size="lg" variant="outline">
								<Target className="mr-2 h-5 w-5" />
								Try Rhythm Practice
							</Button>
						</Link>
					</div>
				</div>
			</section>
		</div>
	);
}

// frontend/src/app/public/home-page/home-page.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../shared/components/ui/card.directive";

/** One row of the "How It Works" list. */
interface HowItWorksStep {
	readonly step: number;
	readonly title: string;
	readonly description: string;
}

/**
 * Port of frontend-react/src/pages/HomePage.tsx.
 *
 * The page holds no state and makes no request -- it is the marketing
 * landing page, reachable at `/home` (the root path redirects to
 * `/note-game`, see app.routes.ts). Everything here is copy and layout, so
 * the component's only job is to carry the two lists the React version
 * mapped over inline.
 *
 * DESIGN.md rule 5 ("hero = notation, not gradient") is the shape of the
 * first section: paper background, faint engraved staff lines behind a
 * one-color ink headline, and a single brass CTA. The staff lines are
 * decorative -- `aria-hidden` in the template -- and the loop below is only
 * there so the template does not repeat the same `<div>` five times.
 */
@Component({
	selector: "app-home-page",
	imports: [RouterLink, NgIcon, ButtonComponent, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./home-page.component.html",
})
export class HomePageComponent {
	/** The five engraved staff lines behind the hero headline. */
	protected readonly staffLines = [0, 1, 2, 3, 4] as const;

	protected readonly steps: readonly HowItWorksStep[] = [
		{
			step: 1,
			title: "Choose Your Exercise",
			description:
				"Select from note games, rhythm practice, or custom exercises tailored to your needs.",
		},
		{
			step: 2,
			title: "Practice & Learn",
			description:
				"Work through exercises tailored to your skill level and goals with immediate feedback.",
		},
		{
			step: 3,
			title: "Track Improvement",
			description:
				"View your progress and celebrate your musical growth with detailed analytics.",
		},
	];
}

<!--
	Port of frontend-react/src/pages/HomePage.tsx, section for section.

	Card overrides go through `className` (tailwind-merge), never `class` --
	see card.directive.ts. Icons are sized with `<ng-icon size="…">` because
	@ng-icons writes its size as an inline style that no `h-*`/`w-*` class
	can beat, and each one is `aria-hidden` because its host carries
	`role="img"` and it sits next to its own label.
-->
<div class="min-h-screen">
	<!-- Hero: ink headline set on faint engraved staff lines -->
	<section class="relative overflow-hidden py-24 px-4">
		<div
			aria-hidden="true"
			class="absolute inset-x-0 top-1/2 -translate-y-1/2 flex flex-col gap-7"
		>
			@for (line of staffLines; track line) {
				<div class="h-px w-full bg-foreground/10"></div>
			}
		</div>
		<div class="container mx-auto max-w-6xl relative">
			<div class="text-center space-y-6 animate-fade-in">
				<h1
					class="font-display text-5xl md:text-7xl font-bold leading-tight text-balance"
				>
					Master music sight reading
				</h1>
				<p class="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
					Practice reading notes, key signatures, intervals, scales, and chords
					— built for music students, teachers, and performers
				</p>
				<div
					class="flex flex-col sm:flex-row gap-4 justify-center items-center pt-6"
				>
					<a routerLink="/note-game">
						<app-button size="xl" variant="brass" className="w-full sm:w-auto">
							<ng-icon
								name="lucideMusic2"
								size="1.25rem"
								aria-hidden="true"
								class="mr-2"
							/>
							Start practicing
						</app-button>
					</a>
				</div>
			</div>
		</div>
	</section>

	<!-- Features Section -->
	<section class="py-20 px-4">
		<div class="container mx-auto max-w-6xl">
			<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
				<a routerLink="/note-game" class="block">
					<div
						appCard
						className="group hover:border-primary hover:shadow-lg transition-all"
					>
						<div appCardHeader>
							<div
								class="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"
							>
								<ng-icon
									name="lucideMusic2"
									size="1.5rem"
									aria-hidden="true"
									class="text-primary"
								/>
							</div>
							<h3 appCardTitle>Note Recognition Game</h3>
						</div>
						<div appCardContent>
							<p appCardDescription className="text-base">
								Interactive games that help you identify notes quickly and
								accurately. Track your speed and accuracy in real-time.
							</p>
						</div>
					</div>
				</a>

				<a routerLink="/sheet-music" class="block">
					<div
						appCard
						className="group hover:border-primary hover:shadow-lg transition-all"
					>
						<div appCardHeader>
							<div
								class="w-12 h-12 rounded-lg bg-brass/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"
							>
								<ng-icon
									name="lucideTarget"
									size="1.5rem"
									aria-hidden="true"
									class="text-brass"
								/>
							</div>
							<h3 appCardTitle>Sheet-Music Generator</h3>
						</div>
						<div appCardContent>
							<p appCardDescription className="text-base">
								Pick a scale, an octave and a 16th- or 8th-note rhythm pattern,
								and get a fresh line of notation to read. Every generation is
								different, so there is nothing to memorize.
							</p>
						</div>
					</div>
				</a>

				<a routerLink="/dashboard" class="block">
					<div
						appCard
						className="group hover:border-primary hover:shadow-lg transition-all"
					>
						<div appCardHeader>
							<div
								class="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"
							>
								<ng-icon
									name="lucideTrendingUp"
									size="1.5rem"
									aria-hidden="true"
									class="text-primary"
								/>
							</div>
							<h3 appCardTitle>Track Progress</h3>
						</div>
						<div appCardContent>
							<p appCardDescription className="text-base">
								Every finished game is saved. Your dashboard charts accuracy and
								notes-per-minute over time, so improvement is something you can
								point at.
							</p>
						</div>
					</div>
				</a>
			</div>
		</div>
	</section>

	<!-- How It Works Section -->
	<section class="py-20 px-4 bg-muted/30">
		<div class="container mx-auto max-w-4xl">
			<h2 class="font-display text-4xl font-bold text-center mb-12">
				How It Works
			</h2>
			<div class="space-y-8">
				@for (item of steps; track item.step) {
					<div class="flex gap-6 items-start">
						<div
							class="flex-shrink-0 w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xl font-bold"
						>
							{{ item.step }}
						</div>
						<div class="flex-1">
							<h3 class="text-2xl font-bold mb-2">{{ item.title }}</h3>
							<p class="text-muted-foreground text-lg">
								{{ item.description }}
							</p>
						</div>
					</div>
				}
			</div>
		</div>
	</section>

	<!-- Built For Everyone Section -->
	<section class="py-20 px-4">
		<div class="container mx-auto max-w-6xl">
			<h2 class="font-display text-4xl font-bold text-center mb-12">
				Built For Everyone
			</h2>
			<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
				<div appCard className="hover:shadow-lg transition-all">
					<div appCardHeader>
						<div
							class="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4"
						>
							<ng-icon
								name="lucideSchool"
								size="1.5rem"
								aria-hidden="true"
								class="text-primary"
							/>
						</div>
						<h3 appCardTitle>Music Teachers</h3>
					</div>
					<div appCardContent>
						<p appCardDescription className="text-base">
							Create custom exercises, track student progress, and assign
							practice sessions. Perfect for classroom and individual
							instruction.
						</p>
						<a
							routerLink="/pricing"
							class="text-sm font-medium text-primary underline-offset-4 hover:underline"
							>Free for pilot teachers this year</a
						>
					</div>
				</div>

				<div appCard className="hover:shadow-lg transition-all">
					<div appCardHeader>
						<div
							class="w-12 h-12 rounded-lg bg-brass/10 flex items-center justify-center mb-4"
						>
							<ng-icon
								name="lucideUser"
								size="1.5rem"
								aria-hidden="true"
								class="text-brass"
							/>
						</div>
						<h3 appCardTitle>Students</h3>
					</div>
					<div appCardContent>
						<p appCardDescription className="text-base">
							Build sight-reading confidence for auditions, competitions, and
							UIL practice. Work at your own pace and track your improvement.
						</p>
					</div>
				</div>

				<div appCard className="hover:shadow-lg transition-all">
					<div appCardHeader>
						<div
							class="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4"
						>
							<ng-icon
								name="lucideUsers"
								size="1.5rem"
								aria-hidden="true"
								class="text-primary"
							/>
						</div>
						<h3 appCardTitle>Musicians</h3>
					</div>
					<div appCardContent>
						<p appCardDescription className="text-base">
							Drill the things that stay hard: chord quality, four scale types,
							and interval recognition across all seven clefs. Narrow any game
							down to exactly the subset you need.
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Final CTA Section -->
	<section class="py-20 px-4 bg-muted/30">
		<div class="container mx-auto max-w-4xl text-center space-y-6">
			<h2 class="font-display text-4xl font-bold">
				Ready to Improve Your Sight Reading?
			</h2>
			<p class="text-xl text-muted-foreground">
				Free for pilot teachers for the whole 2026–27 school year.
			</p>
			<div
				class="flex flex-col sm:flex-row gap-4 justify-center items-center pt-4"
			>
				<a routerLink="/note-game">
					<app-button size="lg">
						<ng-icon
							name="lucideMusic2"
							size="1.25rem"
							aria-hidden="true"
							class="mr-2"
						/>
						Start Note Game
					</app-button>
				</a>
				<a routerLink="/sheet-music">
					<app-button size="lg" variant="outline">
						<ng-icon
							name="lucideTarget"
							size="1.25rem"
							aria-hidden="true"
							class="mr-2"
						/>
						Generate Sheet Music
					</app-button>
				</a>
			</div>
		</div>
	</section>
</div>
