// frontend/src/features/identification-game/components/GameOverCard.tsx
import { RotateCcw } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Card } from "@/shared/components/ui/card";
import type { GameStats } from "../types";
import { GameMode } from "../types";

export interface GameOverCardProps {
	gameStats: GameStats;
	onPlayAgain: () => void;
}

/**
 * Lightweight results screen for the new identification games.
 * The note game keeps its richer GameResults (recent-games chart, save
 * status); this card can grow those once per-game persistence lands.
 */
export function GameOverCard({ gameStats, onPlayAgain }: GameOverCardProps) {
	return (
		<div className="space-y-6 animate-fade-in">
			<div className="text-center space-y-2">
				<h1 className="font-display text-4xl font-bold">Game Over!</h1>
				<p className="text-muted-foreground text-lg">Here&apos;s how you did</p>
			</div>

			<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
				<Card className="p-8 text-center bg-gradient-to-br from-primary/10 to-transparent">
					<div className="font-display text-6xl font-bold tabular-nums text-primary">
						{gameStats.npm}
					</div>
					<div className="text-sm text-muted-foreground mt-2">
						Answers Per Minute
					</div>
				</Card>
				<Card className="p-8 text-center bg-gradient-to-br from-brass/10 to-transparent">
					<div className="font-display text-6xl font-bold tabular-nums text-brass">
						{gameStats.accuracy}%
					</div>
					<div className="text-sm text-muted-foreground mt-2">Accuracy</div>
				</Card>
			</div>

			<Card className="p-4">
				<div className="flex flex-wrap gap-4 justify-center text-sm text-muted-foreground">
					<span>
						Mode: {gameStats.gameMode === GameMode.Time ? "Time" : "Questions"}
					</span>
					<span>•</span>
					<span>
						Limit: {gameStats.limit}{" "}
						{gameStats.gameMode === GameMode.Time ? "seconds" : "questions"}
					</span>
					<span>•</span>
					<span>
						Score: {gameStats.correct}/{gameStats.total}
					</span>
				</div>
			</Card>

			<div className="flex justify-center">
				<Button size="lg" onClick={onPlayAgain}>
					<RotateCcw className="mr-2 h-5 w-5" />
					Play Again
				</Button>
			</div>
		</div>
	);
}

// frontend/src/app/features/identification-game/components/game-over-card/game-over-card.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
	output,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { ButtonComponent } from "@shared/components/ui/button.component";
import { CardDirective } from "@shared/components/ui/card.directive";

import { GameMode, type GameStats } from "../../models/game-state.models";

/**
 * The results screen every identification game shares.
 *
 * Port of
 * frontend-react/src/features/identification-game/components/GameOverCard.tsx.
 * React's three `ReactNode` slots become three content-projection slots, so
 * a game with more to show (Phase 6's note game has a recent-games chart and
 * a save-status line) fills them instead of forking the layout.
 *
 * Three strings here are acceptance criteria, not copy: `e2e/specs/games.spec.ts`
 * waits on the heading **"Game Over!"** and on text matching `/Accuracy/`,
 * `e2e/support/app.ts` reads the score off a node matching
 * `/^Score: \\d+\\/\\d+$/`, and the Play Again button is matched by
 * `/play again/i`.
 */
@Component({
	selector: "app-game-over-card",
	imports: [ButtonComponent, CardDirective, NgIcon],
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
		}
	`,
	template: `
		<div class="animate-fade-in space-y-6">
			<div class="space-y-2 text-center">
				<h1 class="font-display text-4xl font-bold">Game Over!</h1>
				<p class="text-lg text-muted-foreground">Here's how you did</p>
			</div>

			<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
				<div
					appCard
					className="p-8 text-center bg-gradient-to-br from-primary/10 to-transparent"
				>
					<div
						class="font-display text-6xl font-bold tabular-nums text-primary"
					>
						{{ gameStats().npm }}
					</div>
					<div class="mt-2 text-sm text-muted-foreground">
						{{ rateLabel() }}
					</div>
				</div>
				<div
					appCard
					className="p-8 text-center bg-gradient-to-br from-brass/10 to-transparent"
				>
					<div class="font-display text-6xl font-bold tabular-nums text-brass">
						{{ gameStats().accuracy }}%
					</div>
					<div class="mt-2 text-sm text-muted-foreground">Accuracy</div>
				</div>
			</div>

			<ng-content select="[gameOverSections]" />

			<div appCard className="p-4">
				<div
					class="flex flex-wrap justify-center gap-4 text-sm text-muted-foreground"
				>
					<span>Mode: {{ modeLabel() }}</span>
					<span>•</span>
					<span
						>Limit: {{ gameStats().limit }}
						{{ isTimeMode() ? "seconds" : unit() }}</span
					>
					<span>•</span>
					<span>Score: {{ gameStats().correct }}/{{ gameStats().total }}</span>
					<ng-content select="[gameOverSummary]" />
				</div>
			</div>

			<div class="flex flex-col justify-center gap-4 sm:flex-row">
				<app-button size="lg" (click)="playAgain.emit()">
					<ng-icon name="lucideRotateCcw" class="mr-2 h-5 w-5" />
					Play Again
				</app-button>
				<ng-content select="[gameOverActions]" />
			</div>
		</div>
	`,
})
export class GameOverCardComponent {
	readonly gameStats = input.required<GameStats>();

	/** Label under the per-minute figure. */
	readonly rateLabel = input("Answers Per Minute");

	/** Unit word for question-count mode ("questions", "notes"). */
	readonly unit = input("questions");

	readonly playAgain = output<void>();

	protected readonly isTimeMode = computed(
		() => this.gameStats().gameMode === GameMode.Time,
	);

	protected readonly modeLabel = computed(() =>
		this.isTimeMode()
			? "Time"
			: this.unit().charAt(0).toUpperCase() + this.unit().slice(1),
	);
}
