// frontend-react/src/pages/NoteGamePage.tsx
import { useState, useEffect, useMemo, useRef } from "react";
import { useAuthStore } from "@/stores/auth.store";
import { useBreakpoint } from "@/shared/hooks";
import {
	useNoteGameSettings,
	useSaveNoteGameSettings,
	useKeyboardBindings,
} from "@/shared/hooks/queries";
import {
	useSaveGameOnEnd,
	useGameLifecycle,
	ScoreBar,
} from "@/features/identification-game";
import { DEFAULT_NOTE_TO_KEY_MAP } from "@/features/note-game/hooks/useKeyboardInput";
import {
	useNoteGame,
	GameState,
	GameMode,
	type GameSettingsType,
} from "@/features/note-game";
import { keyBindingsToNoteMap } from "@/features/note-game/utils";
import {
	GameBoard,
	GameBoardLandscape,
} from "@/features/note-game/components/GameBoard";
import { GameResults } from "@/features/note-game/components/GameResults";
import { SettingsBar } from "@/features/note-game/components/SettingsBar";
import type { NoteGameSettingsRequest } from "@/services/api/types";

/**
 * Maps a snake_case note-game config (the assignment's frozen config, or
 * the student's saved settings response — both shaped like
 * NoteGameSettingsRequest) to the camelCase GameSettingsType the engine
 * uses. Per-field undefined guards let a partial config (e.g. a stale or
 * hand-edited assignment blob) degrade gracefully instead of clobbering
 * fields with `undefined`.
 */
function mapNoteConfigToSettings(
	config: Partial<NoteGameSettingsRequest>,
): Partial<GameSettingsType> {
	const patch: Partial<GameSettingsType> = {};
	if (config.game_mode !== undefined)
		patch.gameMode = config.game_mode as GameMode;
	if (config.time_limit !== undefined) patch.timeLimit = config.time_limit;
	if (config.note_limit !== undefined) patch.noteLimit = config.note_limit;
	if (config.scale !== undefined) patch.scale = config.scale;
	if (config.octave !== undefined) patch.octave = config.octave;
	if (config.low_note !== undefined) patch.lowNote = config.low_note;
	if (config.high_note !== undefined) patch.highNote = config.high_note;
	if (config.clef !== undefined) patch.clef = config.clef;
	return patch;
}

export interface NoteGamePageProps {
	/**
	 * When set, the note game runs in "assignment mode": settings are
	 * hydrated from the assignment's frozen config (snake_case
	 * NoteGameSettingsRequest) instead of the student's saved settings,
	 * the settings save-back is suppressed, and the finished attempt is
	 * tagged with the assignment id.
	 */
	assignment?: { id: number; config: Record<string, unknown> };
}

/**
 * Note Recognition Game Page
 * Main orchestrator for the note game feature - manages state flow between
 * ready, playing, and results screens
 */
export function NoteGamePage({ assignment }: NoteGamePageProps = {}) {
	const { isAuthenticated } = useAuthStore();
	const { isPhoneLandscape } = useBreakpoint();
	const [bindingsDialogOpen, setBindingsDialogOpen] = useState(false);
	const { handleGameEnd, saveError } = useSaveGameOnEnd("note", assignment?.id);
	const { data: savedSettings } = useNoteGameSettings(!assignment);
	const saveSettings = useSaveNoteGameSettings();
	const { data: savedKeyboardBindings } = useKeyboardBindings();

	const keyBindings = useMemo(
		() =>
			savedKeyboardBindings
				? keyBindingsToNoteMap(savedKeyboardBindings.key_bindings)
				: undefined,
		[savedKeyboardBindings],
	);

	const { timeRemaining, startTimer, formatTime, endGameRef } =
		useGameLifecycle();

	const {
		gameState,
		currentNote,
		answers,
		gameStats,
		settings,
		updateSettings,
		handleAnswer,
		endGame,
		resetGame,
		syncCurrentNote,
	} = useNoteGame({
		onGameEnd: handleGameEnd,
		// The engine reads callbacks through a ref, so this closure sees
		// the latest settings when the first answer starts the game.
		onGameStart: () => {
			if (settings.gameMode === GameMode.Time) {
				startTimer(settings.timeLimit);
			}
			// In assignment mode, never persist back — playing an
			// assignment must not overwrite the student's own settings.
			if (isAuthenticated && !assignment) {
				saveSettings.mutate({
					game_mode: settings.gameMode,
					time_limit: settings.timeLimit,
					note_limit: settings.noteLimit,
					scale: settings.scale,
					octave: settings.octave,
					low_note: settings.lowNote,
					high_note: settings.highNote,
					clef: settings.clef,
				});
			}
		},
		keyBindings,
		inputDisabled: bindingsDialogOpen,
	});

	useEffect(() => {
		endGameRef.current = endGame;
	}, [endGame, endGameRef]);

	// Hydrate settings from the assignment's frozen config (assignment
	// mode) or the student's saved settings (normal play). The note
	// config is snake_case (NoteGameSettingsRequest); map it to the
	// game's camelCase settings so it flows through the normal state.
	const appliedAssignmentRef = useRef(false);
	useEffect(() => {
		if (assignment) {
			if (appliedAssignmentRef.current) return;
			appliedAssignmentRef.current = true;
			const config = assignment.config as Partial<NoteGameSettingsRequest>;
			updateSettings(mapNoteConfigToSettings(config));
			return;
		}
		if (savedSettings) {
			updateSettings(mapNoteConfigToSettings(savedSettings));
		}
	}, [assignment, savedSettings, updateSettings]);

	const statusBar =
		gameState === GameState.Playing ? (
			<ScoreBar
				answers={answers}
				timeRemaining={timeRemaining}
				noteLimit={settings.noteLimit}
				gameMode={settings.gameMode}
				formatTime={formatTime}
			/>
		) : (
			<SettingsBar
				settings={settings}
				onSettingsChange={updateSettings}
				onDialogOpenChange={setBindingsDialogOpen}
			/>
		);

	const gameBoardProps = {
		currentNote,
		answers,
		onAnswer: handleAnswer,
		onNoteGenerated: syncCurrentNote,
		scale: settings.scale,
		octave: settings.octave,
		range: {
			lowNote: settings.lowNote,
			highNote: settings.highNote,
			clef: settings.clef,
		},
		keyBindings: keyBindings ?? DEFAULT_NOTE_TO_KEY_MAP,
	};

	const landscapeLayout = (
		<GameBoardLandscape {...gameBoardProps} statusBar={statusBar} />
	);

	const portraitLayout = (
		<div className="flex flex-col flex-1 min-h-0 gap-2 sm:gap-4">
			<div className="flex-shrink-0">{statusBar}</div>
			<GameBoard {...gameBoardProps} />
		</div>
	);

	return (
		<div className="h-[calc(100vh-4rem)] flex flex-col py-2 px-2 sm:py-4 sm:px-4">
			<div className="container mx-auto max-w-6xl flex flex-col flex-1 min-h-0">
				{gameState === GameState.GameOver && gameStats ? (
					<GameResults
						gameStats={gameStats}
						isAuthenticated={isAuthenticated}
						onPlayAgain={resetGame}
						saveError={saveError}
					/>
				) : isPhoneLandscape ? (
					landscapeLayout
				) : (
					portraitLayout
				)}
			</div>
		</div>
	);
}

// frontend/src/app/features/note-game/components/note-game-page/note-game-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	input,
	untracked,
} from "@angular/core";
import { rxResource, takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { NgTemplateOutlet } from "@angular/common";

import { AuthStore } from "../../../../auth/services/auth.store";
import { BreakpointService } from "../../../../shared/services/breakpoint.service";
import type { NoteGameSettings } from "../../../../shared/models/game.models";
import { UserService } from "../../../../shared/services/user.service";
import { GameMode, GameState } from "../../models/engine.models";
import {
	keyBindingsToNoteMap,
	noteMapToKeyBindings,
	DEFAULT_NOTE_TO_KEY_MAP,
} from "../../models/keymap";
import type { GameSettings } from "../../models/note-game.models";
import { GameTimerService } from "../../services/game-timer.service";
import { NoteGameService } from "../../services/note-game.service";
import { SaveGameOnEndService } from "../../services/save-game-on-end.service";
import {
	NoteGameBoardComponent,
	NoteGameBoardLandscapeComponent,
} from "../note-game-board/note-game-board.component";
import { NoteGameResultsComponent } from "../note-game-results/note-game-results.component";
import { ScoreBarComponent } from "../score-bar/score-bar.component";
import { SettingsBarComponent } from "../settings-bar/settings-bar.component";

/**
 * Note Recognition Game. Port of
 * frontend-react/src/pages/NoteGamePage.tsx.
 *
 * The orchestrator: it owns the three services the game needs, hydrates the
 * settings, and swaps between the settings bar, the score bar and the results
 * screen. Everything else is delegated.
 *
 * **Settings are persisted when the game starts, not when a control is
 * clicked.** That is `settings.spec.ts`'s golden flow, stated in its own
 * header: a port that saved on every click would pass the spec while
 * hammering the API. `NoteGameService.started` fires synchronously inside the
 * first answer, which is where both the save and the countdown begin.
 *
 * **`octave` is read and written but never acted on.** It rides through
 * `mapSavedSettings` and back out in the save so a row written before the
 * range picker existed still loads; the range is what plays
 * (`frontend/CLAUDE.md`).
 */
@Component({
	selector: "app-note-game-page",
	imports: [
		NgTemplateOutlet,
		NoteGameBoardComponent,
		NoteGameBoardLandscapeComponent,
		NoteGameResultsComponent,
		ScoreBarComponent,
		SettingsBarComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [NoteGameService, GameTimerService, SaveGameOnEndService],
	styles: `
		:host {
			display: block;
		}
	`,
	templateUrl: "./note-game-page.component.html",
})
export class NoteGamePageComponent {
	private readonly users = inject(UserService);
	private readonly auth = inject(AuthStore);
	private readonly timer = inject(GameTimerService);
	private readonly saver = inject(SaveGameOnEndService);

	protected readonly game = inject(NoteGameService);
	protected readonly breakpoints = inject(BreakpointService);

	/**
	 * Assignment mode: settings come from the assignment's frozen config
	 * instead of the student's saved row, the settings save-back is
	 * suppressed, and the finished attempt is tagged with the assignment id.
	 *
	 * Nothing routes to this yet -- `AssignmentGameHostComponent` still
	 * renders its stub, because Phase 5 owns that file too and both game
	 * shells land in it at the merge. See the handoff.
	 */
	readonly assignment = input<{
		id: number;
		config: Partial<NoteGameSettings>;
	}>();

	protected readonly states = GameState;
	protected readonly isAuthenticated = this.auth.isAuthenticated;

	protected readonly timeRemaining = this.timer.timeRemaining;
	protected readonly formatTime = (seconds: number): string =>
		this.timer.formatTime(seconds);
	protected readonly saveError = this.saver.saveError;

	/** `null` (or a 404) means "nothing saved yet", not an error. */
	private readonly savedSettings = rxResource({
		params: () =>
			this.assignment() === undefined && this.auth.isAuthenticated()
				? this.auth.user()?.id
				: undefined,
		stream: () => this.users.getNoteGameSettings(),
	});

	private readonly savedBindings = rxResource({
		params: () =>
			this.auth.isAuthenticated() ? this.auth.user()?.id : undefined,
		stream: () => this.users.getKeyboardBindings(),
	});

	/** Note -> key, for the answer-pad hints and the bindings dialog. */
	protected readonly noteToKeyMap = computed(() => {
		const saved = this.savedBindings.value();
		return saved
			? keyBindingsToNoteMap(saved.keyBindings)
			: DEFAULT_NOTE_TO_KEY_MAP;
	});

	protected readonly range = computed(() => {
		const settings = this.game.settings();
		return {
			lowNote: settings.lowNote,
			highNote: settings.highNote,
			clef: settings.clef,
		};
	});

	protected readonly answersLength = computed(() => this.game.answers().length);

	/** Guards the assignment hydration: apply its frozen config exactly once. */
	private assignmentApplied = false;

	constructor() {
		// The timer ends the game; the game's start starts the timer. React
		// broke that circle with `endGameRef`; two subscriptions do it here.
		this.timer.expired
			.pipe(takeUntilDestroyed())
			.subscribe(() => this.game.endGame());

		this.game.started
			.pipe(takeUntilDestroyed())
			.subscribe(() => this.onStart());

		this.game.ended
			.pipe(takeUntilDestroyed())
			.subscribe((stats) =>
				this.saver.handleGameEnd(stats, "note", this.assignment()?.id),
			);

		// Custom bindings feed the keydown stream.
		effect(() => {
			const saved = this.savedBindings.value();
			untracked(() =>
				this.game.keyBindings.set(
					saved ? keyBindingsToNoteMap(saved.keyBindings) : undefined,
				),
			);
		});

		// Hydrate from the assignment's frozen config, or the player's saved
		// row. Both are the same shape; per-field guards let a partial or
		// hand-edited config degrade rather than clobber a field with
		// undefined.
		effect(() => {
			const assignment = this.assignment();
			if (assignment) {
				if (this.assignmentApplied) return;
				this.assignmentApplied = true;
				untracked(() =>
					this.game.updateSettings(mapSavedSettings(assignment.config)),
				);
				return;
			}

			const saved = this.savedSettings.value();
			if (!saved) return;
			untracked(() => this.game.updateSettings(mapSavedSettings(saved)));
		});
	}

	protected onAnswer(answer: string): void {
		this.game.handleAnswer(answer);
	}

	protected onQuestionLoaded(noteName: string): void {
		this.game.syncCurrentNote(noteName);
	}

	protected onSettingsChange(patch: Partial<GameSettings>): void {
		this.game.updateSettings(patch);
	}

	protected onPlayAgain(): void {
		this.timer.resetTimer();
		this.saver.reset();
		this.game.resetGame();
	}

	protected onBindingsOpenChange(open: boolean): void {
		this.game.inputDisabled.set(open);
	}

	protected onSaveBindings(noteToKey: Record<string, string>): void {
		this.users
			.saveKeyboardBindings(noteMapToKeyBindings(noteToKey))
			.subscribe(() => this.savedBindings.reload());
	}

	/** The first answer: start the clock, and commit the settings played with. */
	private onStart(): void {
		const settings = this.game.settings();

		if (settings.gameMode === GameMode.Time) {
			this.timer.startTimer(settings.timeLimit);
		}

		// Playing an assignment must never overwrite the student's own
		// settings.
		if (!this.auth.isAuthenticated() || this.assignment()) return;

		this.users
			.saveNoteGameSettings({
				gameMode: settings.gameMode,
				timeLimit: settings.timeLimit,
				noteLimit: settings.noteLimit,
				scale: settings.scale,
				octave: settings.octave,
				lowNote: settings.lowNote,
				highNote: settings.highNote,
				clef: settings.clef,
			})
			.subscribe({
				// Fire and forget, as React's mutation was: a failed settings
				// save must not interrupt the game that just started.
				error: () => undefined,
			});
	}
}

/**
 * A saved (or assignment-frozen) settings row as a settings patch.
 *
 * Per-field guards, ported from React's `mapNoteConfigToSettings`: a row that
 * predates a field -- or an assignment config someone edited by hand -- must
 * leave that setting at its default rather than set it to `undefined`.
 *
 * `octave` is copied through deliberately. It does nothing, and a row saved
 * before the range picker existed still has to load (`frontend/CLAUDE.md`).
 */
function mapSavedSettings(
	saved: Partial<NoteGameSettings>,
): Partial<GameSettings> {
	const patch: Partial<GameSettings> = {};
	if (saved.gameMode !== undefined) patch.gameMode = saved.gameMode as GameMode;
	if (saved.timeLimit !== undefined) patch.timeLimit = saved.timeLimit;
	if (saved.noteLimit !== undefined) patch.noteLimit = saved.noteLimit;
	if (saved.scale !== undefined) patch.scale = saved.scale;
	if (saved.octave !== undefined) patch.octave = saved.octave;
	if (saved.lowNote !== undefined) patch.lowNote = saved.lowNote;
	if (saved.highNote !== undefined) patch.highNote = saved.highNote;
	if (saved.clef !== undefined) patch.clef = saved.clef;
	return patch;
}

/** Exported for the spec: the mapping is where a legacy row is honoured. */
export { mapSavedSettings as mapSavedNoteGameSettings };

<div class="h-[calc(100vh-4rem-2px)] flex flex-col py-2 px-2 sm:py-4 sm:px-4">
	<div class="container mx-auto max-w-6xl flex flex-col flex-1 min-h-0">
		@if (game.gameState() === states.GameOver && game.gameStats(); as stats) {
			<app-note-game-results
				[gameStats]="stats"
				[saveError]="saveError()"
				(playAgain)="onPlayAgain()"
			/>
		} @else if (breakpoints.isPhoneLandscape()) {
			<app-note-game-board-landscape
				[answersLength]="answersLength()"
				[currentNote]="game.currentNote()"
				[scale]="game.settings().scale"
				[octave]="game.settings().octave"
				[range]="range()"
				[keyMap]="hintKeyMap()"
				(answer)="onAnswer($event)"
				(questionLoaded)="onQuestionLoaded($event)"
			>
				<ng-container *ngTemplateOutlet="statusBar" />
			</app-note-game-board-landscape>
		} @else {
			<div class="flex flex-col flex-1 min-h-0 gap-2 sm:gap-4">
				<div class="flex-shrink-0">
					<ng-container *ngTemplateOutlet="statusBar" />
				</div>
				<app-note-game-board
					[answersLength]="answersLength()"
					[currentNote]="game.currentNote()"
					[scale]="game.settings().scale"
					[octave]="game.settings().octave"
					[range]="range()"
					[keyMap]="hintKeyMap()"
					(answer)="onAnswer($event)"
					(questionLoaded)="onQuestionLoaded($event)"
				/>
			</div>
		}
	</div>
</div>

<!--
	The score bar replaces the settings bar during play, in both layouts, so
	it is declared once and stamped where each layout wants it.
-->
<ng-template #statusBar>
	@if (game.gameState() === states.Playing) {
		<app-score-bar
			[answers]="game.answers()"
			[gameMode]="game.settings().gameMode"
			[timeRemaining]="timeRemaining()"
			[noteLimit]="game.settings().noteLimit"
			[formatTime]="formatTime"
		/>
	} @else {
		<app-settings-bar
			[settings]="game.settings()"
			[bindings]="noteToKeyMap()"
			[overlapAccidentals]="game.overlapAccidentals()"
			(settingsChange)="onSettingsChange($event)"
			(saveBindings)="onSaveBindings($event)"
			(bindingsOpenChange)="onBindingsOpenChange($event)"
		/>
	}
</ng-template>
