// frontend-react/src/features/dashboard/components/TeacherDashboard.tsx
/**
 * Teacher Dashboard Component
 *
 * Displays teacher-specific information and features:
 * - Teacher name
 * - Number of students (placeholder for future implementation)
 * - Entry point to classes & assignments
 */

import { Link } from "react-router-dom";
import {
	Card,
	CardContent,
	CardHeader,
	CardTitle,
} from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import type { UserProfile } from "@/services/api/types";

interface TeacherDashboardProps {
	user: UserProfile;
	studentCount?: number;
}

export function TeacherDashboard({
	user,
	studentCount,
}: TeacherDashboardProps) {
	return (
		<Card className="shadow-lg">
			<CardHeader>
				<CardTitle className="text-2xl">Teacher Dashboard</CardTitle>
			</CardHeader>
			<CardContent className="space-y-4">
				<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
					<div>
						<p className="text-sm text-muted-foreground mb-1">Name</p>
						<p className="font-medium">
							{user.firstName} {user.lastName}
						</p>
					</div>
					<div>
						<p className="text-sm text-muted-foreground mb-1">
							Number of Students
						</p>
						<p className="font-medium text-primary">
							{studentCount !== undefined ? studentCount : "Coming soon"}
						</p>
					</div>
				</div>
				<div className="flex items-center justify-between gap-4">
					<p className="text-sm text-muted-foreground">
						Create classes, hand out join codes, assign exercises, and track
						results per assignment.
					</p>
					<Button asChild variant="brass">
						<Link to="/classes">My Classes</Link>
					</Button>
				</div>
			</CardContent>
		</Card>
	);
}

// frontend/src/app/features/dashboard/components/teacher-dashboard/teacher-dashboard.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
} from "@angular/core";
import { RouterLink } from "@angular/router";

import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import type { UserProfile } from "../../../../shared/models/user.models";

/**
 * Port of frontend-react/src/features/dashboard/components/TeacherDashboard.tsx.
 * Rendered only for a signed-in teacher, below the stats grid.
 *
 * `studentCount` is still the placeholder React left: unset renders
 * "Coming soon".
 */
@Component({
	selector: "app-teacher-dashboard",
	imports: [ButtonComponent, RouterLink, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: "block" },
	templateUrl: "./teacher-dashboard.component.html",
})
export class TeacherDashboardComponent {
	readonly user = input.required<UserProfile>();
	readonly studentCount = input<number | null>(null);

	protected readonly fullName = computed(
		() => `${this.user().firstName} ${this.user().lastName}`,
	);

	protected readonly studentCountLabel = computed(() => {
		const count = this.studentCount();
		return count === null ? "Coming soon" : String(count);
	});
}

<div appCard className="shadow-lg">
	<div appCardHeader>
		<h3 appCardTitle className="text-2xl">Teacher Dashboard</h3>
	</div>
	<div appCardContent className="space-y-4">
		<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
			<div>
				<p class="mb-1 text-sm text-muted-foreground">Name</p>
				<p class="font-medium">{{ fullName() }}</p>
			</div>
			<div>
				<p class="mb-1 text-sm text-muted-foreground">Number of Students</p>
				<p class="font-medium text-primary">{{ studentCountLabel() }}</p>
			</div>
		</div>
		<div class="flex items-center justify-between gap-4">
			<p class="text-sm text-muted-foreground">
				Create classes, hand out join codes, assign exercises, and track results
				per assignment.
			</p>
			<!--
				React's `<Button asChild>` ignores `asChild` and always renders a
				real <button> wrapping its children, so this is a <button> around
				an <a> there too. Reproduced rather than "corrected": the
				baselines were captured from that markup, and the parity suite
				reaches the link by its role either way.
			-->
			<app-button variant="brass">
				<a routerLink="/classes">My Classes</a>
			</app-button>
		</div>
	</div>
</div>
