// frontend/src/app/public/about-page/about-page.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { CARD_DIRECTIVES } from "../../shared/components/ui/card.directive";

/**
 * One icon-and-prose row under "For Music Educators" / "For Developing
 * Musicians".
 *
 * `tileClass` and `iconClass` hold **complete** class strings rather than a
 * tone name a template turns into a class. Tailwind scans `src/**\/*.{ts,html}`
 * for literals, so a string written out here is emitted; one assembled at
 * runtime (`` `bg-${tone}/10` ``) never is. Same trap sub-feature 1 hit with
 * the password-strength colours.
 */
interface Highlight {
	readonly icon: string;
	readonly tileClass: string;
	readonly iconClass: string;
	readonly title: string;
	readonly description: string;
}

const PRIMARY_TILE =
	"flex-shrink-0 w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center";
const BRASS_TILE =
	"flex-shrink-0 w-12 h-12 rounded-lg bg-brass/10 flex items-center justify-center";

/**
 * Port of frontend-react/src/pages/AboutPage.tsx.
 *
 * Static copy, no state and no request. React wrote all five highlight rows
 * out longhand; they are identical in structure, so they live here as data
 * and the template loops. The rendered DOM is the same either way, which is
 * what the screenshot baselines care about.
 *
 * The headings here are deliberately **not** `font-display`: React's About
 * page never applied it (only HomePage did), and the baselines were captured
 * from that. See phase-3-subfeature-2-handoff.md.
 */
@Component({
	selector: "app-about-page",
	imports: [NgIcon, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./about-page.component.html",
})
export class AboutPageComponent {
	protected readonly educatorHighlights: readonly Highlight[] = [
		{
			icon: "lucideBook",
			tileClass: PRIMARY_TILE,
			iconClass: "text-primary",
			title: "Real Reading, Not Memorization",
			description:
				"The biggest challenge in music education is students memorizing pieces instead of learning to sight-read. Our dynamic exercises prevent memorization by generating unique patterns every time, forcing students to engage with actual note reading.",
		},
		{
			icon: "lucideTrophy",
			tileClass: BRASS_TILE,
			iconClass: "text-brass",
			title: "UIL-Focused Practice",
			description:
				"Tremolo targets specific rhythms and patterns that frequently appear in UIL sight reading competitions. Students can practice the exact skills they'll need to succeed in competitive settings.",
		},
		{
			icon: "lucideBrain",
			tileClass: PRIMARY_TILE,
			iconClass: "text-primary",
			title: "Customizable Learning Paths",
			description:
				"Every student learns differently. Create tailored exercises that target specific weaknesses, reinforce strengths, and adapt to individual learning speeds and styles.",
		},
	];

	protected readonly musicianHighlights: readonly Highlight[] = [
		{
			icon: "lucideMusic2",
			tileClass: PRIMARY_TILE,
			iconClass: "text-primary",
			title: "Advanced Skill Development",
			description:
				"Work on complex chord structures, challenging scale degree jumps, and intricate intervallic patterns. Build the sight-reading skills that separate good musicians from great ones.",
		},
		{
			icon: "lucideTrendingUp",
			tileClass: BRASS_TILE,
			iconClass: "text-brass",
			title: "Practice What You Need",
			description:
				"Preparing for an audition? Working on a challenging piece? Customize your practice to target exactly what you need. Track your progress with detailed analytics and see measurable improvement over time.",
		},
	];
}

<!--
	Port of frontend-react/src/pages/AboutPage.tsx, section for section.

	Card overrides go through `className` (tailwind-merge), never `class` --
	see card.directive.ts. Icons are sized with `<ng-icon size="…">` and are
	`aria-hidden`, because the host carries `role="img"` and each one sits
	beside the heading it decorates.
-->
<div class="min-h-screen py-12 px-4">
	<div class="container mx-auto max-w-4xl space-y-12">
		<!-- Mission Statement -->
		<section class="space-y-6 animate-fade-in">
			<h1 class="text-5xl font-bold">About Tremolo</h1>

			<div appCard className="border-primary/50 shadow-lg">
				<div appCardHeader>
					<h3 appCardTitle className="text-2xl">Our Mission</h3>
				</div>
				<div appCardContent className="space-y-4 text-lg text-muted-foreground">
					<p>
						Tremolo was born from real classroom experience as a percussion
						director who witnessed a fundamental problem: students were
						memorizing sheet music instead of actually learning to read it.
					</p>
					<p>
						We believe in building genuine skills over memorization tricks.
						That's why every exercise in Tremolo is dynamically generated—no two
						practice sessions are ever the same. Students can't memorize their
						way through; they have to actually learn to read music.
					</p>
					<p>
						From beginner fundamentals to advanced concepts, Tremolo adapts to
						every skill level. Whether you're a 6th grader just starting your
						musical journey or a seasoned musician preparing for an important
						audition, we have the tools to help you improve.
					</p>
				</div>
			</div>
		</section>

		<!-- For Music Educators -->
		<section class="space-y-6">
			<h2 class="text-4xl font-bold">For Music Educators</h2>

			<div class="space-y-6">
				@for (item of educatorHighlights; track item.title) {
					<div class="flex gap-4 items-start">
						<div [class]="item.tileClass">
							<ng-icon
								size="1.5rem"
								aria-hidden="true"
								[name]="item.icon"
								[class]="item.iconClass"
							/>
						</div>
						<div class="flex-1">
							<h3 class="text-2xl font-bold mb-2">{{ item.title }}</h3>
							<p class="text-muted-foreground text-lg">
								{{ item.description }}
							</p>
						</div>
					</div>
				}
			</div>
		</section>

		<!-- For Developing Musicians -->
		<section class="space-y-6">
			<h2 class="text-4xl font-bold">For Developing Musicians</h2>

			<div class="space-y-6">
				@for (item of musicianHighlights; track item.title) {
					<div class="flex gap-4 items-start">
						<div [class]="item.tileClass">
							<ng-icon
								size="1.5rem"
								aria-hidden="true"
								[name]="item.icon"
								[class]="item.iconClass"
							/>
						</div>
						<div class="flex-1">
							<h3 class="text-2xl font-bold mb-2">{{ item.title }}</h3>
							<p class="text-muted-foreground text-lg">
								{{ item.description }}
							</p>
						</div>
					</div>
				}
			</div>
		</section>

		<!-- Vision Statement -->
		<section class="space-y-6">
			<div
				appCard
				className="border-primary/50 shadow-lg bg-gradient-to-br from-primary/5 to-brass/5"
			>
				<div appCardHeader>
					<h3 appCardTitle className="text-3xl">The Vision</h3>
				</div>
				<div appCardContent className="text-lg text-muted-foreground">
					<p>
						We're building a comprehensive solution that covers everything from
						beginner fundamentals to advanced concepts. Whether you're a 6th
						grader learning your first notes or a seasoned musician preparing
						for a professional audition, Tremolo will have the tools and
						exercises you need to succeed.
					</p>
					<p class="mt-4">
						Our goal is simple: make sight-reading practice effective, engaging,
						and accessible to everyone. Real skills. Real progress. Real
						results.
					</p>
				</div>
			</div>
		</section>
	</div>
</div>

// new-frontend/src/pages/AboutPage.tsx
import { Book, Trophy, Brain, Music2, TrendingUp } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export function AboutPage() {
  return (
    <div className="min-h-screen py-12 px-4">
      <div className="container mx-auto max-w-4xl space-y-12">
        {/* Mission Statement */}
        <section className="space-y-6 animate-fade-in">
          <h1 className="text-5xl font-bold">About Tremolo</h1>
          
          <Card className="border-primary/50 shadow-lg">
            <CardHeader>
              <CardTitle className="text-2xl">Our Mission</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-lg text-muted-foreground">
              <p>
                Tremolo was born from real classroom experience as a percussion director who witnessed
                a fundamental problem: students were memorizing sheet music instead of actually learning
                to read it.
              </p>
              <p>
                We believe in building genuine skills over memorization tricks. That's why every exercise
                in Tremolo is dynamically generated—no two practice sessions are ever the same. Students
                can't memorize their way through; they have to actually learn to read music.
              </p>
              <p>
                From beginner fundamentals to advanced concepts, Tremolo adapts to every skill level.
                Whether you're a 6th grader just starting your musical journey or a seasoned musician
                preparing for an important audition, we have the tools to help you improve.
              </p>
            </CardContent>
          </Card>
        </section>

        {/* For Music Educators */}
        <section className="space-y-6">
          <h2 className="text-4xl font-bold">For Music Educators</h2>
          
          <div className="space-y-6">
            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                <Book className="h-6 w-6 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2">Real Reading, Not Memorization</h3>
                <p className="text-muted-foreground text-lg">
                  The biggest challenge in music education is students memorizing pieces instead of
                  learning to sight-read. Our dynamic exercises prevent memorization by generating
                  unique patterns every time, forcing students to engage with actual note reading.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-accent/10 flex items-center justify-center">
                <Trophy className="h-6 w-6 text-accent" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2">UIL-Focused Practice</h3>
                <p className="text-muted-foreground text-lg">
                  Tremolo targets specific rhythms and patterns that frequently appear in UIL sight
                  reading competitions. Students can practice the exact skills they'll need to succeed
                  in competitive settings.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                <Brain className="h-6 w-6 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2">Customizable Learning Paths</h3>
                <p className="text-muted-foreground text-lg">
                  Every student learns differently. Create tailored exercises that target specific
                  weaknesses, reinforce strengths, and adapt to individual learning speeds and styles.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* For Developing Musicians */}
        <section className="space-y-6">
          <h2 className="text-4xl font-bold">For Developing Musicians</h2>
          
          <div className="space-y-6">
            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                <Music2 className="h-6 w-6 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2">Advanced Skill Development</h3>
                <p className="text-muted-foreground text-lg">
                  Work on complex chord structures, challenging scale degree jumps, and intricate
                  intervallic patterns. Build the sight-reading skills that separate good musicians
                  from great ones.
                </p>
              </div>
            </div>

            <div className="flex gap-4 items-start">
              <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-accent/10 flex items-center justify-center">
                <TrendingUp className="h-6 w-6 text-accent" />
              </div>
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-2">Practice What You Need</h3>
                <p className="text-muted-foreground text-lg">
                  Preparing for an audition? Working on a challenging piece? Customize your practice
                  to target exactly what you need. Track your progress with detailed analytics and
                  see measurable improvement over time.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Vision Statement */}
        <section className="space-y-6">
          <Card className="border-primary/50 shadow-lg bg-gradient-to-br from-primary/5 to-accent/5">
            <CardHeader>
              <CardTitle className="text-3xl">The Vision</CardTitle>
            </CardHeader>
            <CardContent className="text-lg text-muted-foreground">
              <p>
                We're building a comprehensive solution that covers everything from beginner
                fundamentals to advanced concepts. Whether you're a 6th grader learning your first
                notes or a seasoned musician preparing for a professional audition, Tremolo will
                have the tools and exercises you need to succeed.
              </p>
              <p className="mt-4">
                Our goal is simple: make sight-reading practice effective, engaging, and accessible
                to everyone. Real skills. Real progress. Real results.
              </p>
            </CardContent>
          </Card>
        </section>
      </div>
    </div>
  );
}
