// frontend/src/app/features/account/components/account-page/account-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	inject,
	signal,
} from "@angular/core";
import {
	form,
	FormField,
	validateStandardSchema,
} from "@angular/forms/signals";
import { Router } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { AuthService } from "../../../../auth/services/auth.service";
import { AuthStore } from "../../../../auth/services/auth.store";
import { NotificationService } from "../../../../core/services/notification.service";
import { FormFieldComponent } from "../../../../shared/components/forms/form-field.component";
import { FormInputDirective } from "../../../../shared/components/forms/form-input.directive";
import { ButtonComponent } from "../../../../shared/components/ui/button.component";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";
import {
	type DeleteAccountFormData,
	deleteAccountSchema,
	type PasswordChangeFormData,
	passwordChangeSchema,
} from "../../../../shared/validators/auth.schemas";

const BLANK_PASSWORD_FORM: PasswordChangeFormData = {
	currentPassword: "",
	newPassword: "",
	confirmPassword: "",
};

const BLANK_DELETE_FORM: DeleteAccountFormData = { emailConfirmation: "" };

/**
 * Account settings. Port of frontend-react/src/pages/AccountPage.tsx.
 *
 * Five cards and a confirmation modal, of which **nothing talks to the
 * server**: React answered the password form, the data download and the
 * deletion with toasts, because the Go service registers no route for any
 * of them (`core-api/controllers/user_info_controller.go` mounts one
 * GET). That is ported as-is -- the strings below are the product's current
 * promises, not placeholders someone forgot. There is therefore **no
 * `rxResource` on this page**; see phase-3-subfeature-3-handoff.md.
 *
 * Two Signal Forms live here rather than one, exactly as React ran two
 * `useForm`s: the schemas are unrelated and the delete form has to reset
 * independently when the modal is dismissed.
 */
@Component({
	selector: "app-account-page",
	imports: [
		ButtonComponent,
		FormField,
		FormFieldComponent,
		FormInputDirective,
		NgIcon,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./account-page.component.html",
})
export class AccountPageComponent {
	private readonly auth = inject(AuthService);
	private readonly store = inject(AuthStore);
	private readonly router = inject(Router);
	private readonly notifications = inject(NotificationService);

	readonly user = this.store.user;

	/** Reveals all three password fields at once, as React's single flag did. */
	readonly showPasswords = signal(false);
	readonly showDeleteModal = signal(false);

	private readonly passwordModel = signal<PasswordChangeFormData>({
		...BLANK_PASSWORD_FORM,
	});
	readonly passwordForm = form(this.passwordModel, (path) => {
		validateStandardSchema(path, passwordChangeSchema);
	});

	private readonly deleteModel = signal<DeleteAccountFormData>({
		...BLANK_DELETE_FORM,
	});
	readonly deleteForm = form(this.deleteModel, (path) => {
		validateStandardSchema(path, deleteAccountSchema);
	});

	togglePasswords(): void {
		this.showPasswords.update((shown) => !shown);
	}

	submitPasswordChange(event: Event): void {
		event.preventDefault();

		this.passwordForm().markAsTouched();
		if (this.passwordForm().invalid()) return;

		this.notifications.showInfo("Password update functionality coming soon!");
		// `reset(value)` clears touched/dirty *and* sets the model back, which
		// is the pair React Hook Form's `reset()` did in one call.
		this.passwordForm().reset({ ...BLANK_PASSWORD_FORM });
	}

	downloadData(): void {
		this.notifications.showInfo(
			"Your data download will begin shortly. (Feature coming soon)",
		);
	}

	openDeleteModal(): void {
		this.showDeleteModal.set(true);
	}

	closeDeleteModal(): void {
		this.showDeleteModal.set(false);
		this.deleteForm().reset({ ...BLANK_DELETE_FORM });
	}

	submitDelete(event: Event): void {
		event.preventDefault();

		this.deleteForm().markAsTouched();
		if (this.deleteForm().invalid()) return;

		const email = this.user()?.email;
		if (this.deleteModel().emailConfirmation !== email) {
			this.notifications.showError("Email does not match your account email");
			return;
		}

		this.notifications.showSuccess("Account deletion would occur here");
		// React ran this through `useLogout().mutate(...)` for its `onSuccess`
		// hook; `AuthService.logout()` is local-only and synchronous (the Go
		// service has no logout endpoint), so the navigation follows it
		// directly.
		this.auth.logout();
		void this.router.navigateByUrl("/");
	}
}

@if (user(); as currentUser) {
	<div class="min-h-screen px-4 py-8">
		<div class="container mx-auto max-w-4xl space-y-6">
			<div class="space-y-2 text-center">
				<h1 class="text-4xl font-bold">Account Settings</h1>
				<p class="text-lg text-muted-foreground">
					Manage your security, privacy, and account preferences
				</p>
			</div>

			<!-- Account security -->
			<div appCard className="shadow-lg">
				<div appCardHeader>
					<div class="flex items-center gap-3">
						<div class="rounded-lg bg-primary/10 p-2">
							<ng-icon
								name="lucideShield"
								size="1.5rem"
								aria-hidden="true"
								class="text-primary"
							/>
						</div>
						<div>
							<h3 appCardTitle>Account Security</h3>
							<p appCardDescription>Manage your password and authentication</p>
						</div>
					</div>
				</div>
				<div appCardContent>
					<!--
						`flex flex-col gap-4`, where React wrote `space-y-4`: the
						children are `<app-form-field>` and `<app-button>`, whose
						hosts are `display: contents`, and a margin on a contents
						box is ignored. Flex `gap` lays out the real elements.
						phase-3-subfeature-1-handoff.md 7.3.
					-->
					<form
						class="flex flex-col gap-4"
						(submit)="submitPasswordChange($event)"
					>
						<app-form-field
							label="Current Password"
							htmlFor="currentPassword"
							[field]="passwordForm.currentPassword"
						>
							<div class="relative">
								<input
									appFormInput
									id="currentPassword"
									class="pr-10"
									autocomplete="current-password"
									placeholder="Enter current password"
									[type]="showPasswords() ? 'text' : 'password'"
									[formField]="passwordForm.currentPassword"
								/>
								<!--
									The e2e locators are now exact-match, so this button's
									accessible name no longer collides with
									`getByLabel("Password")` (a substring match). It flips
									all four password fields at once (since #249 -- see
									emailCurrentPassword below), which the label says.
								-->
								<button
									type="button"
									class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground"
									[attr.aria-label]="passwordsToggleLabel()"
									[appTooltip]="passwordsToggleLabel()"
									(click)="togglePasswords()"
								>
									<ng-icon
										size="1rem"
										[name]="showPasswords() ? 'lucideEyeOff' : 'lucideEye'"
										aria-hidden="true"
										class="h-4 w-4"
									/>
								</button>
							</div>
						</app-form-field>

						<app-form-field
							label="New Password"
							htmlFor="newPassword"
							[field]="passwordForm.newPassword"
						>
							<input
								appFormInput
								id="newPassword"
								autocomplete="new-password"
								placeholder="Enter new password"
								[type]="showPasswords() ? 'text' : 'password'"
								[formField]="passwordForm.newPassword"
							/>
						</app-form-field>

						<app-form-field
							label="Confirm New Password"
							htmlFor="confirmPassword"
							[field]="passwordForm.confirmPassword"
						>
							<input
								appFormInput
								id="confirmPassword"
								autocomplete="new-password"
								placeholder="Confirm new password"
								[type]="showPasswords() ? 'text' : 'password'"
								[formField]="passwordForm.confirmPassword"
							/>
						</app-form-field>

						<!--
							`self-start` restores what `space-y-4` gave for free.
							React's button was an `inline-flex` box in block flow, so
							it was shrink-to-fit; as a column flex item it would
							stretch to the card's full width instead. The form fields
							above *should* stretch, so `items-start` on the form is
							not the fix -- only the button opts out.
						-->
						<app-button
							type="submit"
							className="self-start"
							[loading]="passwordPending()"
						>
							<ng-icon
								name="lucideKey"
								size="1rem"
								aria-hidden="true"
								class="mr-2 h-4 w-4"
							/>
							Update Password
						</app-button>
					</form>
				</div>
			</div>

			<!-- Email management -->
			<div appCard className="shadow-lg">
				<div appCardHeader>
					<div class="flex items-center gap-3">
						<div class="rounded-lg bg-brass/10 p-2">
							<ng-icon
								name="lucideMail"
								size="1.5rem"
								aria-hidden="true"
								class="text-brass"
							/>
						</div>
						<div>
							<h3 appCardTitle>Email Management</h3>
							<p appCardDescription>Update your email address</p>
						</div>
					</div>
				</div>
				<div appCardContent className="space-y-4">
					<div class="space-y-2">
						<p class="text-sm font-medium">Current Email</p>
						<div class="flex items-center gap-2">
							<span class="text-lg font-medium">{{ currentUser.email }}</span>
							@if (currentUser.emailVerified) {
								<span
									class="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary"
								>
									<ng-icon
										name="lucideCheckCircle2"
										size="0.875rem"
										aria-hidden="true"
									/>
									Verified
								</span>
							} @else {
								<span
									class="inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground"
								>
									<ng-icon
										name="lucideAlertTriangle"
										size="0.875rem"
										aria-hidden="true"
									/>
									Unverified
								</span>
							}
						</div>
					</div>

					<form
						class="flex flex-col gap-4"
						(submit)="submitEmailChange($event)"
					>
						<app-form-field
							label="Current Password"
							htmlFor="emailCurrentPassword"
							[field]="emailForm.currentPassword"
						>
							<input
								appFormInput
								id="emailCurrentPassword"
								autocomplete="current-password"
								placeholder="Enter current password"
								[type]="showPasswords() ? 'text' : 'password'"
								[formField]="emailForm.currentPassword"
							/>
						</app-form-field>

						<app-form-field
							label="New Email Address"
							htmlFor="newEmail"
							[field]="emailForm.newEmail"
						>
							<input
								appFormInput
								id="newEmail"
								type="email"
								autocomplete="email"
								placeholder="Enter new email address"
								[formField]="emailForm.newEmail"
							/>
						</app-form-field>

						<app-button
							type="submit"
							className="self-start"
							[loading]="emailPending()"
						>
							<ng-icon
								name="lucideMail"
								size="1rem"
								aria-hidden="true"
								class="mr-2 h-4 w-4"
							/>
							Send Confirmation Link
						</app-button>
					</form>
				</div>
			</div>

			<!-- Privacy settings -->
			<div appCard className="shadow-lg">
				<div appCardHeader>
					<div class="flex items-center gap-3">
						<div class="rounded-lg bg-primary/10 p-2">
							<ng-icon
								name="lucideShield"
								size="1.5rem"
								aria-hidden="true"
								class="text-primary"
							/>
						</div>
						<div>
							<h3 appCardTitle>Privacy Settings</h3>
							<p appCardDescription>Control your data visibility</p>
						</div>
					</div>
				</div>
				<div appCardContent className="space-y-4">
					<p class="text-sm text-muted-foreground">
						Privacy controls will allow you to manage:
					</p>
					<ul class="space-y-2 text-sm text-muted-foreground">
						<li>&bull; Teacher access to your performance data</li>
						<li>&bull; Parent visibility of practice sessions</li>
						<li>&bull; Inclusion in class leaderboards</li>
						<li>&bull; Email notification preferences</li>
					</ul>
				</div>
			</div>

			<!-- Data & privacy -->
			<div appCard className="shadow-lg">
				<div appCardHeader>
					<div class="flex items-center gap-3">
						<div class="rounded-lg bg-brass/10 p-2">
							<ng-icon
								name="lucideDownload"
								size="1.5rem"
								aria-hidden="true"
								class="text-brass"
							/>
						</div>
						<div>
							<h3 appCardTitle>Data &amp; Privacy</h3>
							<p appCardDescription>Download or delete your data</p>
						</div>
					</div>
				</div>
				<div appCardContent className="space-y-4">
					<div>
						<h4 class="mb-2 font-medium">Download Your Data</h4>
						<p class="mb-4 text-sm text-muted-foreground">
							Get a copy of all your practice data, statistics, and account
							information in JSON format.
						</p>
						<app-button
							variant="outline"
							[loading]="exporting()"
							(click)="exportData()"
						>
							<ng-icon
								name="lucideDownload"
								size="1rem"
								aria-hidden="true"
								class="mr-2 h-4 w-4"
							/>
							Download All My Data
						</app-button>
					</div>
				</div>
			</div>

			<!-- Danger zone -->
			<div appCard className="border-destructive/50 shadow-lg">
				<div appCardHeader>
					<div class="flex items-center gap-3">
						<div class="rounded-lg bg-destructive/10 p-2">
							<ng-icon
								name="lucideAlertTriangle"
								size="1.5rem"
								aria-hidden="true"
								class="text-destructive"
							/>
						</div>
						<div>
							<h3 appCardTitle className="text-destructive">Danger Zone</h3>
							<p appCardDescription>Irreversible account actions</p>
						</div>
					</div>
				</div>
				<div appCardContent className="space-y-4">
					<div>
						<h4 class="mb-2 font-medium">Delete Account</h4>
						<p class="mb-4 text-sm text-muted-foreground">
							Once you delete your account, there is no going back. All your
							data will be permanently removed.
						</p>
						<app-button variant="destructive" (click)="openDeleteModal()">
							<ng-icon
								name="lucideTrash2"
								size="1rem"
								aria-hidden="true"
								class="mr-2 h-4 w-4"
							/>
							Delete My Account
						</app-button>
					</div>
				</div>
			</div>

			@if (showDeleteModal()) {
				<div
					class="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-sm"
				>
					<div
						appCard
						className="w-full max-w-md border-destructive shadow-2xl"
					>
						<div appCardHeader>
							<h3 appCardTitle className="text-destructive">
								Confirm Account Deletion
							</h3>
							<p appCardDescription>This action cannot be undone</p>
						</div>
						<div appCardContent>
							<form class="flex flex-col gap-4" (submit)="submitDelete($event)">
								<p class="text-sm">
									All your practice data, statistics, and account information
									will be permanently deleted. Type your email address to
									confirm:
								</p>
								<app-form-field
									htmlFor="emailConfirmation"
									[field]="deleteForm.emailConfirmation"
								>
									<input
										appFormInput
										id="emailConfirmation"
										type="email"
										[placeholder]="currentUser.email"
										[formField]="deleteForm.emailConfirmation"
									/>
								</app-form-field>
								<app-form-field
									label="Current Password"
									htmlFor="deletePassword"
									[field]="deleteForm.password"
								>
									<input
										appFormInput
										id="deletePassword"
										type="password"
										autocomplete="current-password"
										[formField]="deleteForm.password"
									/>
									<p class="text-xs text-muted-foreground">
										Leave blank if you only sign in with Google.
									</p>
								</app-form-field>
								@if (deleteError()) {
									<p role="alert" class="text-sm text-destructive">
										{{ deleteError() }}
									</p>
								}
								<div class="flex gap-2">
									<app-button
										type="button"
										variant="outline"
										className="flex-1"
										(click)="closeDeleteModal()"
									>
										Cancel
									</app-button>
									<app-button
										type="submit"
										variant="destructive"
										className="flex-1"
										[loading]="deleting()"
									>
										Permanently Delete Account
									</app-button>
								</div>
							</form>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
}

// new-frontend/src/pages/AccountPage.tsx
import { useState } from 'react';
import { useAuthStore } from '@/stores/auth.store';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Shield, Mail, Key, Download, Trash2, Eye, EyeOff, AlertTriangle } from 'lucide-react';

export function AccountPage() {
  const { user, logoutUser } = useAuthStore();
  const navigate = useNavigate();

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPasswords, setShowPasswords] = useState(false);
  const [deleteConfirmation, setDeleteConfirmation] = useState('');
  const [showDeleteModal, setShowDeleteModal] = useState(false);

  if (!user) return null;

  const handlePasswordUpdate = (e: React.FormEvent) => {
    e.preventDefault();
    // Mock password update
    alert('Password update functionality coming soon!');
  };

  const handleDownloadData = () => {
    // Mock data download
    alert('Your data download will begin shortly. (Feature coming soon)');
  };

  const handleDeleteAccount = () => {
    if (deleteConfirmation === user.email) {
      alert('Account deletion would occur here');
      logoutUser();
      navigate('/');
    }
  };

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="container mx-auto max-w-4xl space-y-6">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-bold">Account Settings</h1>
          <p className="text-muted-foreground text-lg">
            Manage your security, privacy, and account preferences
          </p>
        </div>

        {/* Account Security */}
        <Card className="shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-primary/10 p-2">
                <Shield className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle>Account Security</CardTitle>
                <CardDescription>Manage your password and authentication</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <form onSubmit={handlePasswordUpdate} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="currentPassword">Current Password</Label>
                <div className="relative">
                  <Input
                    id="currentPassword"
                    type={showPasswords ? 'text' : 'password'}
                    value={currentPassword}
                    onChange={(e) => setCurrentPassword(e.target.value)}
                    placeholder="Enter current password"
                    className="pr-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPasswords(!showPasswords)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  >
                    {showPasswords ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </button>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="newPassword">New Password</Label>
                <Input
                  id="newPassword"
                  type={showPasswords ? 'text' : 'password'}
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                  placeholder="Enter new password"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm New Password</Label>
                <Input
                  id="confirmPassword"
                  type={showPasswords ? 'text' : 'password'}
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="Confirm new password"
                />
              </div>

              <Button type="submit">
                <Key className="mr-2 h-4 w-4" />
                Update Password
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Email Management */}
        <Card className="shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-accent/10 p-2">
                <Mail className="h-6 w-6 text-accent" />
              </div>
              <div>
                <CardTitle>Email Management</CardTitle>
                <CardDescription>Update your email address</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Current Email</Label>
              <div className="text-lg font-medium">{user.email}</div>
            </div>
            <p className="text-sm text-muted-foreground">
              Email change functionality coming soon. You'll be able to update your email address
              and verify the new address before the change takes effect.
            </p>
          </CardContent>
        </Card>

        {/* Privacy Settings */}
        <Card className="shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-primary/10 p-2">
                <Shield className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle>Privacy Settings</CardTitle>
                <CardDescription>Control your data visibility</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Privacy controls will allow you to manage:
            </p>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li>• Teacher access to your performance data</li>
              <li>• Parent visibility of practice sessions</li>
              <li>• Inclusion in class leaderboards</li>
              <li>• Email notification preferences</li>
            </ul>
          </CardContent>
        </Card>

        {/* Data & Privacy */}
        <Card className="shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-accent/10 p-2">
                <Download className="h-6 w-6 text-accent" />
              </div>
              <div>
                <CardTitle>Data & Privacy</CardTitle>
                <CardDescription>Download or delete your data</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h4 className="font-medium mb-2">Download Your Data</h4>
              <p className="text-sm text-muted-foreground mb-4">
                Get a copy of all your practice data, statistics, and account information in JSON format.
              </p>
              <Button variant="outline" onClick={handleDownloadData}>
                <Download className="mr-2 h-4 w-4" />
                Download All My Data
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Danger Zone */}
        <Card className="shadow-lg border-destructive/50">
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-destructive/10 p-2">
                <AlertTriangle className="h-6 w-6 text-destructive" />
              </div>
              <div>
                <CardTitle className="text-destructive">Danger Zone</CardTitle>
                <CardDescription>Irreversible account actions</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h4 className="font-medium mb-2">Delete Account</h4>
              <p className="text-sm text-muted-foreground mb-4">
                Once you delete your account, there is no going back. All your data will be permanently removed.
              </p>
              <Button
                variant="destructive"
                onClick={() => setShowDeleteModal(true)}
              >
                <Trash2 className="mr-2 h-4 w-4" />
                Delete My Account
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Delete Confirmation Modal */}
        {showDeleteModal && (
          <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <Card className="w-full max-w-md shadow-2xl border-destructive">
              <CardHeader>
                <CardTitle className="text-destructive">Confirm Account Deletion</CardTitle>
                <CardDescription>This action cannot be undone</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-sm">
                  All your practice data, statistics, and account information will be permanently deleted.
                  Type your email address to confirm:
                </p>
                <Input
                  type="email"
                  placeholder={user.email}
                  value={deleteConfirmation}
                  onChange={(e) => setDeleteConfirmation(e.target.value)}
                />
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    onClick={() => {
                      setShowDeleteModal(false);
                      setDeleteConfirmation('');
                    }}
                    className="flex-1"
                  >
                    Cancel
                  </Button>
                  <Button
                    variant="destructive"
                    onClick={handleDeleteAccount}
                    disabled={deleteConfirmation !== user.email}
                    className="flex-1"
                  >
                    Permanently Delete Account
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
