// frontend/src/app/features/account/components/profile-page/profile-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
} from "@angular/core";
import { NgIcon } from "@ng-icons/core";

import { AuthStore } from "../../../../auth/services/auth.store";
import { CARD_DIRECTIVES } from "../../../../shared/components/ui/card.directive";

/**
 * One of the six "proposed feature" cards. React repeated the same six-line
 * block six times; the shape is identical every time, so it is data here.
 *
 * The class strings are literals rather than something built from `tone`:
 * Tailwind scans `src/**\/*.{ts,html}`, so a literal in this file is found,
 * but a runtime-assembled `` `bg-${tone}/10` `` never would be.
 */
interface FeatureCard {
	icon: string;
	iconWrapperClass: string;
	iconClass: string;
	title: string;
	items: readonly string[];
}

/**
 * Profile. Port of frontend-react/src/pages/ProfilePage.tsx.
 *
 * Everything on it comes from the session -- name, email and role are read
 * off `AuthStore`, exactly as React read them off the Zustand store, and
 * the rest of the page is a list of features that do not exist yet. **No
 * `rxResource` here, deliberately: this page fetches nothing.** The one
 * profile endpoint the Go service exposes
 * (`UserService.getProfile`) is the dashboard's, not this page's -- see
 * phase-3-subfeature-3-handoff.md.
 */
@Component({
	selector: "app-profile-page",
	imports: [NgIcon, ...CARD_DIRECTIVES],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./profile-page.component.html",
})
export class ProfilePageComponent {
	private readonly store = inject(AuthStore);

	readonly user = this.store.user;

	/** `"STUDENT"` -> `"Student"`, as React's inline expression did. */
	readonly roleLabel = computed(() => {
		const role = this.user()?.role ?? "";
		return role.charAt(0) + role.slice(1).toLowerCase();
	});

	/**
	 * `charAt(0)`, not `[0]`: `noUncheckedIndexedAccess` types the index
	 * access `string | undefined`, and an empty name should render nothing
	 * rather than "undefined".
	 */
	readonly initials = computed(() => {
		const user = this.user();
		if (!user) return "";
		return user.firstName.charAt(0) + user.lastName.charAt(0);
	});

	readonly featureCards: readonly FeatureCard[] = [
		{
			icon: "lucideUser",
			iconWrapperClass: "rounded-lg bg-primary/10 p-2",
			iconClass: "text-primary",
			title: "Personal Information",
			items: [
				"Edit name and avatar",
				"Update email address",
				"Set school affiliation",
				"Choose primary instrument",
				"Select grade level (students)",
			],
		},
		{
			icon: "lucideMusic",
			iconWrapperClass: "rounded-lg bg-brass/10 p-2",
			iconClass: "text-brass",
			title: "Practice Preferences",
			items: [
				"Set default game mode",
				"Choose preferred scales",
				"Select difficulty level",
				"Configure notifications",
				"Set practice reminders",
			],
		},
		{
			icon: "lucideTarget",
			iconWrapperClass: "rounded-lg bg-primary/10 p-2",
			iconClass: "text-primary",
			title: "Practice Goals",
			items: [
				"Set weekly session targets",
				"Track accuracy goals",
				"Monitor speed improvements",
				"Build practice streaks",
				"Celebrate milestones",
			],
		},
		{
			icon: "lucideAward",
			iconWrapperClass: "rounded-lg bg-brass/10 p-2",
			iconClass: "text-brass",
			title: "Achievements & Badges",
			items: [
				"First Session badge",
				"Perfect Score achievements",
				"Speed Demon milestone",
				"Consistency rewards",
				"Scale Master completion",
			],
		},
		{
			icon: "lucideTrendingUp",
			iconWrapperClass: "rounded-lg bg-primary/10 p-2",
			iconClass: "text-primary",
			title: "Detailed Statistics",
			items: [
				"All-time performance stats",
				"Performance by scale",
				"Performance by octave",
				"Strongest/weakest areas",
				"Practice streak tracking",
			],
		},
		{
			icon: "lucideSchool",
			iconWrapperClass: "rounded-lg bg-brass/10 p-2",
			iconClass: "text-brass",
			title: "Connections",
			items: [
				"Link with teachers",
				"Connect parent accounts",
				"Manage student access",
				"Share progress reports",
				"Collaborate on goals",
			],
		},
	];
}

@if (user(); as currentUser) {
	<div class="min-h-screen px-4 py-8">
		<div class="container mx-auto max-w-4xl space-y-6">
			<div class="space-y-2 text-center">
				<h1 class="text-4xl font-bold">Profile</h1>
				<p class="text-lg text-muted-foreground">
					View and manage your personal information and preferences
				</p>
			</div>

			<!-- User profile header -->
			<div appCard className="shadow-lg">
				<div appCardContent className="p-6">
					<div
						class="flex flex-col items-center gap-6 md:flex-row md:items-start"
					>
						<div
							class="flex h-32 w-32 items-center justify-center rounded-full bg-primary text-4xl font-bold text-primary-foreground"
						>
							{{ initials() }}
						</div>
						<div class="flex-1 space-y-3 text-center md:text-left">
							<h2 class="text-3xl font-bold">
								{{ currentUser.firstName }} {{ currentUser.lastName }}
							</h2>
							<div class="space-y-1">
								<p class="text-muted-foreground">{{ currentUser.email }}</p>
								<div
									class="flex flex-wrap justify-center gap-2 md:justify-start"
								>
									<span
										class="rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary"
										>{{ roleLabel() }}</span
									>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Proposed features -->
			<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
				@for (card of featureCards; track card.title) {
					<div appCard>
						<div appCardHeader>
							<div class="flex items-center gap-3">
								<div [class]="card.iconWrapperClass">
									<ng-icon
										size="1.5rem"
										aria-hidden="true"
										[name]="card.icon"
										[class]="card.iconClass"
									/>
								</div>
								<h3 appCardTitle>{{ card.title }}</h3>
							</div>
						</div>
						<div appCardContent className="text-sm text-muted-foreground">
							<ul class="space-y-1">
								@for (item of card.items; track item) {
									<li>&bull; {{ item }}</li>
								}
							</ul>
						</div>
					</div>
				}
			</div>

			<!-- Coming soon notice -->
			<div appCard className="border-primary/20 bg-primary/5">
				<div appCardContent className="p-6 text-center">
					<h3 class="mb-2 text-xl font-bold">Coming Soon</h3>
					<p class="text-muted-foreground">
						Profile customization and detailed analytics features are currently
						in development. Check back soon for updates!
					</p>
				</div>
			</div>
		</div>
	</div>
}

// new-frontend/src/pages/ProfilePage.tsx
import { useAuthStore } from '@/stores/auth.store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { User, Target, Award, School, Music, TrendingUp } from 'lucide-react';

export function ProfilePage() {
  const user = useAuthStore((state) => state.user);

  if (!user) return null;

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="container mx-auto max-w-4xl space-y-6">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-bold">Profile</h1>
          <p className="text-muted-foreground text-lg">
            View and manage your personal information and preferences
          </p>
        </div>

        {/* User Profile Header */}
        <Card className="shadow-lg">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-6 items-center md:items-start">
              <div className="w-32 h-32 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-4xl font-bold">
                {user.firstName[0]}{user.lastName[0]}
              </div>
              <div className="flex-1 text-center md:text-left space-y-3">
                <h2 className="text-3xl font-bold">
                  {user.firstName} {user.lastName}
                </h2>
                <div className="space-y-1">
                  <p className="text-muted-foreground">{user.email}</p>
                  <div className="flex flex-wrap gap-2 justify-center md:justify-start">
                    <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium">
                      {user.role.charAt(0).toUpperCase() + user.role.slice(1)}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Proposed Features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-primary/10 p-2">
                  <User className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Personal Information</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• Edit name and avatar</li>
                <li>• Update email address</li>
                <li>• Set school affiliation</li>
                <li>• Choose primary instrument</li>
                <li>• Select grade level (students)</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-accent/10 p-2">
                  <Music className="h-6 w-6 text-accent" />
                </div>
                <CardTitle>Practice Preferences</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• Set default game mode</li>
                <li>• Choose preferred scales</li>
                <li>• Select difficulty level</li>
                <li>• Configure notifications</li>
                <li>• Set practice reminders</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-primary/10 p-2">
                  <Target className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Practice Goals</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• Set weekly session targets</li>
                <li>• Track accuracy goals</li>
                <li>• Monitor speed improvements</li>
                <li>• Build practice streaks</li>
                <li>• Celebrate milestones</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-accent/10 p-2">
                  <Award className="h-6 w-6 text-accent" />
                </div>
                <CardTitle>Achievements & Badges</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• First Session badge</li>
                <li>• Perfect Score achievements</li>
                <li>• Speed Demon milestone</li>
                <li>• Consistency rewards</li>
                <li>• Scale Master completion</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-primary/10 p-2">
                  <TrendingUp className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Detailed Statistics</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• All-time performance stats</li>
                <li>• Performance by scale</li>
                <li>• Performance by octave</li>
                <li>• Strongest/weakest areas</li>
                <li>• Practice streak tracking</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-accent/10 p-2">
                  <School className="h-6 w-6 text-accent" />
                </div>
                <CardTitle>Connections</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              <ul className="space-y-1">
                <li>• Link with teachers</li>
                <li>• Connect parent accounts</li>
                <li>• Manage student access</li>
                <li>• Share progress reports</li>
                <li>• Collaborate on goals</li>
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Coming Soon Notice */}
        <Card className="bg-primary/5 border-primary/20">
          <CardContent className="p-6 text-center">
            <h3 className="text-xl font-bold mb-2">Coming Soon</h3>
            <p className="text-muted-foreground">
              Profile customization and detailed analytics features are currently in development.
              Check back soon for updates!
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
