// frontend/src/app/auth/components/signup/signup-page.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	signal,
} from "@angular/core";
import {
	form,
	FormField,
	validateStandardSchema,
} from "@angular/forms/signals";
import { Router, RouterLink } from "@angular/router";
import { NgIcon } from "@ng-icons/core";

import { CARD_DIRECTIVES } from "../../../shared/components/ui/card.directive";
import { ButtonComponent } from "../../../shared/components/ui/button.component";
import { FormFieldComponent } from "../../../shared/components/forms/form-field.component";
import { FormInputDirective } from "../../../shared/components/forms/form-input.directive";
import { FormSelectDirective } from "../../../shared/components/forms/form-select.directive";
import { SelectComponent } from "../../../shared/components/ui/select.component";
import {
	signupSchema,
	type SignupFormData,
} from "../../../shared/validators/auth.schemas";
import { getErrorMessage } from "../../../shared/utils/error.utils";
import type { PasswordRequirement } from "../../models/auth.models";
import { AuthService } from "../../services/auth.service";
import { AuthStore } from "../../services/auth.store";
import { GoogleSignInButtonComponent } from "../google-sign-in-button/google-sign-in-button.component";

/** The five rules `signupSchema` enforces, as a live checklist. */
const PASSWORD_RULES: readonly {
	label: string;
	test: (password: string) => boolean;
}[] = [
	{ label: "At least 8 characters", test: (p) => p.length >= 8 },
	{ label: "Contains uppercase letter", test: (p) => /[A-Z]/.test(p) },
	{ label: "Contains lowercase letter", test: (p) => /[a-z]/.test(p) },
	{ label: "Contains number", test: (p) => /\d/.test(p) },
	{
		label: "Contains special character",
		test: (p) => /[!@#$%^&*(),.?":{}|<>]/.test(p),
	},
];

export interface PasswordStrength {
	label: string;
	barClass: string;
	textClass: string;
	width: string;
}

const NO_STRENGTH: PasswordStrength = {
	label: "",
	barClass: "",
	textClass: "",
	width: "0%",
};

const WEAK: PasswordStrength = {
	label: "Weak",
	barClass: "bg-destructive",
	textClass: "text-destructive",
	width: "25%",
};

/**
 * React's `getPasswordStrength()`, keyed on how many of the five rules are
 * met -- 0 nothing, 1-2 Weak, 3 Fair, 4 Good, 5 Strong.
 *
 * React derived the label's colour at runtime
 * (`color.replace("bg-", "text-")`), which Tailwind's scanner cannot see;
 * both class names are literals here so both actually exist in the
 * stylesheet. No baseline captures this panel -- it only appears once the
 * password field has focus or content -- so this is a fix, not a diff.
 */
const STRENGTH_BY_MET_COUNT: readonly PasswordStrength[] = [
	NO_STRENGTH,
	WEAK,
	WEAK,
	{
		label: "Fair",
		barClass: "bg-orange-500",
		textClass: "text-orange-500",
		width: "50%",
	},
	{
		label: "Good",
		barClass: "bg-yellow-500",
		textClass: "text-yellow-500",
		width: "75%",
	},
	{
		label: "Strong",
		barClass: "bg-green-500",
		textClass: "text-green-500",
		width: "100%",
	},
];

/**
 * Port of frontend-react/src/pages/SignupPage.tsx.
 *
 * The Signal Forms + zod wiring is the same four lines the login page uses
 * (see `login.component.ts`); what this page adds is the two things a
 * bigger form needs:
 *
 * - **A cross-field rule.** `signupSchema`'s `.refine()` reports "Passwords
 *   do not match" on `confirmPassword`, and `validateStandardSchema` maps
 *   each issue's path onto the matching field, so it lands on the right
 *   control with no extra wiring.
 * - **A custom control.** `<app-select appFormSelect [formField]="...">`
 *   binds because `SelectComponent` implements `FormValueControl<string>`.
 *
 * Registration deliberately does not sign the new account in -- same as
 * React. The user lands on `/login` with the notice "Account created!
 * Please log in.", which `auth.spec.ts` asserts verbatim.
 */
@Component({
	selector: "app-signup-page",
	imports: [
		ButtonComponent,
		FormField,
		FormFieldComponent,
		FormInputDirective,
		FormSelectDirective,
		GoogleSignInButtonComponent,
		NgIcon,
		RouterLink,
		SelectComponent,
		...CARD_DIRECTIVES,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: "./signup-page.component.html",
})
export class SignupPageComponent {
	private readonly auth = inject(AuthService);
	private readonly store = inject(AuthStore);
	private readonly router = inject(Router);

	private readonly model = signal<SignupFormData>({
		firstName: "",
		lastName: "",
		email: "",
		password: "",
		confirmPassword: "",
		role: "STUDENT",
	});

	readonly signupForm = form(this.model, (path) => {
		validateStandardSchema(path, signupSchema);
	});

	readonly pending = signal(false);
	readonly errorMessage = signal<string | null>(null);
	readonly showPassword = signal(false);
	readonly showConfirmPassword = signal(false);
	readonly passwordFocused = signal(false);

	protected readonly password = computed(() => this.model().password);

	readonly requirements = computed<PasswordRequirement[]>(() =>
		PASSWORD_RULES.map((rule) => ({
			label: rule.label,
			met: rule.test(this.password()),
		})),
	);

	readonly strength = computed<PasswordStrength>(() => {
		const met = this.requirements().filter(
			(requirement) => requirement.met,
		).length;
		return STRENGTH_BY_MET_COUNT[met] ?? NO_STRENGTH;
	});

	/** React showed the checklist while the field had focus or any content. */
	readonly showRequirements = computed(
		() => this.passwordFocused() || this.password().length > 0,
	);

	togglePassword(): void {
		this.showPassword.update((shown) => !shown);
	}

	toggleConfirmPassword(): void {
		this.showConfirmPassword.update((shown) => !shown);
	}

	submit(event: Event): void {
		event.preventDefault();
		if (this.pending()) return;

		this.signupForm().markAsTouched();
		if (this.signupForm().invalid()) return;

		this.pending.set(true);
		this.errorMessage.set(null);

		const data = this.model();
		this.auth
			.register({
				email: data.email,
				password: data.password,
				first_name: data.firstName,
				last_name: data.lastName,
				role: data.role,
			})
			.subscribe({
				next: () => {
					this.store.setNotice("success", "Account created! Please log in.");
					void this.router.navigateByUrl("/login");
				},
				error: (err: unknown) => {
					this.pending.set(false);
					this.errorMessage.set(getErrorMessage(err));
				},
			});
	}
}

<section class="flex min-h-screen items-center justify-center px-4 py-12">
	<div appCard className="w-full max-w-md shadow-lg">
		<div appCardHeader className="space-y-1 text-center">
			<div class="mb-4 flex justify-center">
				<div class="rounded-lg bg-primary p-3">
					<ng-icon
						name="lucideMusic"
						size="2rem"
						aria-hidden="true"
						class="text-primary-foreground"
					/>
				</div>
			</div>
			<h1 appCardTitle className="font-display text-3xl">
				Create Your Account
			</h1>
			<p appCardDescription className="text-base">
				Join Tremolo and start your musical journey
			</p>
		</div>

		<form (submit)="submit($event)">
			<div appCardContent className="flex flex-col gap-4">
				@if (errorMessage(); as message) {
					<p
						role="alert"
						class="rounded-md border-2 border-destructive bg-destructive/10 p-3 text-sm font-medium text-destructive"
					>
						{{ message }}
					</p>
				}

				<div class="grid grid-cols-2 gap-4">
					<app-form-field
						label="First Name"
						htmlFor="firstName"
						[field]="signupForm.firstName"
					>
						<input
							appFormInput
							id="firstName"
							type="text"
							autocomplete="given-name"
							placeholder="John"
							[formField]="signupForm.firstName"
						/>
					</app-form-field>

					<app-form-field
						label="Last Name"
						htmlFor="lastName"
						[field]="signupForm.lastName"
					>
						<input
							appFormInput
							id="lastName"
							type="text"
							autocomplete="family-name"
							placeholder="Doe"
							[formField]="signupForm.lastName"
						/>
					</app-form-field>
				</div>

				<app-form-field
					label="Email Address"
					htmlFor="email"
					[field]="signupForm.email"
				>
					<input
						appFormInput
						id="email"
						type="email"
						autocomplete="email"
						placeholder="you@example.com"
						[formField]="signupForm.email"
					/>
				</app-form-field>

				<app-form-field
					label="Password"
					htmlFor="password"
					[field]="signupForm.password"
				>
					<div class="relative">
						<input
							appFormInput
							id="password"
							class="pr-10"
							autocomplete="new-password"
							placeholder="••••••••"
							[type]="showPassword() ? 'text' : 'password'"
							[formField]="signupForm.password"
							(focus)="passwordFocused.set(true)"
							(blur)="passwordFocused.set(false)"
						/>
						<!-- Exact-match e2e locators; see the note in login.component.html. -->
						<button
							type="button"
							class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground"
							[attr.aria-label]="passwordToggleLabel()"
							[appTooltip]="passwordToggleLabel()"
							(click)="togglePassword()"
						>
							<ng-icon
								size="1rem"
								[name]="showPassword() ? 'lucideEyeOff' : 'lucideEye'"
								aria-hidden="true"
								class="h-4 w-4"
							/>
						</button>
					</div>

					@if (showRequirements()) {
						<div
							class="space-y-2 rounded-md border border-border bg-muted/50 p-3"
						>
							<p class="text-xs font-medium">Password Requirements:</p>
							<div class="space-y-1">
								@for (requirement of requirements(); track requirement.label) {
									<div class="flex items-center gap-2 text-xs">
										@if (requirement.met) {
											<ng-icon
												size="0.75rem"
												name="lucideCheck"
												aria-hidden="true"
												class="h-3 w-3 text-green-500"
											/>
										} @else {
											<ng-icon
												size="0.75rem"
												name="lucideX"
												aria-hidden="true"
												class="h-3 w-3 text-muted-foreground"
											/>
										}
										<span [class]="requirement.met ? 'text-green-500' : ''">{{
											requirement.label
										}}</span>
									</div>
								}
							</div>

							@if (password().length > 0) {
								<div class="space-y-1 pt-2">
									<div class="flex justify-between text-xs">
										<span>Strength:</span>
										<span [class]="'font-medium ' + strength().textClass">{{
											strength().label
										}}</span>
									</div>
									<div class="h-2 overflow-hidden rounded-full bg-muted">
										<div
											[class]="'h-full transition-all ' + strength().barClass"
											[style.width]="strength().width"
										></div>
									</div>
								</div>
							}
						</div>
					}
				</app-form-field>

				<app-form-field
					label="Confirm Password"
					htmlFor="confirmPassword"
					[field]="signupForm.confirmPassword"
				>
					<div class="relative">
						<input
							appFormInput
							id="confirmPassword"
							class="pr-10"
							autocomplete="new-password"
							placeholder="••••••••"
							[type]="showConfirmPassword() ? 'text' : 'password'"
							[formField]="signupForm.confirmPassword"
						/>
						<!-- Exact-match e2e locators; see the note in login.component.html. -->
						<button
							type="button"
							class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground"
							[attr.aria-label]="confirmPasswordToggleLabel()"
							[appTooltip]="confirmPasswordToggleLabel()"
							(click)="toggleConfirmPassword()"
						>
							<ng-icon
								size="1rem"
								[name]="showConfirmPassword() ? 'lucideEyeOff' : 'lucideEye'"
								aria-hidden="true"
								class="h-4 w-4"
							/>
						</button>
					</div>
				</app-form-field>

				<app-form-field
					label="I am a..."
					htmlFor="role"
					[field]="signupForm.role"
				>
					<app-select
						appFormSelect
						selectId="role"
						[formField]="signupForm.role"
					>
						<option value="STUDENT">Student</option>
						<option value="TEACHER">Teacher</option>
					</app-select>
				</app-form-field>

				@if (isTeacher()) {
					<app-form-field
						label="Invite code"
						htmlFor="inviteCode"
						[field]="signupForm.inviteCode"
						[error]="inviteCodeError()"
					>
						<input
							appFormInput
							id="inviteCode"
							type="text"
							autocomplete="off"
							placeholder="ABCD2345"
							[formField]="signupForm.inviteCode"
						/>
						<p class="text-xs text-muted-foreground">
							Ask your Tremolo contact for a code.
						</p>
					</app-form-field>
				}

				@if (isStudent()) {
					<app-form-field
						label="What grade are you in?"
						htmlFor="gradeLevel"
						[field]="signupForm.gradeLevel"
					>
						<app-select
							appFormSelect
							selectId="gradeLevel"
							[formField]="signupForm.gradeLevel"
						>
							<option value="">Select your grade</option>
							@for (option of gradeOptions; track option.value) {
								<option [value]="option.value">{{ option.label }}</option>
							}
						</app-select>
						<p class="text-xs text-muted-foreground">
							We ask so we know who the site is being used by. It is a grade,
							not a birthday, and it is never shown to other students.
						</p>
					</app-form-field>
				}
			</div>

			<div appCardFooter className="flex-col gap-4">
				<app-button
					type="submit"
					variant="brass"
					size="lg"
					className="w-full"
					[loading]="pending()"
				>
					Create Account
				</app-button>

				<p class="text-center text-xs text-muted-foreground">
					By creating an account you agree to our
					<a
						routerLink="/terms"
						class="font-medium text-primary underline-offset-4 hover:underline"
						>Terms of Service</a
					>
					and
					<a
						routerLink="/privacy"
						class="font-medium text-primary underline-offset-4 hover:underline"
						>Privacy Policy</a
					>.
				</p>

				<div class="relative w-full">
					<div class="absolute inset-0 flex items-center">
						<span class="w-full border-t"></span>
					</div>
					<div class="relative flex justify-center text-xs uppercase">
						<span class="bg-card px-2 text-muted-foreground"
							>Or continue with</span
						>
					</div>
				</div>

				<app-google-sign-in-button label="Sign up with Google" />

				<p class="text-center text-sm text-muted-foreground">
					Already have an account?
					<a
						routerLink="/login"
						class="font-medium text-primary underline-offset-4 hover:underline"
						>Login</a
					>
				</p>
			</div>
		</form>
	</div>
</section>

// new-frontend/src/pages/SignupPage.tsx
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, Music, Check, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { FormField } from '@/shared/components/forms/FormField';
import { FormInput } from '@/shared/components/forms/FormInput';
import { FormSelect } from '@/shared/components/forms/FormSelect';
import { signupSchema, type SignupFormData } from '@/features/auth/validation/schemas';
import { useRegister } from '@/shared/hooks/queries/useAuthQuery';
import { cn } from '@/lib/utils';
import type { PasswordRequirement, LoginLocationState } from '@/shared/types';
import type { ApiError } from '@/services/api/types';

export interface SignupPageProps {}

export function SignupPage() {
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [passwordFocused, setPasswordFocused] = useState(false);
  const navigate = useNavigate();
  const registerMutation = useRegister();

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
    setError,
  } = useForm<SignupFormData>({
    resolver: zodResolver(signupSchema),
    defaultValues: {
      role: 'student',
    },
  });

  // React Hook Form's watch() is intentionally not memoized
  // eslint-disable-next-line react-compiler/react-compiler
  const password = watch('password', '');

  // Password validation
  const passwordRequirements: PasswordRequirement[] = [
    { label: 'At least 8 characters', met: password.length >= 8 },
    { label: 'Contains uppercase letter', met: /[A-Z]/.test(password) },
    { label: 'Contains lowercase letter', met: /[a-z]/.test(password) },
    { label: 'Contains number', met: /\d/.test(password) },
    { label: 'Contains special character', met: /[!@#$%^&*(),.?":{}|<>]/.test(password) },
  ];

  // Password strength
  const getPasswordStrength = () => {
    const metCount = passwordRequirements.filter((req) => req.met).length;
    if (metCount === 0) return { label: '', color: '', width: '0%' };
    if (metCount <= 2) return { label: 'Weak', color: 'bg-destructive', width: '25%' };
    if (metCount === 3) return { label: 'Fair', color: 'bg-orange-500', width: '50%' };
    if (metCount === 4) return { label: 'Good', color: 'bg-yellow-500', width: '75%' };
    return { label: 'Strong', color: 'bg-green-500', width: '100%' };
  };

  const passwordStrength = getPasswordStrength();

  const onSubmit = async (data: SignupFormData) => {
    try {
      // Map form data to API format
      await registerMutation.mutateAsync({
        email: data.email,
        password: data.password,
        first_name: data.firstName,
        last_name: data.lastName,
        role: data.role,
      });
      
      const navState: LoginLocationState = {
        successMessage: 'Account created! Please log in.',
      };
      navigate('/login', { state: navState });
    } catch (err) {
      const apiError = err as ApiError;
      setError('root', {
        message: apiError.message || 'Registration failed. Please try again.',
      });
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center py-12 px-4">
      <Card className="w-full max-w-md shadow-lg">
        <CardHeader className="space-y-1 text-center">
          <div className="flex justify-center mb-4">
            <div className="rounded-lg bg-primary p-3">
              <Music className="h-8 w-8 text-primary-foreground" />
            </div>
          </div>
          <CardTitle className="text-3xl font-bold">Create Your Account</CardTitle>
          <CardDescription className="text-base">
            Join Tremolo and start your musical journey
          </CardDescription>
        </CardHeader>

        <form onSubmit={handleSubmit(onSubmit)}>
          <CardContent className="space-y-4">
            {errors.root && (
              <div className="p-3 rounded-md bg-destructive/10 border-2 border-destructive text-destructive text-sm font-medium">
                {errors.root.message}
              </div>
            )}

            <div className="grid grid-cols-2 gap-4">
              <FormField label="First Name" error={errors.firstName?.message} htmlFor="firstName">
                <FormInput
                  id="firstName"
                  placeholder="John"
                  autoComplete="given-name"
                  {...register('firstName')}
                  error={errors.firstName?.message}
                />
              </FormField>

              <FormField label="Last Name" error={errors.lastName?.message} htmlFor="lastName">
                <FormInput
                  id="lastName"
                  placeholder="Doe"
                  autoComplete="family-name"
                  {...register('lastName')}
                  error={errors.lastName?.message}
                />
              </FormField>
            </div>

            <FormField label="Email Address" error={errors.email?.message} htmlFor="email">
              <FormInput
                id="email"
                type="email"
                placeholder="you@example.com"
                autoComplete="email"
                {...register('email')}
                error={errors.email?.message}
              />
            </FormField>

            <FormField label="Password" error={errors.password?.message} htmlFor="password">
              <div className="relative">
                <FormInput
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  autoComplete="new-password"
                  className="pr-10"
                  {...register('password')}
                  error={errors.password?.message}
                  onFocus={() => setPasswordFocused(true)}
                  onBlur={() => setPasswordFocused(false)}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>

              {(passwordFocused || password) && (
                <div className="space-y-2 p-3 rounded-md bg-muted/50 border border-border">
                  <p className="text-xs font-medium">Password Requirements:</p>
                  <div className="space-y-1">
                    {passwordRequirements.map((req, index) => (
                      <div key={index} className="flex items-center gap-2 text-xs">
                        {req.met ? (
                          <Check className="h-3 w-3 text-green-500" />
                        ) : (
                          <X className="h-3 w-3 text-muted-foreground" />
                        )}
                        <span className={cn(req.met && 'text-green-500')}>{req.label}</span>
                      </div>
                    ))}
                  </div>

                  {password && (
                    <div className="space-y-1 pt-2">
                      <div className="flex justify-between text-xs">
                        <span>Strength:</span>
                        <span className={cn('font-medium', passwordStrength.color.replace('bg-', 'text-'))}>
                          {passwordStrength.label}
                        </span>
                      </div>
                      <div className="h-2 bg-muted rounded-full overflow-hidden">
                        <div
                          className={cn('h-full transition-all', passwordStrength.color)}
                          style={{ width: passwordStrength.width }}
                        />
                      </div>
                    </div>
                  )}
                </div>
              )}
            </FormField>

            <FormField label="Confirm Password" error={errors.confirmPassword?.message} htmlFor="confirmPassword">
              <div className="relative">
                <FormInput
                  id="confirmPassword"
                  type={showConfirmPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  autoComplete="new-password"
                  className="pr-10"
                  {...register('confirmPassword')}
                  error={errors.confirmPassword?.message}
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </FormField>

            <FormField label="I am a..." error={errors.role?.message} htmlFor="role">
              <FormSelect id="role" {...register('role')} error={errors.role?.message}>
                <option value="student">Student</option>
                <option value="teacher">Teacher</option>
                <option value="parent">Parent</option>
              </FormSelect>
            </FormField>
          </CardContent>

          <CardFooter className="flex flex-col space-y-4">
            <Button type="submit" className="w-full" size="lg" loading={registerMutation.isPending}>
              Create Account
            </Button>

            <p className="text-sm text-center text-muted-foreground">
              Already have an account?{' '}
              <Link to="/login" className="text-primary font-medium hover:underline">
                Login
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
